// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/proto/service/agent.proto

package service

import (
	context "context"
	endpoints "github.com/gsoultan/pontus/api/proto/endpoints"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_GetSystemInfo_FullMethodName       = "/api.proto.service.AgentService/GetSystemInfo"
	AgentService_UpdateConfig_FullMethodName        = "/api.proto.service.AgentService/UpdateConfig"
	AgentService_ExecuteCommand_FullMethodName      = "/api.proto.service.AgentService/ExecuteCommand"
	AgentService_RestartService_FullMethodName      = "/api.proto.service.AgentService/RestartService"
	AgentService_StreamLogs_FullMethodName          = "/api.proto.service.AgentService/StreamLogs"
	AgentService_ScheduleMaintenance_FullMethodName = "/api.proto.service.AgentService/ScheduleMaintenance"
	AgentService_SetupReplication_FullMethodName    = "/api.proto.service.AgentService/SetupReplication"
	AgentService_PromoteNode_FullMethodName         = "/api.proto.service.AgentService/PromoteNode"
	AgentService_InitializeDatabase_FullMethodName  = "/api.proto.service.AgentService/InitializeDatabase"
	AgentService_InstallDatabase_FullMethodName     = "/api.proto.service.AgentService/InstallDatabase"
	AgentService_BackupDatabase_FullMethodName      = "/api.proto.service.AgentService/BackupDatabase"
	AgentService_RestoreDatabase_FullMethodName     = "/api.proto.service.AgentService/RestoreDatabase"
	AgentService_GetPostgresInsights_FullMethodName = "/api.proto.service.AgentService/GetPostgresInsights"
	AgentService_ShutdownDatabase_FullMethodName    = "/api.proto.service.AgentService/ShutdownDatabase"
	AgentService_RemoveDatabase_FullMethodName      = "/api.proto.service.AgentService/RemoveDatabase"
	AgentService_VacuumDatabase_FullMethodName      = "/api.proto.service.AgentService/VacuumDatabase"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService defines the operations that can be performed on a database host.
type AgentServiceClient interface {
	// GetSystemInfo returns basic information about the host system.
	GetSystemInfo(ctx context.Context, in *endpoints.GetSystemInfoRequest, opts ...grpc.CallOption) (*endpoints.GetSystemInfoResponse, error)
	// UpdateConfig updates a configuration file on the host.
	UpdateConfig(ctx context.Context, in *endpoints.UpdateConfigRequest, opts ...grpc.CallOption) (*endpoints.UpdateConfigResponse, error)
	// ExecuteCommand executes a shell command on the host and streams the output.
	ExecuteCommand(ctx context.Context, in *endpoints.ExecuteCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.ExecuteCommandResponse], error)
	// RestartService restarts a system service (e.g., postgresql).
	RestartService(ctx context.Context, in *endpoints.RestartServiceRequest, opts ...grpc.CallOption) (*endpoints.RestartServiceResponse, error)
	// StreamLogs streams the logs of a database instance.
	StreamLogs(ctx context.Context, in *endpoints.LogStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.LogStreamResponse], error)
	// ScheduleMaintenance schedules a maintenance task.
	ScheduleMaintenance(ctx context.Context, in *endpoints.ScheduleMaintenanceRequest, opts ...grpc.CallOption) (*endpoints.ScheduleMaintenanceResponse, error)
	// SetupReplication configures the host as a replica of another host.
	SetupReplication(ctx context.Context, in *endpoints.SetupReplicationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.ReplicationProgress], error)
	// PromoteNode promotes a replica to a primary.
	PromoteNode(ctx context.Context, in *endpoints.PromoteNodeRequest, opts ...grpc.CallOption) (*endpoints.PromoteNodeResponse, error)
	// InitializeDatabase initializes a new database instance.
	InitializeDatabase(ctx context.Context, in *endpoints.InitializeDatabaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.InitializeProgress], error)
	// InstallDatabase installs the database software.
	InstallDatabase(ctx context.Context, in *endpoints.InstallDatabaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.InstallProgress], error)
	// BackupDatabase creates a backup of the database.
	BackupDatabase(ctx context.Context, in *endpoints.BackupDatabaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.BackupProgress], error)
	// RestoreDatabase restores the database from a backup.
	RestoreDatabase(ctx context.Context, in *endpoints.RestoreDatabaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.RestoreProgress], error)
	// GetPostgresInsights returns database-specific insights for Postgres.
	GetPostgresInsights(ctx context.Context, in *endpoints.GetPostgresInsightsRequest, opts ...grpc.CallOption) (*endpoints.GetPostgresInsightsResponse, error)
	// ShutdownDatabase stops the database service.
	ShutdownDatabase(ctx context.Context, in *endpoints.ShutdownDatabaseRequest, opts ...grpc.CallOption) (*endpoints.ShutdownDatabaseResponse, error)
	// RemoveDatabase stops the database and removes its data directory.
	RemoveDatabase(ctx context.Context, in *endpoints.RemoveDatabaseRequest, opts ...grpc.CallOption) (*endpoints.RemoveDatabaseResponse, error)
	// VacuumDatabase performs a VACUUM operation on the database.
	VacuumDatabase(ctx context.Context, in *endpoints.VacuumDatabaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.VacuumProgress], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) GetSystemInfo(ctx context.Context, in *endpoints.GetSystemInfoRequest, opts ...grpc.CallOption) (*endpoints.GetSystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetSystemInfoResponse)
	err := c.cc.Invoke(ctx, AgentService_GetSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateConfig(ctx context.Context, in *endpoints.UpdateConfigRequest, opts ...grpc.CallOption) (*endpoints.UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.UpdateConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ExecuteCommand(ctx context.Context, in *endpoints.ExecuteCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.ExecuteCommandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_ExecuteCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.ExecuteCommandRequest, endpoints.ExecuteCommandResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ExecuteCommandClient = grpc.ServerStreamingClient[endpoints.ExecuteCommandResponse]

func (c *agentServiceClient) RestartService(ctx context.Context, in *endpoints.RestartServiceRequest, opts ...grpc.CallOption) (*endpoints.RestartServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.RestartServiceResponse)
	err := c.cc.Invoke(ctx, AgentService_RestartService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamLogs(ctx context.Context, in *endpoints.LogStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.LogStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.LogStreamRequest, endpoints.LogStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamLogsClient = grpc.ServerStreamingClient[endpoints.LogStreamResponse]

func (c *agentServiceClient) ScheduleMaintenance(ctx context.Context, in *endpoints.ScheduleMaintenanceRequest, opts ...grpc.CallOption) (*endpoints.ScheduleMaintenanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.ScheduleMaintenanceResponse)
	err := c.cc.Invoke(ctx, AgentService_ScheduleMaintenance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SetupReplication(ctx context.Context, in *endpoints.SetupReplicationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.ReplicationProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[2], AgentService_SetupReplication_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.SetupReplicationRequest, endpoints.ReplicationProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SetupReplicationClient = grpc.ServerStreamingClient[endpoints.ReplicationProgress]

func (c *agentServiceClient) PromoteNode(ctx context.Context, in *endpoints.PromoteNodeRequest, opts ...grpc.CallOption) (*endpoints.PromoteNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.PromoteNodeResponse)
	err := c.cc.Invoke(ctx, AgentService_PromoteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) InitializeDatabase(ctx context.Context, in *endpoints.InitializeDatabaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.InitializeProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[3], AgentService_InitializeDatabase_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.InitializeDatabaseRequest, endpoints.InitializeProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_InitializeDatabaseClient = grpc.ServerStreamingClient[endpoints.InitializeProgress]

func (c *agentServiceClient) InstallDatabase(ctx context.Context, in *endpoints.InstallDatabaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.InstallProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[4], AgentService_InstallDatabase_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.InstallDatabaseRequest, endpoints.InstallProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_InstallDatabaseClient = grpc.ServerStreamingClient[endpoints.InstallProgress]

func (c *agentServiceClient) BackupDatabase(ctx context.Context, in *endpoints.BackupDatabaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.BackupProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[5], AgentService_BackupDatabase_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.BackupDatabaseRequest, endpoints.BackupProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_BackupDatabaseClient = grpc.ServerStreamingClient[endpoints.BackupProgress]

func (c *agentServiceClient) RestoreDatabase(ctx context.Context, in *endpoints.RestoreDatabaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.RestoreProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[6], AgentService_RestoreDatabase_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.RestoreDatabaseRequest, endpoints.RestoreProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_RestoreDatabaseClient = grpc.ServerStreamingClient[endpoints.RestoreProgress]

func (c *agentServiceClient) GetPostgresInsights(ctx context.Context, in *endpoints.GetPostgresInsightsRequest, opts ...grpc.CallOption) (*endpoints.GetPostgresInsightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetPostgresInsightsResponse)
	err := c.cc.Invoke(ctx, AgentService_GetPostgresInsights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ShutdownDatabase(ctx context.Context, in *endpoints.ShutdownDatabaseRequest, opts ...grpc.CallOption) (*endpoints.ShutdownDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.ShutdownDatabaseResponse)
	err := c.cc.Invoke(ctx, AgentService_ShutdownDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RemoveDatabase(ctx context.Context, in *endpoints.RemoveDatabaseRequest, opts ...grpc.CallOption) (*endpoints.RemoveDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.RemoveDatabaseResponse)
	err := c.cc.Invoke(ctx, AgentService_RemoveDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) VacuumDatabase(ctx context.Context, in *endpoints.VacuumDatabaseRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.VacuumProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[7], AgentService_VacuumDatabase_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.VacuumDatabaseRequest, endpoints.VacuumProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_VacuumDatabaseClient = grpc.ServerStreamingClient[endpoints.VacuumProgress]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService defines the operations that can be performed on a database host.
type AgentServiceServer interface {
	// GetSystemInfo returns basic information about the host system.
	GetSystemInfo(context.Context, *endpoints.GetSystemInfoRequest) (*endpoints.GetSystemInfoResponse, error)
	// UpdateConfig updates a configuration file on the host.
	UpdateConfig(context.Context, *endpoints.UpdateConfigRequest) (*endpoints.UpdateConfigResponse, error)
	// ExecuteCommand executes a shell command on the host and streams the output.
	ExecuteCommand(*endpoints.ExecuteCommandRequest, grpc.ServerStreamingServer[endpoints.ExecuteCommandResponse]) error
	// RestartService restarts a system service (e.g., postgresql).
	RestartService(context.Context, *endpoints.RestartServiceRequest) (*endpoints.RestartServiceResponse, error)
	// StreamLogs streams the logs of a database instance.
	StreamLogs(*endpoints.LogStreamRequest, grpc.ServerStreamingServer[endpoints.LogStreamResponse]) error
	// ScheduleMaintenance schedules a maintenance task.
	ScheduleMaintenance(context.Context, *endpoints.ScheduleMaintenanceRequest) (*endpoints.ScheduleMaintenanceResponse, error)
	// SetupReplication configures the host as a replica of another host.
	SetupReplication(*endpoints.SetupReplicationRequest, grpc.ServerStreamingServer[endpoints.ReplicationProgress]) error
	// PromoteNode promotes a replica to a primary.
	PromoteNode(context.Context, *endpoints.PromoteNodeRequest) (*endpoints.PromoteNodeResponse, error)
	// InitializeDatabase initializes a new database instance.
	InitializeDatabase(*endpoints.InitializeDatabaseRequest, grpc.ServerStreamingServer[endpoints.InitializeProgress]) error
	// InstallDatabase installs the database software.
	InstallDatabase(*endpoints.InstallDatabaseRequest, grpc.ServerStreamingServer[endpoints.InstallProgress]) error
	// BackupDatabase creates a backup of the database.
	BackupDatabase(*endpoints.BackupDatabaseRequest, grpc.ServerStreamingServer[endpoints.BackupProgress]) error
	// RestoreDatabase restores the database from a backup.
	RestoreDatabase(*endpoints.RestoreDatabaseRequest, grpc.ServerStreamingServer[endpoints.RestoreProgress]) error
	// GetPostgresInsights returns database-specific insights for Postgres.
	GetPostgresInsights(context.Context, *endpoints.GetPostgresInsightsRequest) (*endpoints.GetPostgresInsightsResponse, error)
	// ShutdownDatabase stops the database service.
	ShutdownDatabase(context.Context, *endpoints.ShutdownDatabaseRequest) (*endpoints.ShutdownDatabaseResponse, error)
	// RemoveDatabase stops the database and removes its data directory.
	RemoveDatabase(context.Context, *endpoints.RemoveDatabaseRequest) (*endpoints.RemoveDatabaseResponse, error)
	// VacuumDatabase performs a VACUUM operation on the database.
	VacuumDatabase(*endpoints.VacuumDatabaseRequest, grpc.ServerStreamingServer[endpoints.VacuumProgress]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) GetSystemInfo(context.Context, *endpoints.GetSystemInfoRequest) (*endpoints.GetSystemInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemInfo not implemented")
}
func (UnimplementedAgentServiceServer) UpdateConfig(context.Context, *endpoints.UpdateConfigRequest) (*endpoints.UpdateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedAgentServiceServer) ExecuteCommand(*endpoints.ExecuteCommandRequest, grpc.ServerStreamingServer[endpoints.ExecuteCommandResponse]) error {
	return status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedAgentServiceServer) RestartService(context.Context, *endpoints.RestartServiceRequest) (*endpoints.RestartServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartService not implemented")
}
func (UnimplementedAgentServiceServer) StreamLogs(*endpoints.LogStreamRequest, grpc.ServerStreamingServer[endpoints.LogStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedAgentServiceServer) ScheduleMaintenance(context.Context, *endpoints.ScheduleMaintenanceRequest) (*endpoints.ScheduleMaintenanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleMaintenance not implemented")
}
func (UnimplementedAgentServiceServer) SetupReplication(*endpoints.SetupReplicationRequest, grpc.ServerStreamingServer[endpoints.ReplicationProgress]) error {
	return status.Error(codes.Unimplemented, "method SetupReplication not implemented")
}
func (UnimplementedAgentServiceServer) PromoteNode(context.Context, *endpoints.PromoteNodeRequest) (*endpoints.PromoteNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromoteNode not implemented")
}
func (UnimplementedAgentServiceServer) InitializeDatabase(*endpoints.InitializeDatabaseRequest, grpc.ServerStreamingServer[endpoints.InitializeProgress]) error {
	return status.Error(codes.Unimplemented, "method InitializeDatabase not implemented")
}
func (UnimplementedAgentServiceServer) InstallDatabase(*endpoints.InstallDatabaseRequest, grpc.ServerStreamingServer[endpoints.InstallProgress]) error {
	return status.Error(codes.Unimplemented, "method InstallDatabase not implemented")
}
func (UnimplementedAgentServiceServer) BackupDatabase(*endpoints.BackupDatabaseRequest, grpc.ServerStreamingServer[endpoints.BackupProgress]) error {
	return status.Error(codes.Unimplemented, "method BackupDatabase not implemented")
}
func (UnimplementedAgentServiceServer) RestoreDatabase(*endpoints.RestoreDatabaseRequest, grpc.ServerStreamingServer[endpoints.RestoreProgress]) error {
	return status.Error(codes.Unimplemented, "method RestoreDatabase not implemented")
}
func (UnimplementedAgentServiceServer) GetPostgresInsights(context.Context, *endpoints.GetPostgresInsightsRequest) (*endpoints.GetPostgresInsightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPostgresInsights not implemented")
}
func (UnimplementedAgentServiceServer) ShutdownDatabase(context.Context, *endpoints.ShutdownDatabaseRequest) (*endpoints.ShutdownDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShutdownDatabase not implemented")
}
func (UnimplementedAgentServiceServer) RemoveDatabase(context.Context, *endpoints.RemoveDatabaseRequest) (*endpoints.RemoveDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDatabase not implemented")
}
func (UnimplementedAgentServiceServer) VacuumDatabase(*endpoints.VacuumDatabaseRequest, grpc.ServerStreamingServer[endpoints.VacuumProgress]) error {
	return status.Error(codes.Unimplemented, "method VacuumDatabase not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_GetSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetSystemInfo(ctx, req.(*endpoints.GetSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateConfig(ctx, req.(*endpoints.UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ExecuteCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.ExecuteCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).ExecuteCommand(m, &grpc.GenericServerStream[endpoints.ExecuteCommandRequest, endpoints.ExecuteCommandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ExecuteCommandServer = grpc.ServerStreamingServer[endpoints.ExecuteCommandResponse]

func _AgentService_RestartService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.RestartServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RestartService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RestartService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RestartService(ctx, req.(*endpoints.RestartServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.LogStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamLogs(m, &grpc.GenericServerStream[endpoints.LogStreamRequest, endpoints.LogStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamLogsServer = grpc.ServerStreamingServer[endpoints.LogStreamResponse]

func _AgentService_ScheduleMaintenance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.ScheduleMaintenanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ScheduleMaintenance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ScheduleMaintenance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ScheduleMaintenance(ctx, req.(*endpoints.ScheduleMaintenanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SetupReplication_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.SetupReplicationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).SetupReplication(m, &grpc.GenericServerStream[endpoints.SetupReplicationRequest, endpoints.ReplicationProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SetupReplicationServer = grpc.ServerStreamingServer[endpoints.ReplicationProgress]

func _AgentService_PromoteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.PromoteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PromoteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PromoteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PromoteNode(ctx, req.(*endpoints.PromoteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_InitializeDatabase_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.InitializeDatabaseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).InitializeDatabase(m, &grpc.GenericServerStream[endpoints.InitializeDatabaseRequest, endpoints.InitializeProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_InitializeDatabaseServer = grpc.ServerStreamingServer[endpoints.InitializeProgress]

func _AgentService_InstallDatabase_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.InstallDatabaseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).InstallDatabase(m, &grpc.GenericServerStream[endpoints.InstallDatabaseRequest, endpoints.InstallProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_InstallDatabaseServer = grpc.ServerStreamingServer[endpoints.InstallProgress]

func _AgentService_BackupDatabase_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.BackupDatabaseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).BackupDatabase(m, &grpc.GenericServerStream[endpoints.BackupDatabaseRequest, endpoints.BackupProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_BackupDatabaseServer = grpc.ServerStreamingServer[endpoints.BackupProgress]

func _AgentService_RestoreDatabase_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.RestoreDatabaseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).RestoreDatabase(m, &grpc.GenericServerStream[endpoints.RestoreDatabaseRequest, endpoints.RestoreProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_RestoreDatabaseServer = grpc.ServerStreamingServer[endpoints.RestoreProgress]

func _AgentService_GetPostgresInsights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetPostgresInsightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetPostgresInsights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetPostgresInsights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetPostgresInsights(ctx, req.(*endpoints.GetPostgresInsightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ShutdownDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.ShutdownDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ShutdownDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ShutdownDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ShutdownDatabase(ctx, req.(*endpoints.ShutdownDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RemoveDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.RemoveDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RemoveDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RemoveDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RemoveDatabase(ctx, req.(*endpoints.RemoveDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_VacuumDatabase_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.VacuumDatabaseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).VacuumDatabase(m, &grpc.GenericServerStream[endpoints.VacuumDatabaseRequest, endpoints.VacuumProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_VacuumDatabaseServer = grpc.ServerStreamingServer[endpoints.VacuumProgress]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.service.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystemInfo",
			Handler:    _AgentService_GetSystemInfo_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _AgentService_UpdateConfig_Handler,
		},
		{
			MethodName: "RestartService",
			Handler:    _AgentService_RestartService_Handler,
		},
		{
			MethodName: "ScheduleMaintenance",
			Handler:    _AgentService_ScheduleMaintenance_Handler,
		},
		{
			MethodName: "PromoteNode",
			Handler:    _AgentService_PromoteNode_Handler,
		},
		{
			MethodName: "GetPostgresInsights",
			Handler:    _AgentService_GetPostgresInsights_Handler,
		},
		{
			MethodName: "ShutdownDatabase",
			Handler:    _AgentService_ShutdownDatabase_Handler,
		},
		{
			MethodName: "RemoveDatabase",
			Handler:    _AgentService_RemoveDatabase_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteCommand",
			Handler:       _AgentService_ExecuteCommand_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _AgentService_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SetupReplication",
			Handler:       _AgentService_SetupReplication_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InitializeDatabase",
			Handler:       _AgentService_InitializeDatabase_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InstallDatabase",
			Handler:       _AgentService_InstallDatabase_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BackupDatabase",
			Handler:       _AgentService_BackupDatabase_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RestoreDatabase",
			Handler:       _AgentService_RestoreDatabase_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "VacuumDatabase",
			Handler:       _AgentService_VacuumDatabase_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/service/agent.proto",
}
