// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/service/agent.proto

package service

import (
	endpoints "github.com/gsoultan/pontus/api/proto/endpoints"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto_service_agent_proto protoreflect.FileDescriptor

const file_api_proto_service_agent_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/service/agent.proto\x12\x11api.proto.service\x1a\x1fapi/proto/endpoints/agent.proto2\xbd\r\n" +
	"\fAgentService\x12f\n" +
	"\rGetSystemInfo\x12).api.proto.endpoints.GetSystemInfoRequest\x1a*.api.proto.endpoints.GetSystemInfoResponse\x12c\n" +
	"\fUpdateConfig\x12(.api.proto.endpoints.UpdateConfigRequest\x1a).api.proto.endpoints.UpdateConfigResponse\x12k\n" +
	"\x0eExecuteCommand\x12*.api.proto.endpoints.ExecuteCommandRequest\x1a+.api.proto.endpoints.ExecuteCommandResponse0\x01\x12i\n" +
	"\x0eRestartService\x12*.api.proto.endpoints.RestartServiceRequest\x1a+.api.proto.endpoints.RestartServiceResponse\x12]\n" +
	"\n" +
	"StreamLogs\x12%.api.proto.endpoints.LogStreamRequest\x1a&.api.proto.endpoints.LogStreamResponse0\x01\x12x\n" +
	"\x13ScheduleMaintenance\x12/.api.proto.endpoints.ScheduleMaintenanceRequest\x1a0.api.proto.endpoints.ScheduleMaintenanceResponse\x12l\n" +
	"\x10SetupReplication\x12,.api.proto.endpoints.SetupReplicationRequest\x1a(.api.proto.endpoints.ReplicationProgress0\x01\x12`\n" +
	"\vPromoteNode\x12'.api.proto.endpoints.PromoteNodeRequest\x1a(.api.proto.endpoints.PromoteNodeResponse\x12o\n" +
	"\x12InitializeDatabase\x12..api.proto.endpoints.InitializeDatabaseRequest\x1a'.api.proto.endpoints.InitializeProgress0\x01\x12f\n" +
	"\x0fInstallDatabase\x12+.api.proto.endpoints.InstallDatabaseRequest\x1a$.api.proto.endpoints.InstallProgress0\x01\x12c\n" +
	"\x0eBackupDatabase\x12*.api.proto.endpoints.BackupDatabaseRequest\x1a#.api.proto.endpoints.BackupProgress0\x01\x12f\n" +
	"\x0fRestoreDatabase\x12+.api.proto.endpoints.RestoreDatabaseRequest\x1a$.api.proto.endpoints.RestoreProgress0\x01\x12x\n" +
	"\x13GetPostgresInsights\x12/.api.proto.endpoints.GetPostgresInsightsRequest\x1a0.api.proto.endpoints.GetPostgresInsightsResponse\x12o\n" +
	"\x10ShutdownDatabase\x12,.api.proto.endpoints.ShutdownDatabaseRequest\x1a-.api.proto.endpoints.ShutdownDatabaseResponse\x12i\n" +
	"\x0eRemoveDatabase\x12*.api.proto.endpoints.RemoveDatabaseRequest\x1a+.api.proto.endpoints.RemoveDatabaseResponse\x12c\n" +
	"\x0eVacuumDatabase\x12*.api.proto.endpoints.VacuumDatabaseRequest\x1a#.api.proto.endpoints.VacuumProgress0\x01B.Z,github.com/gsoultan/pontus/api/proto/serviceb\x06proto3"

var file_api_proto_service_agent_proto_goTypes = []any{
	(*endpoints.GetSystemInfoRequest)(nil),        // 0: api.proto.endpoints.GetSystemInfoRequest
	(*endpoints.UpdateConfigRequest)(nil),         // 1: api.proto.endpoints.UpdateConfigRequest
	(*endpoints.ExecuteCommandRequest)(nil),       // 2: api.proto.endpoints.ExecuteCommandRequest
	(*endpoints.RestartServiceRequest)(nil),       // 3: api.proto.endpoints.RestartServiceRequest
	(*endpoints.LogStreamRequest)(nil),            // 4: api.proto.endpoints.LogStreamRequest
	(*endpoints.ScheduleMaintenanceRequest)(nil),  // 5: api.proto.endpoints.ScheduleMaintenanceRequest
	(*endpoints.SetupReplicationRequest)(nil),     // 6: api.proto.endpoints.SetupReplicationRequest
	(*endpoints.PromoteNodeRequest)(nil),          // 7: api.proto.endpoints.PromoteNodeRequest
	(*endpoints.InitializeDatabaseRequest)(nil),   // 8: api.proto.endpoints.InitializeDatabaseRequest
	(*endpoints.InstallDatabaseRequest)(nil),      // 9: api.proto.endpoints.InstallDatabaseRequest
	(*endpoints.BackupDatabaseRequest)(nil),       // 10: api.proto.endpoints.BackupDatabaseRequest
	(*endpoints.RestoreDatabaseRequest)(nil),      // 11: api.proto.endpoints.RestoreDatabaseRequest
	(*endpoints.GetPostgresInsightsRequest)(nil),  // 12: api.proto.endpoints.GetPostgresInsightsRequest
	(*endpoints.ShutdownDatabaseRequest)(nil),     // 13: api.proto.endpoints.ShutdownDatabaseRequest
	(*endpoints.RemoveDatabaseRequest)(nil),       // 14: api.proto.endpoints.RemoveDatabaseRequest
	(*endpoints.VacuumDatabaseRequest)(nil),       // 15: api.proto.endpoints.VacuumDatabaseRequest
	(*endpoints.GetSystemInfoResponse)(nil),       // 16: api.proto.endpoints.GetSystemInfoResponse
	(*endpoints.UpdateConfigResponse)(nil),        // 17: api.proto.endpoints.UpdateConfigResponse
	(*endpoints.ExecuteCommandResponse)(nil),      // 18: api.proto.endpoints.ExecuteCommandResponse
	(*endpoints.RestartServiceResponse)(nil),      // 19: api.proto.endpoints.RestartServiceResponse
	(*endpoints.LogStreamResponse)(nil),           // 20: api.proto.endpoints.LogStreamResponse
	(*endpoints.ScheduleMaintenanceResponse)(nil), // 21: api.proto.endpoints.ScheduleMaintenanceResponse
	(*endpoints.ReplicationProgress)(nil),         // 22: api.proto.endpoints.ReplicationProgress
	(*endpoints.PromoteNodeResponse)(nil),         // 23: api.proto.endpoints.PromoteNodeResponse
	(*endpoints.InitializeProgress)(nil),          // 24: api.proto.endpoints.InitializeProgress
	(*endpoints.InstallProgress)(nil),             // 25: api.proto.endpoints.InstallProgress
	(*endpoints.BackupProgress)(nil),              // 26: api.proto.endpoints.BackupProgress
	(*endpoints.RestoreProgress)(nil),             // 27: api.proto.endpoints.RestoreProgress
	(*endpoints.GetPostgresInsightsResponse)(nil), // 28: api.proto.endpoints.GetPostgresInsightsResponse
	(*endpoints.ShutdownDatabaseResponse)(nil),    // 29: api.proto.endpoints.ShutdownDatabaseResponse
	(*endpoints.RemoveDatabaseResponse)(nil),      // 30: api.proto.endpoints.RemoveDatabaseResponse
	(*endpoints.VacuumProgress)(nil),              // 31: api.proto.endpoints.VacuumProgress
}
var file_api_proto_service_agent_proto_depIdxs = []int32{
	0,  // 0: api.proto.service.AgentService.GetSystemInfo:input_type -> api.proto.endpoints.GetSystemInfoRequest
	1,  // 1: api.proto.service.AgentService.UpdateConfig:input_type -> api.proto.endpoints.UpdateConfigRequest
	2,  // 2: api.proto.service.AgentService.ExecuteCommand:input_type -> api.proto.endpoints.ExecuteCommandRequest
	3,  // 3: api.proto.service.AgentService.RestartService:input_type -> api.proto.endpoints.RestartServiceRequest
	4,  // 4: api.proto.service.AgentService.StreamLogs:input_type -> api.proto.endpoints.LogStreamRequest
	5,  // 5: api.proto.service.AgentService.ScheduleMaintenance:input_type -> api.proto.endpoints.ScheduleMaintenanceRequest
	6,  // 6: api.proto.service.AgentService.SetupReplication:input_type -> api.proto.endpoints.SetupReplicationRequest
	7,  // 7: api.proto.service.AgentService.PromoteNode:input_type -> api.proto.endpoints.PromoteNodeRequest
	8,  // 8: api.proto.service.AgentService.InitializeDatabase:input_type -> api.proto.endpoints.InitializeDatabaseRequest
	9,  // 9: api.proto.service.AgentService.InstallDatabase:input_type -> api.proto.endpoints.InstallDatabaseRequest
	10, // 10: api.proto.service.AgentService.BackupDatabase:input_type -> api.proto.endpoints.BackupDatabaseRequest
	11, // 11: api.proto.service.AgentService.RestoreDatabase:input_type -> api.proto.endpoints.RestoreDatabaseRequest
	12, // 12: api.proto.service.AgentService.GetPostgresInsights:input_type -> api.proto.endpoints.GetPostgresInsightsRequest
	13, // 13: api.proto.service.AgentService.ShutdownDatabase:input_type -> api.proto.endpoints.ShutdownDatabaseRequest
	14, // 14: api.proto.service.AgentService.RemoveDatabase:input_type -> api.proto.endpoints.RemoveDatabaseRequest
	15, // 15: api.proto.service.AgentService.VacuumDatabase:input_type -> api.proto.endpoints.VacuumDatabaseRequest
	16, // 16: api.proto.service.AgentService.GetSystemInfo:output_type -> api.proto.endpoints.GetSystemInfoResponse
	17, // 17: api.proto.service.AgentService.UpdateConfig:output_type -> api.proto.endpoints.UpdateConfigResponse
	18, // 18: api.proto.service.AgentService.ExecuteCommand:output_type -> api.proto.endpoints.ExecuteCommandResponse
	19, // 19: api.proto.service.AgentService.RestartService:output_type -> api.proto.endpoints.RestartServiceResponse
	20, // 20: api.proto.service.AgentService.StreamLogs:output_type -> api.proto.endpoints.LogStreamResponse
	21, // 21: api.proto.service.AgentService.ScheduleMaintenance:output_type -> api.proto.endpoints.ScheduleMaintenanceResponse
	22, // 22: api.proto.service.AgentService.SetupReplication:output_type -> api.proto.endpoints.ReplicationProgress
	23, // 23: api.proto.service.AgentService.PromoteNode:output_type -> api.proto.endpoints.PromoteNodeResponse
	24, // 24: api.proto.service.AgentService.InitializeDatabase:output_type -> api.proto.endpoints.InitializeProgress
	25, // 25: api.proto.service.AgentService.InstallDatabase:output_type -> api.proto.endpoints.InstallProgress
	26, // 26: api.proto.service.AgentService.BackupDatabase:output_type -> api.proto.endpoints.BackupProgress
	27, // 27: api.proto.service.AgentService.RestoreDatabase:output_type -> api.proto.endpoints.RestoreProgress
	28, // 28: api.proto.service.AgentService.GetPostgresInsights:output_type -> api.proto.endpoints.GetPostgresInsightsResponse
	29, // 29: api.proto.service.AgentService.ShutdownDatabase:output_type -> api.proto.endpoints.ShutdownDatabaseResponse
	30, // 30: api.proto.service.AgentService.RemoveDatabase:output_type -> api.proto.endpoints.RemoveDatabaseResponse
	31, // 31: api.proto.service.AgentService.VacuumDatabase:output_type -> api.proto.endpoints.VacuumProgress
	16, // [16:32] is the sub-list for method output_type
	0,  // [0:16] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_service_agent_proto_init() }
func file_api_proto_service_agent_proto_init() {
	if File_api_proto_service_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_service_agent_proto_rawDesc), len(file_api_proto_service_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_service_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_service_agent_proto_depIdxs,
	}.Build()
	File_api_proto_service_agent_proto = out.File
	file_api_proto_service_agent_proto_goTypes = nil
	file_api_proto_service_agent_proto_depIdxs = nil
}
