// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/service/management.proto

package service

import (
	domain "github.com/gsoultan/pontus/api/proto/domain"
	endpoints "github.com/gsoultan/pontus/api/proto/endpoints"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto_service_management_proto protoreflect.FileDescriptor

const file_api_proto_service_management_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/service/management.proto\x12\x11api.proto.service\x1a$api/proto/endpoints/management.proto\x1a\x1aapi/proto/domain/log.proto2\xb2\x1e\n" +
	"\x11ManagementService\x12c\n" +
	"\fListProjects\x12(.api.proto.endpoints.ListProjectsRequest\x1a).api.proto.endpoints.ListProjectsResponse\x12f\n" +
	"\rCreateProject\x12).api.proto.endpoints.CreateProjectRequest\x1a*.api.proto.endpoints.CreateProjectResponse\x12f\n" +
	"\rDeleteProject\x12).api.proto.endpoints.DeleteProjectRequest\x1a*.api.proto.endpoints.DeleteProjectResponse\x12W\n" +
	"\bAddProxy\x12$.api.proto.endpoints.AddProxyRequest\x1a%.api.proto.endpoints.AddProxyResponse\x12`\n" +
	"\vRemoveProxy\x12'.api.proto.endpoints.RemoveProxyRequest\x1a(.api.proto.endpoints.RemoveProxyResponse\x12`\n" +
	"\vUpdateProxy\x12'.api.proto.endpoints.UpdateProxyRequest\x1a(.api.proto.endpoints.UpdateProxyResponse\x12Z\n" +
	"\tGetStatus\x12%.api.proto.endpoints.GetStatusRequest\x1a&.api.proto.endpoints.GetStatusResponse\x12b\n" +
	"\fStreamStatus\x12(.api.proto.endpoints.StreamStatusRequest\x1a&.api.proto.endpoints.GetStatusResponse0\x01\x12]\n" +
	"\n" +
	"AddBackend\x12&.api.proto.endpoints.AddBackendRequest\x1a'.api.proto.endpoints.AddBackendResponse\x12f\n" +
	"\rRemoveBackend\x12).api.proto.endpoints.RemoveBackendRequest\x1a*.api.proto.endpoints.RemoveBackendResponse\x12f\n" +
	"\rUpdateBackend\x12).api.proto.endpoints.UpdateBackendRequest\x1a*.api.proto.endpoints.UpdateBackendResponse\x12j\n" +
	"\x10ProvisionReplica\x12,.api.proto.endpoints.ProvisionReplicaRequest\x1a&.api.proto.endpoints.ProvisionProgress0\x01\x12l\n" +
	"\x0fValidateBackend\x12+.api.proto.endpoints.ValidateBackendRequest\x1a,.api.proto.endpoints.ValidateBackendResponse\x12R\n" +
	"\n" +
	"StreamLogs\x12&.api.proto.endpoints.StreamLogsRequest\x1a\x1a.api.proto.domain.LogEntry0\x01\x12k\n" +
	"\x0eInitializeNode\x12*.api.proto.endpoints.InitializeNodeRequest\x1a+.api.proto.endpoints.InitializeNodeProgress0\x01\x12b\n" +
	"\vInstallNode\x12'.api.proto.endpoints.InstallNodeRequest\x1a(.api.proto.endpoints.InstallNodeProgress0\x01\x12h\n" +
	"\rBackupBackend\x12).api.proto.endpoints.BackupBackendRequest\x1a*.api.proto.endpoints.BackupBackendProgress0\x01\x12k\n" +
	"\x0eRestoreBackend\x12*.api.proto.endpoints.RestoreBackendRequest\x1a+.api.proto.endpoints.RestoreBackendProgress0\x01\x12i\n" +
	"\x0ePromoteBackend\x12*.api.proto.endpoints.PromoteBackendRequest\x1a+.api.proto.endpoints.PromoteBackendResponse\x12r\n" +
	"\x11GetMetricsHistory\x12-.api.proto.endpoints.GetMetricsHistoryRequest\x1a..api.proto.endpoints.GetMetricsHistoryResponse\x12{\n" +
	"\x14GetTopQueriesHistory\x120.api.proto.endpoints.GetTopQueriesHistoryRequest\x1a1.api.proto.endpoints.GetTopQueriesHistoryResponse\x12o\n" +
	"\x10SetClusterConfig\x12,.api.proto.endpoints.SetClusterConfigRequest\x1a-.api.proto.endpoints.SetClusterConfigResponse\x12o\n" +
	"\x10GetClusterConfig\x12,.api.proto.endpoints.GetClusterConfigRequest\x1a-.api.proto.endpoints.GetClusterConfigResponse\x12l\n" +
	"\x0fDiscoverCluster\x12+.api.proto.endpoints.DiscoverClusterRequest\x1a,.api.proto.endpoints.DiscoverClusterResponse\x12h\n" +
	"\rVacuumBackend\x12).api.proto.endpoints.VacuumBackendRequest\x1a*.api.proto.endpoints.VacuumBackendProgress0\x01\x12c\n" +
	"\fExplainQuery\x12(.api.proto.endpoints.ExplainQueryRequest\x1a).api.proto.endpoints.ExplainQueryResponse\x12T\n" +
	"\aGetLogs\x12#.api.proto.endpoints.GetLogsRequest\x1a$.api.proto.endpoints.GetLogsResponse\x12c\n" +
	"\fTuneDatabase\x12(.api.proto.endpoints.TuneDatabaseRequest\x1a).api.proto.endpoints.TuneDatabaseResponse\x12`\n" +
	"\vApplyTuning\x12'.api.proto.endpoints.ApplyTuningRequest\x1a(.api.proto.endpoints.ApplyTuningResponse\x12c\n" +
	"\fGetAgentInfo\x12(.api.proto.endpoints.GetAgentInfoRequest\x1a).api.proto.endpoints.GetAgentInfoResponse\x12{\n" +
	"\x14GetAvailableVersions\x120.api.proto.endpoints.GetAvailableVersionsRequest\x1a1.api.proto.endpoints.GetAvailableVersionsResponse\x12N\n" +
	"\x05Login\x12!.api.proto.endpoints.LoginRequest\x1a\".api.proto.endpoints.LoginResponse\x12]\n" +
	"\n" +
	"CreateUser\x12&.api.proto.endpoints.CreateUserRequest\x1a'.api.proto.endpoints.CreateUserResponse\x12f\n" +
	"\rGetServerInfo\x12).api.proto.endpoints.GetServerInfoRequest\x1a*.api.proto.endpoints.GetServerInfoResponse\x12\x86\x01\n" +
	"\x13GetPostgresInsights\x126.api.proto.endpoints.GetBackendPostgresInsightsRequest\x1a7.api.proto.endpoints.GetBackendPostgresInsightsResponse\x12~\n" +
	"\x15RestartBackendService\x121.api.proto.endpoints.RestartBackendServiceRequest\x1a2.api.proto.endpoints.RestartBackendServiceResponse\x12l\n" +
	"\x0fShutdownBackend\x12+.api.proto.endpoints.ShutdownBackendRequest\x1a,.api.proto.endpoints.ShutdownBackendResponseB.Z,github.com/gsoultan/pontus/api/proto/serviceb\x06proto3"

var file_api_proto_service_management_proto_goTypes = []any{
	(*endpoints.ListProjectsRequest)(nil),                // 0: api.proto.endpoints.ListProjectsRequest
	(*endpoints.CreateProjectRequest)(nil),               // 1: api.proto.endpoints.CreateProjectRequest
	(*endpoints.DeleteProjectRequest)(nil),               // 2: api.proto.endpoints.DeleteProjectRequest
	(*endpoints.AddProxyRequest)(nil),                    // 3: api.proto.endpoints.AddProxyRequest
	(*endpoints.RemoveProxyRequest)(nil),                 // 4: api.proto.endpoints.RemoveProxyRequest
	(*endpoints.UpdateProxyRequest)(nil),                 // 5: api.proto.endpoints.UpdateProxyRequest
	(*endpoints.GetStatusRequest)(nil),                   // 6: api.proto.endpoints.GetStatusRequest
	(*endpoints.StreamStatusRequest)(nil),                // 7: api.proto.endpoints.StreamStatusRequest
	(*endpoints.AddBackendRequest)(nil),                  // 8: api.proto.endpoints.AddBackendRequest
	(*endpoints.RemoveBackendRequest)(nil),               // 9: api.proto.endpoints.RemoveBackendRequest
	(*endpoints.UpdateBackendRequest)(nil),               // 10: api.proto.endpoints.UpdateBackendRequest
	(*endpoints.ProvisionReplicaRequest)(nil),            // 11: api.proto.endpoints.ProvisionReplicaRequest
	(*endpoints.ValidateBackendRequest)(nil),             // 12: api.proto.endpoints.ValidateBackendRequest
	(*endpoints.StreamLogsRequest)(nil),                  // 13: api.proto.endpoints.StreamLogsRequest
	(*endpoints.InitializeNodeRequest)(nil),              // 14: api.proto.endpoints.InitializeNodeRequest
	(*endpoints.InstallNodeRequest)(nil),                 // 15: api.proto.endpoints.InstallNodeRequest
	(*endpoints.BackupBackendRequest)(nil),               // 16: api.proto.endpoints.BackupBackendRequest
	(*endpoints.RestoreBackendRequest)(nil),              // 17: api.proto.endpoints.RestoreBackendRequest
	(*endpoints.PromoteBackendRequest)(nil),              // 18: api.proto.endpoints.PromoteBackendRequest
	(*endpoints.GetMetricsHistoryRequest)(nil),           // 19: api.proto.endpoints.GetMetricsHistoryRequest
	(*endpoints.GetTopQueriesHistoryRequest)(nil),        // 20: api.proto.endpoints.GetTopQueriesHistoryRequest
	(*endpoints.SetClusterConfigRequest)(nil),            // 21: api.proto.endpoints.SetClusterConfigRequest
	(*endpoints.GetClusterConfigRequest)(nil),            // 22: api.proto.endpoints.GetClusterConfigRequest
	(*endpoints.DiscoverClusterRequest)(nil),             // 23: api.proto.endpoints.DiscoverClusterRequest
	(*endpoints.VacuumBackendRequest)(nil),               // 24: api.proto.endpoints.VacuumBackendRequest
	(*endpoints.ExplainQueryRequest)(nil),                // 25: api.proto.endpoints.ExplainQueryRequest
	(*endpoints.GetLogsRequest)(nil),                     // 26: api.proto.endpoints.GetLogsRequest
	(*endpoints.TuneDatabaseRequest)(nil),                // 27: api.proto.endpoints.TuneDatabaseRequest
	(*endpoints.ApplyTuningRequest)(nil),                 // 28: api.proto.endpoints.ApplyTuningRequest
	(*endpoints.GetAgentInfoRequest)(nil),                // 29: api.proto.endpoints.GetAgentInfoRequest
	(*endpoints.GetAvailableVersionsRequest)(nil),        // 30: api.proto.endpoints.GetAvailableVersionsRequest
	(*endpoints.LoginRequest)(nil),                       // 31: api.proto.endpoints.LoginRequest
	(*endpoints.CreateUserRequest)(nil),                  // 32: api.proto.endpoints.CreateUserRequest
	(*endpoints.GetServerInfoRequest)(nil),               // 33: api.proto.endpoints.GetServerInfoRequest
	(*endpoints.GetBackendPostgresInsightsRequest)(nil),  // 34: api.proto.endpoints.GetBackendPostgresInsightsRequest
	(*endpoints.RestartBackendServiceRequest)(nil),       // 35: api.proto.endpoints.RestartBackendServiceRequest
	(*endpoints.ShutdownBackendRequest)(nil),             // 36: api.proto.endpoints.ShutdownBackendRequest
	(*endpoints.ListProjectsResponse)(nil),               // 37: api.proto.endpoints.ListProjectsResponse
	(*endpoints.CreateProjectResponse)(nil),              // 38: api.proto.endpoints.CreateProjectResponse
	(*endpoints.DeleteProjectResponse)(nil),              // 39: api.proto.endpoints.DeleteProjectResponse
	(*endpoints.AddProxyResponse)(nil),                   // 40: api.proto.endpoints.AddProxyResponse
	(*endpoints.RemoveProxyResponse)(nil),                // 41: api.proto.endpoints.RemoveProxyResponse
	(*endpoints.UpdateProxyResponse)(nil),                // 42: api.proto.endpoints.UpdateProxyResponse
	(*endpoints.GetStatusResponse)(nil),                  // 43: api.proto.endpoints.GetStatusResponse
	(*endpoints.AddBackendResponse)(nil),                 // 44: api.proto.endpoints.AddBackendResponse
	(*endpoints.RemoveBackendResponse)(nil),              // 45: api.proto.endpoints.RemoveBackendResponse
	(*endpoints.UpdateBackendResponse)(nil),              // 46: api.proto.endpoints.UpdateBackendResponse
	(*endpoints.ProvisionProgress)(nil),                  // 47: api.proto.endpoints.ProvisionProgress
	(*endpoints.ValidateBackendResponse)(nil),            // 48: api.proto.endpoints.ValidateBackendResponse
	(*domain.LogEntry)(nil),                              // 49: api.proto.domain.LogEntry
	(*endpoints.InitializeNodeProgress)(nil),             // 50: api.proto.endpoints.InitializeNodeProgress
	(*endpoints.InstallNodeProgress)(nil),                // 51: api.proto.endpoints.InstallNodeProgress
	(*endpoints.BackupBackendProgress)(nil),              // 52: api.proto.endpoints.BackupBackendProgress
	(*endpoints.RestoreBackendProgress)(nil),             // 53: api.proto.endpoints.RestoreBackendProgress
	(*endpoints.PromoteBackendResponse)(nil),             // 54: api.proto.endpoints.PromoteBackendResponse
	(*endpoints.GetMetricsHistoryResponse)(nil),          // 55: api.proto.endpoints.GetMetricsHistoryResponse
	(*endpoints.GetTopQueriesHistoryResponse)(nil),       // 56: api.proto.endpoints.GetTopQueriesHistoryResponse
	(*endpoints.SetClusterConfigResponse)(nil),           // 57: api.proto.endpoints.SetClusterConfigResponse
	(*endpoints.GetClusterConfigResponse)(nil),           // 58: api.proto.endpoints.GetClusterConfigResponse
	(*endpoints.DiscoverClusterResponse)(nil),            // 59: api.proto.endpoints.DiscoverClusterResponse
	(*endpoints.VacuumBackendProgress)(nil),              // 60: api.proto.endpoints.VacuumBackendProgress
	(*endpoints.ExplainQueryResponse)(nil),               // 61: api.proto.endpoints.ExplainQueryResponse
	(*endpoints.GetLogsResponse)(nil),                    // 62: api.proto.endpoints.GetLogsResponse
	(*endpoints.TuneDatabaseResponse)(nil),               // 63: api.proto.endpoints.TuneDatabaseResponse
	(*endpoints.ApplyTuningResponse)(nil),                // 64: api.proto.endpoints.ApplyTuningResponse
	(*endpoints.GetAgentInfoResponse)(nil),               // 65: api.proto.endpoints.GetAgentInfoResponse
	(*endpoints.GetAvailableVersionsResponse)(nil),       // 66: api.proto.endpoints.GetAvailableVersionsResponse
	(*endpoints.LoginResponse)(nil),                      // 67: api.proto.endpoints.LoginResponse
	(*endpoints.CreateUserResponse)(nil),                 // 68: api.proto.endpoints.CreateUserResponse
	(*endpoints.GetServerInfoResponse)(nil),              // 69: api.proto.endpoints.GetServerInfoResponse
	(*endpoints.GetBackendPostgresInsightsResponse)(nil), // 70: api.proto.endpoints.GetBackendPostgresInsightsResponse
	(*endpoints.RestartBackendServiceResponse)(nil),      // 71: api.proto.endpoints.RestartBackendServiceResponse
	(*endpoints.ShutdownBackendResponse)(nil),            // 72: api.proto.endpoints.ShutdownBackendResponse
}
var file_api_proto_service_management_proto_depIdxs = []int32{
	0,  // 0: api.proto.service.ManagementService.ListProjects:input_type -> api.proto.endpoints.ListProjectsRequest
	1,  // 1: api.proto.service.ManagementService.CreateProject:input_type -> api.proto.endpoints.CreateProjectRequest
	2,  // 2: api.proto.service.ManagementService.DeleteProject:input_type -> api.proto.endpoints.DeleteProjectRequest
	3,  // 3: api.proto.service.ManagementService.AddProxy:input_type -> api.proto.endpoints.AddProxyRequest
	4,  // 4: api.proto.service.ManagementService.RemoveProxy:input_type -> api.proto.endpoints.RemoveProxyRequest
	5,  // 5: api.proto.service.ManagementService.UpdateProxy:input_type -> api.proto.endpoints.UpdateProxyRequest
	6,  // 6: api.proto.service.ManagementService.GetStatus:input_type -> api.proto.endpoints.GetStatusRequest
	7,  // 7: api.proto.service.ManagementService.StreamStatus:input_type -> api.proto.endpoints.StreamStatusRequest
	8,  // 8: api.proto.service.ManagementService.AddBackend:input_type -> api.proto.endpoints.AddBackendRequest
	9,  // 9: api.proto.service.ManagementService.RemoveBackend:input_type -> api.proto.endpoints.RemoveBackendRequest
	10, // 10: api.proto.service.ManagementService.UpdateBackend:input_type -> api.proto.endpoints.UpdateBackendRequest
	11, // 11: api.proto.service.ManagementService.ProvisionReplica:input_type -> api.proto.endpoints.ProvisionReplicaRequest
	12, // 12: api.proto.service.ManagementService.ValidateBackend:input_type -> api.proto.endpoints.ValidateBackendRequest
	13, // 13: api.proto.service.ManagementService.StreamLogs:input_type -> api.proto.endpoints.StreamLogsRequest
	14, // 14: api.proto.service.ManagementService.InitializeNode:input_type -> api.proto.endpoints.InitializeNodeRequest
	15, // 15: api.proto.service.ManagementService.InstallNode:input_type -> api.proto.endpoints.InstallNodeRequest
	16, // 16: api.proto.service.ManagementService.BackupBackend:input_type -> api.proto.endpoints.BackupBackendRequest
	17, // 17: api.proto.service.ManagementService.RestoreBackend:input_type -> api.proto.endpoints.RestoreBackendRequest
	18, // 18: api.proto.service.ManagementService.PromoteBackend:input_type -> api.proto.endpoints.PromoteBackendRequest
	19, // 19: api.proto.service.ManagementService.GetMetricsHistory:input_type -> api.proto.endpoints.GetMetricsHistoryRequest
	20, // 20: api.proto.service.ManagementService.GetTopQueriesHistory:input_type -> api.proto.endpoints.GetTopQueriesHistoryRequest
	21, // 21: api.proto.service.ManagementService.SetClusterConfig:input_type -> api.proto.endpoints.SetClusterConfigRequest
	22, // 22: api.proto.service.ManagementService.GetClusterConfig:input_type -> api.proto.endpoints.GetClusterConfigRequest
	23, // 23: api.proto.service.ManagementService.DiscoverCluster:input_type -> api.proto.endpoints.DiscoverClusterRequest
	24, // 24: api.proto.service.ManagementService.VacuumBackend:input_type -> api.proto.endpoints.VacuumBackendRequest
	25, // 25: api.proto.service.ManagementService.ExplainQuery:input_type -> api.proto.endpoints.ExplainQueryRequest
	26, // 26: api.proto.service.ManagementService.GetLogs:input_type -> api.proto.endpoints.GetLogsRequest
	27, // 27: api.proto.service.ManagementService.TuneDatabase:input_type -> api.proto.endpoints.TuneDatabaseRequest
	28, // 28: api.proto.service.ManagementService.ApplyTuning:input_type -> api.proto.endpoints.ApplyTuningRequest
	29, // 29: api.proto.service.ManagementService.GetAgentInfo:input_type -> api.proto.endpoints.GetAgentInfoRequest
	30, // 30: api.proto.service.ManagementService.GetAvailableVersions:input_type -> api.proto.endpoints.GetAvailableVersionsRequest
	31, // 31: api.proto.service.ManagementService.Login:input_type -> api.proto.endpoints.LoginRequest
	32, // 32: api.proto.service.ManagementService.CreateUser:input_type -> api.proto.endpoints.CreateUserRequest
	33, // 33: api.proto.service.ManagementService.GetServerInfo:input_type -> api.proto.endpoints.GetServerInfoRequest
	34, // 34: api.proto.service.ManagementService.GetPostgresInsights:input_type -> api.proto.endpoints.GetBackendPostgresInsightsRequest
	35, // 35: api.proto.service.ManagementService.RestartBackendService:input_type -> api.proto.endpoints.RestartBackendServiceRequest
	36, // 36: api.proto.service.ManagementService.ShutdownBackend:input_type -> api.proto.endpoints.ShutdownBackendRequest
	37, // 37: api.proto.service.ManagementService.ListProjects:output_type -> api.proto.endpoints.ListProjectsResponse
	38, // 38: api.proto.service.ManagementService.CreateProject:output_type -> api.proto.endpoints.CreateProjectResponse
	39, // 39: api.proto.service.ManagementService.DeleteProject:output_type -> api.proto.endpoints.DeleteProjectResponse
	40, // 40: api.proto.service.ManagementService.AddProxy:output_type -> api.proto.endpoints.AddProxyResponse
	41, // 41: api.proto.service.ManagementService.RemoveProxy:output_type -> api.proto.endpoints.RemoveProxyResponse
	42, // 42: api.proto.service.ManagementService.UpdateProxy:output_type -> api.proto.endpoints.UpdateProxyResponse
	43, // 43: api.proto.service.ManagementService.GetStatus:output_type -> api.proto.endpoints.GetStatusResponse
	43, // 44: api.proto.service.ManagementService.StreamStatus:output_type -> api.proto.endpoints.GetStatusResponse
	44, // 45: api.proto.service.ManagementService.AddBackend:output_type -> api.proto.endpoints.AddBackendResponse
	45, // 46: api.proto.service.ManagementService.RemoveBackend:output_type -> api.proto.endpoints.RemoveBackendResponse
	46, // 47: api.proto.service.ManagementService.UpdateBackend:output_type -> api.proto.endpoints.UpdateBackendResponse
	47, // 48: api.proto.service.ManagementService.ProvisionReplica:output_type -> api.proto.endpoints.ProvisionProgress
	48, // 49: api.proto.service.ManagementService.ValidateBackend:output_type -> api.proto.endpoints.ValidateBackendResponse
	49, // 50: api.proto.service.ManagementService.StreamLogs:output_type -> api.proto.domain.LogEntry
	50, // 51: api.proto.service.ManagementService.InitializeNode:output_type -> api.proto.endpoints.InitializeNodeProgress
	51, // 52: api.proto.service.ManagementService.InstallNode:output_type -> api.proto.endpoints.InstallNodeProgress
	52, // 53: api.proto.service.ManagementService.BackupBackend:output_type -> api.proto.endpoints.BackupBackendProgress
	53, // 54: api.proto.service.ManagementService.RestoreBackend:output_type -> api.proto.endpoints.RestoreBackendProgress
	54, // 55: api.proto.service.ManagementService.PromoteBackend:output_type -> api.proto.endpoints.PromoteBackendResponse
	55, // 56: api.proto.service.ManagementService.GetMetricsHistory:output_type -> api.proto.endpoints.GetMetricsHistoryResponse
	56, // 57: api.proto.service.ManagementService.GetTopQueriesHistory:output_type -> api.proto.endpoints.GetTopQueriesHistoryResponse
	57, // 58: api.proto.service.ManagementService.SetClusterConfig:output_type -> api.proto.endpoints.SetClusterConfigResponse
	58, // 59: api.proto.service.ManagementService.GetClusterConfig:output_type -> api.proto.endpoints.GetClusterConfigResponse
	59, // 60: api.proto.service.ManagementService.DiscoverCluster:output_type -> api.proto.endpoints.DiscoverClusterResponse
	60, // 61: api.proto.service.ManagementService.VacuumBackend:output_type -> api.proto.endpoints.VacuumBackendProgress
	61, // 62: api.proto.service.ManagementService.ExplainQuery:output_type -> api.proto.endpoints.ExplainQueryResponse
	62, // 63: api.proto.service.ManagementService.GetLogs:output_type -> api.proto.endpoints.GetLogsResponse
	63, // 64: api.proto.service.ManagementService.TuneDatabase:output_type -> api.proto.endpoints.TuneDatabaseResponse
	64, // 65: api.proto.service.ManagementService.ApplyTuning:output_type -> api.proto.endpoints.ApplyTuningResponse
	65, // 66: api.proto.service.ManagementService.GetAgentInfo:output_type -> api.proto.endpoints.GetAgentInfoResponse
	66, // 67: api.proto.service.ManagementService.GetAvailableVersions:output_type -> api.proto.endpoints.GetAvailableVersionsResponse
	67, // 68: api.proto.service.ManagementService.Login:output_type -> api.proto.endpoints.LoginResponse
	68, // 69: api.proto.service.ManagementService.CreateUser:output_type -> api.proto.endpoints.CreateUserResponse
	69, // 70: api.proto.service.ManagementService.GetServerInfo:output_type -> api.proto.endpoints.GetServerInfoResponse
	70, // 71: api.proto.service.ManagementService.GetPostgresInsights:output_type -> api.proto.endpoints.GetBackendPostgresInsightsResponse
	71, // 72: api.proto.service.ManagementService.RestartBackendService:output_type -> api.proto.endpoints.RestartBackendServiceResponse
	72, // 73: api.proto.service.ManagementService.ShutdownBackend:output_type -> api.proto.endpoints.ShutdownBackendResponse
	37, // [37:74] is the sub-list for method output_type
	0,  // [0:37] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_service_management_proto_init() }
func file_api_proto_service_management_proto_init() {
	if File_api_proto_service_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_service_management_proto_rawDesc), len(file_api_proto_service_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_service_management_proto_goTypes,
		DependencyIndexes: file_api_proto_service_management_proto_depIdxs,
	}.Build()
	File_api_proto_service_management_proto = out.File
	file_api_proto_service_management_proto_goTypes = nil
	file_api_proto_service_management_proto_depIdxs = nil
}
