// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: api/proto/service/management.proto

package service

import (
	context "context"
	domain "github.com/gsoultan/pontus/api/proto/domain"
	endpoints "github.com/gsoultan/pontus/api/proto/endpoints"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagementService_ListProjects_FullMethodName          = "/api.proto.service.ManagementService/ListProjects"
	ManagementService_CreateProject_FullMethodName         = "/api.proto.service.ManagementService/CreateProject"
	ManagementService_DeleteProject_FullMethodName         = "/api.proto.service.ManagementService/DeleteProject"
	ManagementService_AddProxy_FullMethodName              = "/api.proto.service.ManagementService/AddProxy"
	ManagementService_RemoveProxy_FullMethodName           = "/api.proto.service.ManagementService/RemoveProxy"
	ManagementService_UpdateProxy_FullMethodName           = "/api.proto.service.ManagementService/UpdateProxy"
	ManagementService_GetStatus_FullMethodName             = "/api.proto.service.ManagementService/GetStatus"
	ManagementService_StreamStatus_FullMethodName          = "/api.proto.service.ManagementService/StreamStatus"
	ManagementService_AddBackend_FullMethodName            = "/api.proto.service.ManagementService/AddBackend"
	ManagementService_RemoveBackend_FullMethodName         = "/api.proto.service.ManagementService/RemoveBackend"
	ManagementService_UpdateBackend_FullMethodName         = "/api.proto.service.ManagementService/UpdateBackend"
	ManagementService_ProvisionReplica_FullMethodName      = "/api.proto.service.ManagementService/ProvisionReplica"
	ManagementService_ValidateBackend_FullMethodName       = "/api.proto.service.ManagementService/ValidateBackend"
	ManagementService_StreamLogs_FullMethodName            = "/api.proto.service.ManagementService/StreamLogs"
	ManagementService_InitializeNode_FullMethodName        = "/api.proto.service.ManagementService/InitializeNode"
	ManagementService_InstallNode_FullMethodName           = "/api.proto.service.ManagementService/InstallNode"
	ManagementService_BackupBackend_FullMethodName         = "/api.proto.service.ManagementService/BackupBackend"
	ManagementService_RestoreBackend_FullMethodName        = "/api.proto.service.ManagementService/RestoreBackend"
	ManagementService_PromoteBackend_FullMethodName        = "/api.proto.service.ManagementService/PromoteBackend"
	ManagementService_GetMetricsHistory_FullMethodName     = "/api.proto.service.ManagementService/GetMetricsHistory"
	ManagementService_GetTopQueriesHistory_FullMethodName  = "/api.proto.service.ManagementService/GetTopQueriesHistory"
	ManagementService_SetClusterConfig_FullMethodName      = "/api.proto.service.ManagementService/SetClusterConfig"
	ManagementService_GetClusterConfig_FullMethodName      = "/api.proto.service.ManagementService/GetClusterConfig"
	ManagementService_DiscoverCluster_FullMethodName       = "/api.proto.service.ManagementService/DiscoverCluster"
	ManagementService_VacuumBackend_FullMethodName         = "/api.proto.service.ManagementService/VacuumBackend"
	ManagementService_ExplainQuery_FullMethodName          = "/api.proto.service.ManagementService/ExplainQuery"
	ManagementService_GetLogs_FullMethodName               = "/api.proto.service.ManagementService/GetLogs"
	ManagementService_TuneDatabase_FullMethodName          = "/api.proto.service.ManagementService/TuneDatabase"
	ManagementService_ApplyTuning_FullMethodName           = "/api.proto.service.ManagementService/ApplyTuning"
	ManagementService_GetAgentInfo_FullMethodName          = "/api.proto.service.ManagementService/GetAgentInfo"
	ManagementService_GetAvailableVersions_FullMethodName  = "/api.proto.service.ManagementService/GetAvailableVersions"
	ManagementService_Login_FullMethodName                 = "/api.proto.service.ManagementService/Login"
	ManagementService_CreateUser_FullMethodName            = "/api.proto.service.ManagementService/CreateUser"
	ManagementService_GetServerInfo_FullMethodName         = "/api.proto.service.ManagementService/GetServerInfo"
	ManagementService_GetPostgresInsights_FullMethodName   = "/api.proto.service.ManagementService/GetPostgresInsights"
	ManagementService_RestartBackendService_FullMethodName = "/api.proto.service.ManagementService/RestartBackendService"
	ManagementService_ShutdownBackend_FullMethodName       = "/api.proto.service.ManagementService/ShutdownBackend"
)

// ManagementServiceClient is the client API for ManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ManagementService defines the administrative API for Pontus.
type ManagementServiceClient interface {
	// Projects management
	ListProjects(ctx context.Context, in *endpoints.ListProjectsRequest, opts ...grpc.CallOption) (*endpoints.ListProjectsResponse, error)
	CreateProject(ctx context.Context, in *endpoints.CreateProjectRequest, opts ...grpc.CallOption) (*endpoints.CreateProjectResponse, error)
	DeleteProject(ctx context.Context, in *endpoints.DeleteProjectRequest, opts ...grpc.CallOption) (*endpoints.DeleteProjectResponse, error)
	// Proxies management
	AddProxy(ctx context.Context, in *endpoints.AddProxyRequest, opts ...grpc.CallOption) (*endpoints.AddProxyResponse, error)
	RemoveProxy(ctx context.Context, in *endpoints.RemoveProxyRequest, opts ...grpc.CallOption) (*endpoints.RemoveProxyResponse, error)
	UpdateProxy(ctx context.Context, in *endpoints.UpdateProxyRequest, opts ...grpc.CallOption) (*endpoints.UpdateProxyResponse, error)
	// GetStatus returns the current status of all backends and global metrics.
	GetStatus(ctx context.Context, in *endpoints.GetStatusRequest, opts ...grpc.CallOption) (*endpoints.GetStatusResponse, error)
	// StreamStatus pushes status updates for as long as the client is connected.
	//
	// Replaces polling GetStatus on a timer. The dashboard re-fetched the entire
	// payload — every backend, twenty top queries with full SQL text, topology,
	// system metrics — on a fixed interval whether anything had changed or not,
	// per connected dashboard. Read-only, same as GetStatus.
	StreamStatus(ctx context.Context, in *endpoints.StreamStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.GetStatusResponse], error)
	// AddBackend adds a new backend to the pool.
	AddBackend(ctx context.Context, in *endpoints.AddBackendRequest, opts ...grpc.CallOption) (*endpoints.AddBackendResponse, error)
	// RemoveBackend removes a backend from the pool.
	RemoveBackend(ctx context.Context, in *endpoints.RemoveBackendRequest, opts ...grpc.CallOption) (*endpoints.RemoveBackendResponse, error)
	// UpdateBackend updates an existing backend configuration.
	UpdateBackend(ctx context.Context, in *endpoints.UpdateBackendRequest, opts ...grpc.CallOption) (*endpoints.UpdateBackendResponse, error)
	// ProvisionReplica provisions a new replica from a source.
	ProvisionReplica(ctx context.Context, in *endpoints.ProvisionReplicaRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.ProvisionProgress], error)
	// ValidateBackend checks if a backend is accessible.
	ValidateBackend(ctx context.Context, in *endpoints.ValidateBackendRequest, opts ...grpc.CallOption) (*endpoints.ValidateBackendResponse, error)
	// StreamLogs returns a real-time stream of logs.
	StreamLogs(ctx context.Context, in *endpoints.StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[domain.LogEntry], error)
	// InitializeNode initializes a database on a clean host via Agent.
	InitializeNode(ctx context.Context, in *endpoints.InitializeNodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.InitializeNodeProgress], error)
	// InstallNode installs the database software on a clean host via Agent.
	InstallNode(ctx context.Context, in *endpoints.InstallNodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.InstallNodeProgress], error)
	// BackupBackend triggers a database backup on a backend via Agent.
	BackupBackend(ctx context.Context, in *endpoints.BackupBackendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.BackupBackendProgress], error)
	// RestoreBackend triggers a database restore on a backend via Agent.
	RestoreBackend(ctx context.Context, in *endpoints.RestoreBackendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.RestoreBackendProgress], error)
	// PromoteBackend promotes a replica to primary.
	PromoteBackend(ctx context.Context, in *endpoints.PromoteBackendRequest, opts ...grpc.CallOption) (*endpoints.PromoteBackendResponse, error)
	// GetMetricsHistory returns historical metrics.
	GetMetricsHistory(ctx context.Context, in *endpoints.GetMetricsHistoryRequest, opts ...grpc.CallOption) (*endpoints.GetMetricsHistoryResponse, error)
	// GetTopQueriesHistory returns historical top queries.
	GetTopQueriesHistory(ctx context.Context, in *endpoints.GetTopQueriesHistoryRequest, opts ...grpc.CallOption) (*endpoints.GetTopQueriesHistoryResponse, error)
	// SetClusterConfig updates configuration across the cluster.
	SetClusterConfig(ctx context.Context, in *endpoints.SetClusterConfigRequest, opts ...grpc.CallOption) (*endpoints.SetClusterConfigResponse, error)
	// GetClusterConfig returns the current cluster configuration.
	GetClusterConfig(ctx context.Context, in *endpoints.GetClusterConfigRequest, opts ...grpc.CallOption) (*endpoints.GetClusterConfigResponse, error)
	// DiscoverCluster auto-discovers and adds all nodes in a cluster.
	DiscoverCluster(ctx context.Context, in *endpoints.DiscoverClusterRequest, opts ...grpc.CallOption) (*endpoints.DiscoverClusterResponse, error)
	// VacuumBackend triggers a VACUUM operation on a backend via Agent.
	VacuumBackend(ctx context.Context, in *endpoints.VacuumBackendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.VacuumBackendProgress], error)
	// ExplainQuery analyzes a SQL query.
	ExplainQuery(ctx context.Context, in *endpoints.ExplainQueryRequest, opts ...grpc.CallOption) (*endpoints.ExplainQueryResponse, error)
	// GetLogs returns historical logs with filtering and pagination.
	GetLogs(ctx context.Context, in *endpoints.GetLogsRequest, opts ...grpc.CallOption) (*endpoints.GetLogsResponse, error)
	// TuneDatabase provides tuning recommendations based on system resources.
	TuneDatabase(ctx context.Context, in *endpoints.TuneDatabaseRequest, opts ...grpc.CallOption) (*endpoints.TuneDatabaseResponse, error)
	// ApplyTuning applies a tuning suggestion to a backend.
	ApplyTuning(ctx context.Context, in *endpoints.ApplyTuningRequest, opts ...grpc.CallOption) (*endpoints.ApplyTuningResponse, error)
	// GetAgentInfo fetches system info from a Pontus Agent.
	GetAgentInfo(ctx context.Context, in *endpoints.GetAgentInfoRequest, opts ...grpc.CallOption) (*endpoints.GetAgentInfoResponse, error)
	// GetAvailableVersions returns all supported PostgreSQL versions.
	GetAvailableVersions(ctx context.Context, in *endpoints.GetAvailableVersionsRequest, opts ...grpc.CallOption) (*endpoints.GetAvailableVersionsResponse, error)
	// Login authenticates a user and returns a token.
	Login(ctx context.Context, in *endpoints.LoginRequest, opts ...grpc.CallOption) (*endpoints.LoginResponse, error)
	// CreateUser creates a new management user.
	CreateUser(ctx context.Context, in *endpoints.CreateUserRequest, opts ...grpc.CallOption) (*endpoints.CreateUserResponse, error)
	// GetServerInfo returns information about the Pontus server.
	GetServerInfo(ctx context.Context, in *endpoints.GetServerInfoRequest, opts ...grpc.CallOption) (*endpoints.GetServerInfoResponse, error)
	// GetPostgresInsights retrieves database-specific insights for a backend.
	GetPostgresInsights(ctx context.Context, in *endpoints.GetBackendPostgresInsightsRequest, opts ...grpc.CallOption) (*endpoints.GetBackendPostgresInsightsResponse, error)
	// RestartBackendService restarts the database service on a backend via Agent.
	RestartBackendService(ctx context.Context, in *endpoints.RestartBackendServiceRequest, opts ...grpc.CallOption) (*endpoints.RestartBackendServiceResponse, error)
	// ShutdownBackend shuts down the database on a backend via Agent.
	ShutdownBackend(ctx context.Context, in *endpoints.ShutdownBackendRequest, opts ...grpc.CallOption) (*endpoints.ShutdownBackendResponse, error)
}

type managementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagementServiceClient(cc grpc.ClientConnInterface) ManagementServiceClient {
	return &managementServiceClient{cc}
}

func (c *managementServiceClient) ListProjects(ctx context.Context, in *endpoints.ListProjectsRequest, opts ...grpc.CallOption) (*endpoints.ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.ListProjectsResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) CreateProject(ctx context.Context, in *endpoints.CreateProjectRequest, opts ...grpc.CallOption) (*endpoints.CreateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.CreateProjectResponse)
	err := c.cc.Invoke(ctx, ManagementService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) DeleteProject(ctx context.Context, in *endpoints.DeleteProjectRequest, opts ...grpc.CallOption) (*endpoints.DeleteProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.DeleteProjectResponse)
	err := c.cc.Invoke(ctx, ManagementService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) AddProxy(ctx context.Context, in *endpoints.AddProxyRequest, opts ...grpc.CallOption) (*endpoints.AddProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.AddProxyResponse)
	err := c.cc.Invoke(ctx, ManagementService_AddProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) RemoveProxy(ctx context.Context, in *endpoints.RemoveProxyRequest, opts ...grpc.CallOption) (*endpoints.RemoveProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.RemoveProxyResponse)
	err := c.cc.Invoke(ctx, ManagementService_RemoveProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) UpdateProxy(ctx context.Context, in *endpoints.UpdateProxyRequest, opts ...grpc.CallOption) (*endpoints.UpdateProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.UpdateProxyResponse)
	err := c.cc.Invoke(ctx, ManagementService_UpdateProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetStatus(ctx context.Context, in *endpoints.GetStatusRequest, opts ...grpc.CallOption) (*endpoints.GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetStatusResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) StreamStatus(ctx context.Context, in *endpoints.StreamStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.GetStatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[0], ManagementService_StreamStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.StreamStatusRequest, endpoints.GetStatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_StreamStatusClient = grpc.ServerStreamingClient[endpoints.GetStatusResponse]

func (c *managementServiceClient) AddBackend(ctx context.Context, in *endpoints.AddBackendRequest, opts ...grpc.CallOption) (*endpoints.AddBackendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.AddBackendResponse)
	err := c.cc.Invoke(ctx, ManagementService_AddBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) RemoveBackend(ctx context.Context, in *endpoints.RemoveBackendRequest, opts ...grpc.CallOption) (*endpoints.RemoveBackendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.RemoveBackendResponse)
	err := c.cc.Invoke(ctx, ManagementService_RemoveBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) UpdateBackend(ctx context.Context, in *endpoints.UpdateBackendRequest, opts ...grpc.CallOption) (*endpoints.UpdateBackendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.UpdateBackendResponse)
	err := c.cc.Invoke(ctx, ManagementService_UpdateBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ProvisionReplica(ctx context.Context, in *endpoints.ProvisionReplicaRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.ProvisionProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[1], ManagementService_ProvisionReplica_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.ProvisionReplicaRequest, endpoints.ProvisionProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_ProvisionReplicaClient = grpc.ServerStreamingClient[endpoints.ProvisionProgress]

func (c *managementServiceClient) ValidateBackend(ctx context.Context, in *endpoints.ValidateBackendRequest, opts ...grpc.CallOption) (*endpoints.ValidateBackendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.ValidateBackendResponse)
	err := c.cc.Invoke(ctx, ManagementService_ValidateBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) StreamLogs(ctx context.Context, in *endpoints.StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[domain.LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[2], ManagementService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.StreamLogsRequest, domain.LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_StreamLogsClient = grpc.ServerStreamingClient[domain.LogEntry]

func (c *managementServiceClient) InitializeNode(ctx context.Context, in *endpoints.InitializeNodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.InitializeNodeProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[3], ManagementService_InitializeNode_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.InitializeNodeRequest, endpoints.InitializeNodeProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_InitializeNodeClient = grpc.ServerStreamingClient[endpoints.InitializeNodeProgress]

func (c *managementServiceClient) InstallNode(ctx context.Context, in *endpoints.InstallNodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.InstallNodeProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[4], ManagementService_InstallNode_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.InstallNodeRequest, endpoints.InstallNodeProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_InstallNodeClient = grpc.ServerStreamingClient[endpoints.InstallNodeProgress]

func (c *managementServiceClient) BackupBackend(ctx context.Context, in *endpoints.BackupBackendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.BackupBackendProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[5], ManagementService_BackupBackend_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.BackupBackendRequest, endpoints.BackupBackendProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_BackupBackendClient = grpc.ServerStreamingClient[endpoints.BackupBackendProgress]

func (c *managementServiceClient) RestoreBackend(ctx context.Context, in *endpoints.RestoreBackendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.RestoreBackendProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[6], ManagementService_RestoreBackend_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.RestoreBackendRequest, endpoints.RestoreBackendProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_RestoreBackendClient = grpc.ServerStreamingClient[endpoints.RestoreBackendProgress]

func (c *managementServiceClient) PromoteBackend(ctx context.Context, in *endpoints.PromoteBackendRequest, opts ...grpc.CallOption) (*endpoints.PromoteBackendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.PromoteBackendResponse)
	err := c.cc.Invoke(ctx, ManagementService_PromoteBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetMetricsHistory(ctx context.Context, in *endpoints.GetMetricsHistoryRequest, opts ...grpc.CallOption) (*endpoints.GetMetricsHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetMetricsHistoryResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetMetricsHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetTopQueriesHistory(ctx context.Context, in *endpoints.GetTopQueriesHistoryRequest, opts ...grpc.CallOption) (*endpoints.GetTopQueriesHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetTopQueriesHistoryResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetTopQueriesHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) SetClusterConfig(ctx context.Context, in *endpoints.SetClusterConfigRequest, opts ...grpc.CallOption) (*endpoints.SetClusterConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.SetClusterConfigResponse)
	err := c.cc.Invoke(ctx, ManagementService_SetClusterConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetClusterConfig(ctx context.Context, in *endpoints.GetClusterConfigRequest, opts ...grpc.CallOption) (*endpoints.GetClusterConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetClusterConfigResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetClusterConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) DiscoverCluster(ctx context.Context, in *endpoints.DiscoverClusterRequest, opts ...grpc.CallOption) (*endpoints.DiscoverClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.DiscoverClusterResponse)
	err := c.cc.Invoke(ctx, ManagementService_DiscoverCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) VacuumBackend(ctx context.Context, in *endpoints.VacuumBackendRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[endpoints.VacuumBackendProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[7], ManagementService_VacuumBackend_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[endpoints.VacuumBackendRequest, endpoints.VacuumBackendProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_VacuumBackendClient = grpc.ServerStreamingClient[endpoints.VacuumBackendProgress]

func (c *managementServiceClient) ExplainQuery(ctx context.Context, in *endpoints.ExplainQueryRequest, opts ...grpc.CallOption) (*endpoints.ExplainQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.ExplainQueryResponse)
	err := c.cc.Invoke(ctx, ManagementService_ExplainQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetLogs(ctx context.Context, in *endpoints.GetLogsRequest, opts ...grpc.CallOption) (*endpoints.GetLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetLogsResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) TuneDatabase(ctx context.Context, in *endpoints.TuneDatabaseRequest, opts ...grpc.CallOption) (*endpoints.TuneDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.TuneDatabaseResponse)
	err := c.cc.Invoke(ctx, ManagementService_TuneDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ApplyTuning(ctx context.Context, in *endpoints.ApplyTuningRequest, opts ...grpc.CallOption) (*endpoints.ApplyTuningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.ApplyTuningResponse)
	err := c.cc.Invoke(ctx, ManagementService_ApplyTuning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetAgentInfo(ctx context.Context, in *endpoints.GetAgentInfoRequest, opts ...grpc.CallOption) (*endpoints.GetAgentInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetAgentInfoResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetAgentInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetAvailableVersions(ctx context.Context, in *endpoints.GetAvailableVersionsRequest, opts ...grpc.CallOption) (*endpoints.GetAvailableVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetAvailableVersionsResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetAvailableVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) Login(ctx context.Context, in *endpoints.LoginRequest, opts ...grpc.CallOption) (*endpoints.LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.LoginResponse)
	err := c.cc.Invoke(ctx, ManagementService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) CreateUser(ctx context.Context, in *endpoints.CreateUserRequest, opts ...grpc.CallOption) (*endpoints.CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.CreateUserResponse)
	err := c.cc.Invoke(ctx, ManagementService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetServerInfo(ctx context.Context, in *endpoints.GetServerInfoRequest, opts ...grpc.CallOption) (*endpoints.GetServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetServerInfoResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetPostgresInsights(ctx context.Context, in *endpoints.GetBackendPostgresInsightsRequest, opts ...grpc.CallOption) (*endpoints.GetBackendPostgresInsightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.GetBackendPostgresInsightsResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetPostgresInsights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) RestartBackendService(ctx context.Context, in *endpoints.RestartBackendServiceRequest, opts ...grpc.CallOption) (*endpoints.RestartBackendServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.RestartBackendServiceResponse)
	err := c.cc.Invoke(ctx, ManagementService_RestartBackendService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ShutdownBackend(ctx context.Context, in *endpoints.ShutdownBackendRequest, opts ...grpc.CallOption) (*endpoints.ShutdownBackendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(endpoints.ShutdownBackendResponse)
	err := c.cc.Invoke(ctx, ManagementService_ShutdownBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagementServiceServer is the server API for ManagementService service.
// All implementations must embed UnimplementedManagementServiceServer
// for forward compatibility.
//
// ManagementService defines the administrative API for Pontus.
type ManagementServiceServer interface {
	// Projects management
	ListProjects(context.Context, *endpoints.ListProjectsRequest) (*endpoints.ListProjectsResponse, error)
	CreateProject(context.Context, *endpoints.CreateProjectRequest) (*endpoints.CreateProjectResponse, error)
	DeleteProject(context.Context, *endpoints.DeleteProjectRequest) (*endpoints.DeleteProjectResponse, error)
	// Proxies management
	AddProxy(context.Context, *endpoints.AddProxyRequest) (*endpoints.AddProxyResponse, error)
	RemoveProxy(context.Context, *endpoints.RemoveProxyRequest) (*endpoints.RemoveProxyResponse, error)
	UpdateProxy(context.Context, *endpoints.UpdateProxyRequest) (*endpoints.UpdateProxyResponse, error)
	// GetStatus returns the current status of all backends and global metrics.
	GetStatus(context.Context, *endpoints.GetStatusRequest) (*endpoints.GetStatusResponse, error)
	// StreamStatus pushes status updates for as long as the client is connected.
	//
	// Replaces polling GetStatus on a timer. The dashboard re-fetched the entire
	// payload — every backend, twenty top queries with full SQL text, topology,
	// system metrics — on a fixed interval whether anything had changed or not,
	// per connected dashboard. Read-only, same as GetStatus.
	StreamStatus(*endpoints.StreamStatusRequest, grpc.ServerStreamingServer[endpoints.GetStatusResponse]) error
	// AddBackend adds a new backend to the pool.
	AddBackend(context.Context, *endpoints.AddBackendRequest) (*endpoints.AddBackendResponse, error)
	// RemoveBackend removes a backend from the pool.
	RemoveBackend(context.Context, *endpoints.RemoveBackendRequest) (*endpoints.RemoveBackendResponse, error)
	// UpdateBackend updates an existing backend configuration.
	UpdateBackend(context.Context, *endpoints.UpdateBackendRequest) (*endpoints.UpdateBackendResponse, error)
	// ProvisionReplica provisions a new replica from a source.
	ProvisionReplica(*endpoints.ProvisionReplicaRequest, grpc.ServerStreamingServer[endpoints.ProvisionProgress]) error
	// ValidateBackend checks if a backend is accessible.
	ValidateBackend(context.Context, *endpoints.ValidateBackendRequest) (*endpoints.ValidateBackendResponse, error)
	// StreamLogs returns a real-time stream of logs.
	StreamLogs(*endpoints.StreamLogsRequest, grpc.ServerStreamingServer[domain.LogEntry]) error
	// InitializeNode initializes a database on a clean host via Agent.
	InitializeNode(*endpoints.InitializeNodeRequest, grpc.ServerStreamingServer[endpoints.InitializeNodeProgress]) error
	// InstallNode installs the database software on a clean host via Agent.
	InstallNode(*endpoints.InstallNodeRequest, grpc.ServerStreamingServer[endpoints.InstallNodeProgress]) error
	// BackupBackend triggers a database backup on a backend via Agent.
	BackupBackend(*endpoints.BackupBackendRequest, grpc.ServerStreamingServer[endpoints.BackupBackendProgress]) error
	// RestoreBackend triggers a database restore on a backend via Agent.
	RestoreBackend(*endpoints.RestoreBackendRequest, grpc.ServerStreamingServer[endpoints.RestoreBackendProgress]) error
	// PromoteBackend promotes a replica to primary.
	PromoteBackend(context.Context, *endpoints.PromoteBackendRequest) (*endpoints.PromoteBackendResponse, error)
	// GetMetricsHistory returns historical metrics.
	GetMetricsHistory(context.Context, *endpoints.GetMetricsHistoryRequest) (*endpoints.GetMetricsHistoryResponse, error)
	// GetTopQueriesHistory returns historical top queries.
	GetTopQueriesHistory(context.Context, *endpoints.GetTopQueriesHistoryRequest) (*endpoints.GetTopQueriesHistoryResponse, error)
	// SetClusterConfig updates configuration across the cluster.
	SetClusterConfig(context.Context, *endpoints.SetClusterConfigRequest) (*endpoints.SetClusterConfigResponse, error)
	// GetClusterConfig returns the current cluster configuration.
	GetClusterConfig(context.Context, *endpoints.GetClusterConfigRequest) (*endpoints.GetClusterConfigResponse, error)
	// DiscoverCluster auto-discovers and adds all nodes in a cluster.
	DiscoverCluster(context.Context, *endpoints.DiscoverClusterRequest) (*endpoints.DiscoverClusterResponse, error)
	// VacuumBackend triggers a VACUUM operation on a backend via Agent.
	VacuumBackend(*endpoints.VacuumBackendRequest, grpc.ServerStreamingServer[endpoints.VacuumBackendProgress]) error
	// ExplainQuery analyzes a SQL query.
	ExplainQuery(context.Context, *endpoints.ExplainQueryRequest) (*endpoints.ExplainQueryResponse, error)
	// GetLogs returns historical logs with filtering and pagination.
	GetLogs(context.Context, *endpoints.GetLogsRequest) (*endpoints.GetLogsResponse, error)
	// TuneDatabase provides tuning recommendations based on system resources.
	TuneDatabase(context.Context, *endpoints.TuneDatabaseRequest) (*endpoints.TuneDatabaseResponse, error)
	// ApplyTuning applies a tuning suggestion to a backend.
	ApplyTuning(context.Context, *endpoints.ApplyTuningRequest) (*endpoints.ApplyTuningResponse, error)
	// GetAgentInfo fetches system info from a Pontus Agent.
	GetAgentInfo(context.Context, *endpoints.GetAgentInfoRequest) (*endpoints.GetAgentInfoResponse, error)
	// GetAvailableVersions returns all supported PostgreSQL versions.
	GetAvailableVersions(context.Context, *endpoints.GetAvailableVersionsRequest) (*endpoints.GetAvailableVersionsResponse, error)
	// Login authenticates a user and returns a token.
	Login(context.Context, *endpoints.LoginRequest) (*endpoints.LoginResponse, error)
	// CreateUser creates a new management user.
	CreateUser(context.Context, *endpoints.CreateUserRequest) (*endpoints.CreateUserResponse, error)
	// GetServerInfo returns information about the Pontus server.
	GetServerInfo(context.Context, *endpoints.GetServerInfoRequest) (*endpoints.GetServerInfoResponse, error)
	// GetPostgresInsights retrieves database-specific insights for a backend.
	GetPostgresInsights(context.Context, *endpoints.GetBackendPostgresInsightsRequest) (*endpoints.GetBackendPostgresInsightsResponse, error)
	// RestartBackendService restarts the database service on a backend via Agent.
	RestartBackendService(context.Context, *endpoints.RestartBackendServiceRequest) (*endpoints.RestartBackendServiceResponse, error)
	// ShutdownBackend shuts down the database on a backend via Agent.
	ShutdownBackend(context.Context, *endpoints.ShutdownBackendRequest) (*endpoints.ShutdownBackendResponse, error)
	mustEmbedUnimplementedManagementServiceServer()
}

// UnimplementedManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagementServiceServer struct{}

func (UnimplementedManagementServiceServer) ListProjects(context.Context, *endpoints.ListProjectsRequest) (*endpoints.ListProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedManagementServiceServer) CreateProject(context.Context, *endpoints.CreateProjectRequest) (*endpoints.CreateProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedManagementServiceServer) DeleteProject(context.Context, *endpoints.DeleteProjectRequest) (*endpoints.DeleteProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedManagementServiceServer) AddProxy(context.Context, *endpoints.AddProxyRequest) (*endpoints.AddProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddProxy not implemented")
}
func (UnimplementedManagementServiceServer) RemoveProxy(context.Context, *endpoints.RemoveProxyRequest) (*endpoints.RemoveProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveProxy not implemented")
}
func (UnimplementedManagementServiceServer) UpdateProxy(context.Context, *endpoints.UpdateProxyRequest) (*endpoints.UpdateProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProxy not implemented")
}
func (UnimplementedManagementServiceServer) GetStatus(context.Context, *endpoints.GetStatusRequest) (*endpoints.GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedManagementServiceServer) StreamStatus(*endpoints.StreamStatusRequest, grpc.ServerStreamingServer[endpoints.GetStatusResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamStatus not implemented")
}
func (UnimplementedManagementServiceServer) AddBackend(context.Context, *endpoints.AddBackendRequest) (*endpoints.AddBackendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBackend not implemented")
}
func (UnimplementedManagementServiceServer) RemoveBackend(context.Context, *endpoints.RemoveBackendRequest) (*endpoints.RemoveBackendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBackend not implemented")
}
func (UnimplementedManagementServiceServer) UpdateBackend(context.Context, *endpoints.UpdateBackendRequest) (*endpoints.UpdateBackendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBackend not implemented")
}
func (UnimplementedManagementServiceServer) ProvisionReplica(*endpoints.ProvisionReplicaRequest, grpc.ServerStreamingServer[endpoints.ProvisionProgress]) error {
	return status.Error(codes.Unimplemented, "method ProvisionReplica not implemented")
}
func (UnimplementedManagementServiceServer) ValidateBackend(context.Context, *endpoints.ValidateBackendRequest) (*endpoints.ValidateBackendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateBackend not implemented")
}
func (UnimplementedManagementServiceServer) StreamLogs(*endpoints.StreamLogsRequest, grpc.ServerStreamingServer[domain.LogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedManagementServiceServer) InitializeNode(*endpoints.InitializeNodeRequest, grpc.ServerStreamingServer[endpoints.InitializeNodeProgress]) error {
	return status.Error(codes.Unimplemented, "method InitializeNode not implemented")
}
func (UnimplementedManagementServiceServer) InstallNode(*endpoints.InstallNodeRequest, grpc.ServerStreamingServer[endpoints.InstallNodeProgress]) error {
	return status.Error(codes.Unimplemented, "method InstallNode not implemented")
}
func (UnimplementedManagementServiceServer) BackupBackend(*endpoints.BackupBackendRequest, grpc.ServerStreamingServer[endpoints.BackupBackendProgress]) error {
	return status.Error(codes.Unimplemented, "method BackupBackend not implemented")
}
func (UnimplementedManagementServiceServer) RestoreBackend(*endpoints.RestoreBackendRequest, grpc.ServerStreamingServer[endpoints.RestoreBackendProgress]) error {
	return status.Error(codes.Unimplemented, "method RestoreBackend not implemented")
}
func (UnimplementedManagementServiceServer) PromoteBackend(context.Context, *endpoints.PromoteBackendRequest) (*endpoints.PromoteBackendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromoteBackend not implemented")
}
func (UnimplementedManagementServiceServer) GetMetricsHistory(context.Context, *endpoints.GetMetricsHistoryRequest) (*endpoints.GetMetricsHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetricsHistory not implemented")
}
func (UnimplementedManagementServiceServer) GetTopQueriesHistory(context.Context, *endpoints.GetTopQueriesHistoryRequest) (*endpoints.GetTopQueriesHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopQueriesHistory not implemented")
}
func (UnimplementedManagementServiceServer) SetClusterConfig(context.Context, *endpoints.SetClusterConfigRequest) (*endpoints.SetClusterConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetClusterConfig not implemented")
}
func (UnimplementedManagementServiceServer) GetClusterConfig(context.Context, *endpoints.GetClusterConfigRequest) (*endpoints.GetClusterConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterConfig not implemented")
}
func (UnimplementedManagementServiceServer) DiscoverCluster(context.Context, *endpoints.DiscoverClusterRequest) (*endpoints.DiscoverClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverCluster not implemented")
}
func (UnimplementedManagementServiceServer) VacuumBackend(*endpoints.VacuumBackendRequest, grpc.ServerStreamingServer[endpoints.VacuumBackendProgress]) error {
	return status.Error(codes.Unimplemented, "method VacuumBackend not implemented")
}
func (UnimplementedManagementServiceServer) ExplainQuery(context.Context, *endpoints.ExplainQueryRequest) (*endpoints.ExplainQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainQuery not implemented")
}
func (UnimplementedManagementServiceServer) GetLogs(context.Context, *endpoints.GetLogsRequest) (*endpoints.GetLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedManagementServiceServer) TuneDatabase(context.Context, *endpoints.TuneDatabaseRequest) (*endpoints.TuneDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TuneDatabase not implemented")
}
func (UnimplementedManagementServiceServer) ApplyTuning(context.Context, *endpoints.ApplyTuningRequest) (*endpoints.ApplyTuningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyTuning not implemented")
}
func (UnimplementedManagementServiceServer) GetAgentInfo(context.Context, *endpoints.GetAgentInfoRequest) (*endpoints.GetAgentInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentInfo not implemented")
}
func (UnimplementedManagementServiceServer) GetAvailableVersions(context.Context, *endpoints.GetAvailableVersionsRequest) (*endpoints.GetAvailableVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableVersions not implemented")
}
func (UnimplementedManagementServiceServer) Login(context.Context, *endpoints.LoginRequest) (*endpoints.LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedManagementServiceServer) CreateUser(context.Context, *endpoints.CreateUserRequest) (*endpoints.CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedManagementServiceServer) GetServerInfo(context.Context, *endpoints.GetServerInfoRequest) (*endpoints.GetServerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedManagementServiceServer) GetPostgresInsights(context.Context, *endpoints.GetBackendPostgresInsightsRequest) (*endpoints.GetBackendPostgresInsightsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPostgresInsights not implemented")
}
func (UnimplementedManagementServiceServer) RestartBackendService(context.Context, *endpoints.RestartBackendServiceRequest) (*endpoints.RestartBackendServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartBackendService not implemented")
}
func (UnimplementedManagementServiceServer) ShutdownBackend(context.Context, *endpoints.ShutdownBackendRequest) (*endpoints.ShutdownBackendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShutdownBackend not implemented")
}
func (UnimplementedManagementServiceServer) mustEmbedUnimplementedManagementServiceServer() {}
func (UnimplementedManagementServiceServer) testEmbeddedByValue()                           {}

// UnsafeManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagementServiceServer will
// result in compilation errors.
type UnsafeManagementServiceServer interface {
	mustEmbedUnimplementedManagementServiceServer()
}

func RegisterManagementServiceServer(s grpc.ServiceRegistrar, srv ManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagementService_ServiceDesc, srv)
}

func _ManagementService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListProjects(ctx, req.(*endpoints.ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CreateProject(ctx, req.(*endpoints.CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).DeleteProject(ctx, req.(*endpoints.DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_AddProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.AddProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).AddProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_AddProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).AddProxy(ctx, req.(*endpoints.AddProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_RemoveProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.RemoveProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RemoveProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RemoveProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RemoveProxy(ctx, req.(*endpoints.RemoveProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_UpdateProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.UpdateProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).UpdateProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_UpdateProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).UpdateProxy(ctx, req.(*endpoints.UpdateProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetStatus(ctx, req.(*endpoints.GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_StreamStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.StreamStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).StreamStatus(m, &grpc.GenericServerStream[endpoints.StreamStatusRequest, endpoints.GetStatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_StreamStatusServer = grpc.ServerStreamingServer[endpoints.GetStatusResponse]

func _ManagementService_AddBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.AddBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).AddBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_AddBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).AddBackend(ctx, req.(*endpoints.AddBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_RemoveBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.RemoveBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RemoveBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RemoveBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RemoveBackend(ctx, req.(*endpoints.RemoveBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_UpdateBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.UpdateBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).UpdateBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_UpdateBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).UpdateBackend(ctx, req.(*endpoints.UpdateBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ProvisionReplica_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.ProvisionReplicaRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).ProvisionReplica(m, &grpc.GenericServerStream[endpoints.ProvisionReplicaRequest, endpoints.ProvisionProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_ProvisionReplicaServer = grpc.ServerStreamingServer[endpoints.ProvisionProgress]

func _ManagementService_ValidateBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.ValidateBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ValidateBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ValidateBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ValidateBackend(ctx, req.(*endpoints.ValidateBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).StreamLogs(m, &grpc.GenericServerStream[endpoints.StreamLogsRequest, domain.LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_StreamLogsServer = grpc.ServerStreamingServer[domain.LogEntry]

func _ManagementService_InitializeNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.InitializeNodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).InitializeNode(m, &grpc.GenericServerStream[endpoints.InitializeNodeRequest, endpoints.InitializeNodeProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_InitializeNodeServer = grpc.ServerStreamingServer[endpoints.InitializeNodeProgress]

func _ManagementService_InstallNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.InstallNodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).InstallNode(m, &grpc.GenericServerStream[endpoints.InstallNodeRequest, endpoints.InstallNodeProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_InstallNodeServer = grpc.ServerStreamingServer[endpoints.InstallNodeProgress]

func _ManagementService_BackupBackend_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.BackupBackendRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).BackupBackend(m, &grpc.GenericServerStream[endpoints.BackupBackendRequest, endpoints.BackupBackendProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_BackupBackendServer = grpc.ServerStreamingServer[endpoints.BackupBackendProgress]

func _ManagementService_RestoreBackend_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.RestoreBackendRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).RestoreBackend(m, &grpc.GenericServerStream[endpoints.RestoreBackendRequest, endpoints.RestoreBackendProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_RestoreBackendServer = grpc.ServerStreamingServer[endpoints.RestoreBackendProgress]

func _ManagementService_PromoteBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.PromoteBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).PromoteBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_PromoteBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).PromoteBackend(ctx, req.(*endpoints.PromoteBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetMetricsHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetMetricsHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetMetricsHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetMetricsHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetMetricsHistory(ctx, req.(*endpoints.GetMetricsHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetTopQueriesHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetTopQueriesHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetTopQueriesHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetTopQueriesHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetTopQueriesHistory(ctx, req.(*endpoints.GetTopQueriesHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_SetClusterConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.SetClusterConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).SetClusterConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_SetClusterConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).SetClusterConfig(ctx, req.(*endpoints.SetClusterConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetClusterConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetClusterConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetClusterConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetClusterConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetClusterConfig(ctx, req.(*endpoints.GetClusterConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_DiscoverCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.DiscoverClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).DiscoverCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_DiscoverCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).DiscoverCluster(ctx, req.(*endpoints.DiscoverClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_VacuumBackend_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(endpoints.VacuumBackendRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).VacuumBackend(m, &grpc.GenericServerStream[endpoints.VacuumBackendRequest, endpoints.VacuumBackendProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_VacuumBackendServer = grpc.ServerStreamingServer[endpoints.VacuumBackendProgress]

func _ManagementService_ExplainQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.ExplainQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ExplainQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ExplainQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ExplainQuery(ctx, req.(*endpoints.ExplainQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetLogs(ctx, req.(*endpoints.GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_TuneDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.TuneDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).TuneDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_TuneDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).TuneDatabase(ctx, req.(*endpoints.TuneDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ApplyTuning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.ApplyTuningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ApplyTuning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ApplyTuning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ApplyTuning(ctx, req.(*endpoints.ApplyTuningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetAgentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetAgentInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetAgentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetAgentInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetAgentInfo(ctx, req.(*endpoints.GetAgentInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetAvailableVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetAvailableVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetAvailableVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetAvailableVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetAvailableVersions(ctx, req.(*endpoints.GetAvailableVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).Login(ctx, req.(*endpoints.LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CreateUser(ctx, req.(*endpoints.CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetServerInfo(ctx, req.(*endpoints.GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetPostgresInsights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.GetBackendPostgresInsightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetPostgresInsights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetPostgresInsights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetPostgresInsights(ctx, req.(*endpoints.GetBackendPostgresInsightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_RestartBackendService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.RestartBackendServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RestartBackendService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RestartBackendService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RestartBackendService(ctx, req.(*endpoints.RestartBackendServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ShutdownBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(endpoints.ShutdownBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ShutdownBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ShutdownBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ShutdownBackend(ctx, req.(*endpoints.ShutdownBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagementService_ServiceDesc is the grpc.ServiceDesc for ManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.service.ManagementService",
	HandlerType: (*ManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProjects",
			Handler:    _ManagementService_ListProjects_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _ManagementService_CreateProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _ManagementService_DeleteProject_Handler,
		},
		{
			MethodName: "AddProxy",
			Handler:    _ManagementService_AddProxy_Handler,
		},
		{
			MethodName: "RemoveProxy",
			Handler:    _ManagementService_RemoveProxy_Handler,
		},
		{
			MethodName: "UpdateProxy",
			Handler:    _ManagementService_UpdateProxy_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _ManagementService_GetStatus_Handler,
		},
		{
			MethodName: "AddBackend",
			Handler:    _ManagementService_AddBackend_Handler,
		},
		{
			MethodName: "RemoveBackend",
			Handler:    _ManagementService_RemoveBackend_Handler,
		},
		{
			MethodName: "UpdateBackend",
			Handler:    _ManagementService_UpdateBackend_Handler,
		},
		{
			MethodName: "ValidateBackend",
			Handler:    _ManagementService_ValidateBackend_Handler,
		},
		{
			MethodName: "PromoteBackend",
			Handler:    _ManagementService_PromoteBackend_Handler,
		},
		{
			MethodName: "GetMetricsHistory",
			Handler:    _ManagementService_GetMetricsHistory_Handler,
		},
		{
			MethodName: "GetTopQueriesHistory",
			Handler:    _ManagementService_GetTopQueriesHistory_Handler,
		},
		{
			MethodName: "SetClusterConfig",
			Handler:    _ManagementService_SetClusterConfig_Handler,
		},
		{
			MethodName: "GetClusterConfig",
			Handler:    _ManagementService_GetClusterConfig_Handler,
		},
		{
			MethodName: "DiscoverCluster",
			Handler:    _ManagementService_DiscoverCluster_Handler,
		},
		{
			MethodName: "ExplainQuery",
			Handler:    _ManagementService_ExplainQuery_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _ManagementService_GetLogs_Handler,
		},
		{
			MethodName: "TuneDatabase",
			Handler:    _ManagementService_TuneDatabase_Handler,
		},
		{
			MethodName: "ApplyTuning",
			Handler:    _ManagementService_ApplyTuning_Handler,
		},
		{
			MethodName: "GetAgentInfo",
			Handler:    _ManagementService_GetAgentInfo_Handler,
		},
		{
			MethodName: "GetAvailableVersions",
			Handler:    _ManagementService_GetAvailableVersions_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ManagementService_Login_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _ManagementService_CreateUser_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _ManagementService_GetServerInfo_Handler,
		},
		{
			MethodName: "GetPostgresInsights",
			Handler:    _ManagementService_GetPostgresInsights_Handler,
		},
		{
			MethodName: "RestartBackendService",
			Handler:    _ManagementService_RestartBackendService_Handler,
		},
		{
			MethodName: "ShutdownBackend",
			Handler:    _ManagementService_ShutdownBackend_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStatus",
			Handler:       _ManagementService_StreamStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProvisionReplica",
			Handler:       _ManagementService_ProvisionReplica_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _ManagementService_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InitializeNode",
			Handler:       _ManagementService_InitializeNode_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InstallNode",
			Handler:       _ManagementService_InstallNode_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BackupBackend",
			Handler:       _ManagementService_BackupBackend_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RestoreBackend",
			Handler:       _ManagementService_RestoreBackend_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "VacuumBackend",
			Handler:       _ManagementService_VacuumBackend_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/service/management.proto",
}
