// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/proto/service/agent.proto

package serviceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	endpoints "github.com/gsoultan/pontus/api/proto/endpoints"
	service "github.com/gsoultan/pontus/api/proto/service"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "api.proto.service.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceGetSystemInfoProcedure is the fully-qualified name of the AgentService's
	// GetSystemInfo RPC.
	AgentServiceGetSystemInfoProcedure = "/api.proto.service.AgentService/GetSystemInfo"
	// AgentServiceUpdateConfigProcedure is the fully-qualified name of the AgentService's UpdateConfig
	// RPC.
	AgentServiceUpdateConfigProcedure = "/api.proto.service.AgentService/UpdateConfig"
	// AgentServiceExecuteCommandProcedure is the fully-qualified name of the AgentService's
	// ExecuteCommand RPC.
	AgentServiceExecuteCommandProcedure = "/api.proto.service.AgentService/ExecuteCommand"
	// AgentServiceRestartServiceProcedure is the fully-qualified name of the AgentService's
	// RestartService RPC.
	AgentServiceRestartServiceProcedure = "/api.proto.service.AgentService/RestartService"
	// AgentServiceStreamLogsProcedure is the fully-qualified name of the AgentService's StreamLogs RPC.
	AgentServiceStreamLogsProcedure = "/api.proto.service.AgentService/StreamLogs"
	// AgentServiceScheduleMaintenanceProcedure is the fully-qualified name of the AgentService's
	// ScheduleMaintenance RPC.
	AgentServiceScheduleMaintenanceProcedure = "/api.proto.service.AgentService/ScheduleMaintenance"
	// AgentServiceSetupReplicationProcedure is the fully-qualified name of the AgentService's
	// SetupReplication RPC.
	AgentServiceSetupReplicationProcedure = "/api.proto.service.AgentService/SetupReplication"
	// AgentServicePromoteNodeProcedure is the fully-qualified name of the AgentService's PromoteNode
	// RPC.
	AgentServicePromoteNodeProcedure = "/api.proto.service.AgentService/PromoteNode"
	// AgentServiceInitializeDatabaseProcedure is the fully-qualified name of the AgentService's
	// InitializeDatabase RPC.
	AgentServiceInitializeDatabaseProcedure = "/api.proto.service.AgentService/InitializeDatabase"
	// AgentServiceInstallDatabaseProcedure is the fully-qualified name of the AgentService's
	// InstallDatabase RPC.
	AgentServiceInstallDatabaseProcedure = "/api.proto.service.AgentService/InstallDatabase"
	// AgentServiceBackupDatabaseProcedure is the fully-qualified name of the AgentService's
	// BackupDatabase RPC.
	AgentServiceBackupDatabaseProcedure = "/api.proto.service.AgentService/BackupDatabase"
	// AgentServiceRestoreDatabaseProcedure is the fully-qualified name of the AgentService's
	// RestoreDatabase RPC.
	AgentServiceRestoreDatabaseProcedure = "/api.proto.service.AgentService/RestoreDatabase"
	// AgentServiceGetPostgresInsightsProcedure is the fully-qualified name of the AgentService's
	// GetPostgresInsights RPC.
	AgentServiceGetPostgresInsightsProcedure = "/api.proto.service.AgentService/GetPostgresInsights"
	// AgentServiceShutdownDatabaseProcedure is the fully-qualified name of the AgentService's
	// ShutdownDatabase RPC.
	AgentServiceShutdownDatabaseProcedure = "/api.proto.service.AgentService/ShutdownDatabase"
	// AgentServiceRemoveDatabaseProcedure is the fully-qualified name of the AgentService's
	// RemoveDatabase RPC.
	AgentServiceRemoveDatabaseProcedure = "/api.proto.service.AgentService/RemoveDatabase"
	// AgentServiceVacuumDatabaseProcedure is the fully-qualified name of the AgentService's
	// VacuumDatabase RPC.
	AgentServiceVacuumDatabaseProcedure = "/api.proto.service.AgentService/VacuumDatabase"
)

// AgentServiceClient is a client for the api.proto.service.AgentService service.
type AgentServiceClient interface {
	// GetSystemInfo returns basic information about the host system.
	GetSystemInfo(context.Context, *connect.Request[endpoints.GetSystemInfoRequest]) (*connect.Response[endpoints.GetSystemInfoResponse], error)
	// UpdateConfig updates a configuration file on the host.
	UpdateConfig(context.Context, *connect.Request[endpoints.UpdateConfigRequest]) (*connect.Response[endpoints.UpdateConfigResponse], error)
	// ExecuteCommand executes a shell command on the host and streams the output.
	ExecuteCommand(context.Context, *connect.Request[endpoints.ExecuteCommandRequest]) (*connect.ServerStreamForClient[endpoints.ExecuteCommandResponse], error)
	// RestartService restarts a system service (e.g., postgresql).
	RestartService(context.Context, *connect.Request[endpoints.RestartServiceRequest]) (*connect.Response[endpoints.RestartServiceResponse], error)
	// StreamLogs streams the logs of a database instance.
	StreamLogs(context.Context, *connect.Request[endpoints.LogStreamRequest]) (*connect.ServerStreamForClient[endpoints.LogStreamResponse], error)
	// ScheduleMaintenance schedules a maintenance task.
	ScheduleMaintenance(context.Context, *connect.Request[endpoints.ScheduleMaintenanceRequest]) (*connect.Response[endpoints.ScheduleMaintenanceResponse], error)
	// SetupReplication configures the host as a replica of another host.
	SetupReplication(context.Context, *connect.Request[endpoints.SetupReplicationRequest]) (*connect.ServerStreamForClient[endpoints.ReplicationProgress], error)
	// PromoteNode promotes a replica to a primary.
	PromoteNode(context.Context, *connect.Request[endpoints.PromoteNodeRequest]) (*connect.Response[endpoints.PromoteNodeResponse], error)
	// InitializeDatabase initializes a new database instance.
	InitializeDatabase(context.Context, *connect.Request[endpoints.InitializeDatabaseRequest]) (*connect.ServerStreamForClient[endpoints.InitializeProgress], error)
	// InstallDatabase installs the database software.
	InstallDatabase(context.Context, *connect.Request[endpoints.InstallDatabaseRequest]) (*connect.ServerStreamForClient[endpoints.InstallProgress], error)
	// BackupDatabase creates a backup of the database.
	BackupDatabase(context.Context, *connect.Request[endpoints.BackupDatabaseRequest]) (*connect.ServerStreamForClient[endpoints.BackupProgress], error)
	// RestoreDatabase restores the database from a backup.
	RestoreDatabase(context.Context, *connect.Request[endpoints.RestoreDatabaseRequest]) (*connect.ServerStreamForClient[endpoints.RestoreProgress], error)
	// GetPostgresInsights returns database-specific insights for Postgres.
	GetPostgresInsights(context.Context, *connect.Request[endpoints.GetPostgresInsightsRequest]) (*connect.Response[endpoints.GetPostgresInsightsResponse], error)
	// ShutdownDatabase stops the database service.
	ShutdownDatabase(context.Context, *connect.Request[endpoints.ShutdownDatabaseRequest]) (*connect.Response[endpoints.ShutdownDatabaseResponse], error)
	// RemoveDatabase stops the database and removes its data directory.
	RemoveDatabase(context.Context, *connect.Request[endpoints.RemoveDatabaseRequest]) (*connect.Response[endpoints.RemoveDatabaseResponse], error)
	// VacuumDatabase performs a VACUUM operation on the database.
	VacuumDatabase(context.Context, *connect.Request[endpoints.VacuumDatabaseRequest]) (*connect.ServerStreamForClient[endpoints.VacuumProgress], error)
}

// NewAgentServiceClient constructs a client for the api.proto.service.AgentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := service.File_api_proto_service_agent_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		getSystemInfo: connect.NewClient[endpoints.GetSystemInfoRequest, endpoints.GetSystemInfoResponse](
			httpClient,
			baseURL+AgentServiceGetSystemInfoProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetSystemInfo")),
			connect.WithClientOptions(opts...),
		),
		updateConfig: connect.NewClient[endpoints.UpdateConfigRequest, endpoints.UpdateConfigResponse](
			httpClient,
			baseURL+AgentServiceUpdateConfigProcedure,
			connect.WithSchema(agentServiceMethods.ByName("UpdateConfig")),
			connect.WithClientOptions(opts...),
		),
		executeCommand: connect.NewClient[endpoints.ExecuteCommandRequest, endpoints.ExecuteCommandResponse](
			httpClient,
			baseURL+AgentServiceExecuteCommandProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ExecuteCommand")),
			connect.WithClientOptions(opts...),
		),
		restartService: connect.NewClient[endpoints.RestartServiceRequest, endpoints.RestartServiceResponse](
			httpClient,
			baseURL+AgentServiceRestartServiceProcedure,
			connect.WithSchema(agentServiceMethods.ByName("RestartService")),
			connect.WithClientOptions(opts...),
		),
		streamLogs: connect.NewClient[endpoints.LogStreamRequest, endpoints.LogStreamResponse](
			httpClient,
			baseURL+AgentServiceStreamLogsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("StreamLogs")),
			connect.WithClientOptions(opts...),
		),
		scheduleMaintenance: connect.NewClient[endpoints.ScheduleMaintenanceRequest, endpoints.ScheduleMaintenanceResponse](
			httpClient,
			baseURL+AgentServiceScheduleMaintenanceProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ScheduleMaintenance")),
			connect.WithClientOptions(opts...),
		),
		setupReplication: connect.NewClient[endpoints.SetupReplicationRequest, endpoints.ReplicationProgress](
			httpClient,
			baseURL+AgentServiceSetupReplicationProcedure,
			connect.WithSchema(agentServiceMethods.ByName("SetupReplication")),
			connect.WithClientOptions(opts...),
		),
		promoteNode: connect.NewClient[endpoints.PromoteNodeRequest, endpoints.PromoteNodeResponse](
			httpClient,
			baseURL+AgentServicePromoteNodeProcedure,
			connect.WithSchema(agentServiceMethods.ByName("PromoteNode")),
			connect.WithClientOptions(opts...),
		),
		initializeDatabase: connect.NewClient[endpoints.InitializeDatabaseRequest, endpoints.InitializeProgress](
			httpClient,
			baseURL+AgentServiceInitializeDatabaseProcedure,
			connect.WithSchema(agentServiceMethods.ByName("InitializeDatabase")),
			connect.WithClientOptions(opts...),
		),
		installDatabase: connect.NewClient[endpoints.InstallDatabaseRequest, endpoints.InstallProgress](
			httpClient,
			baseURL+AgentServiceInstallDatabaseProcedure,
			connect.WithSchema(agentServiceMethods.ByName("InstallDatabase")),
			connect.WithClientOptions(opts...),
		),
		backupDatabase: connect.NewClient[endpoints.BackupDatabaseRequest, endpoints.BackupProgress](
			httpClient,
			baseURL+AgentServiceBackupDatabaseProcedure,
			connect.WithSchema(agentServiceMethods.ByName("BackupDatabase")),
			connect.WithClientOptions(opts...),
		),
		restoreDatabase: connect.NewClient[endpoints.RestoreDatabaseRequest, endpoints.RestoreProgress](
			httpClient,
			baseURL+AgentServiceRestoreDatabaseProcedure,
			connect.WithSchema(agentServiceMethods.ByName("RestoreDatabase")),
			connect.WithClientOptions(opts...),
		),
		getPostgresInsights: connect.NewClient[endpoints.GetPostgresInsightsRequest, endpoints.GetPostgresInsightsResponse](
			httpClient,
			baseURL+AgentServiceGetPostgresInsightsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetPostgresInsights")),
			connect.WithClientOptions(opts...),
		),
		shutdownDatabase: connect.NewClient[endpoints.ShutdownDatabaseRequest, endpoints.ShutdownDatabaseResponse](
			httpClient,
			baseURL+AgentServiceShutdownDatabaseProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ShutdownDatabase")),
			connect.WithClientOptions(opts...),
		),
		removeDatabase: connect.NewClient[endpoints.RemoveDatabaseRequest, endpoints.RemoveDatabaseResponse](
			httpClient,
			baseURL+AgentServiceRemoveDatabaseProcedure,
			connect.WithSchema(agentServiceMethods.ByName("RemoveDatabase")),
			connect.WithClientOptions(opts...),
		),
		vacuumDatabase: connect.NewClient[endpoints.VacuumDatabaseRequest, endpoints.VacuumProgress](
			httpClient,
			baseURL+AgentServiceVacuumDatabaseProcedure,
			connect.WithSchema(agentServiceMethods.ByName("VacuumDatabase")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	getSystemInfo       *connect.Client[endpoints.GetSystemInfoRequest, endpoints.GetSystemInfoResponse]
	updateConfig        *connect.Client[endpoints.UpdateConfigRequest, endpoints.UpdateConfigResponse]
	executeCommand      *connect.Client[endpoints.ExecuteCommandRequest, endpoints.ExecuteCommandResponse]
	restartService      *connect.Client[endpoints.RestartServiceRequest, endpoints.RestartServiceResponse]
	streamLogs          *connect.Client[endpoints.LogStreamRequest, endpoints.LogStreamResponse]
	scheduleMaintenance *connect.Client[endpoints.ScheduleMaintenanceRequest, endpoints.ScheduleMaintenanceResponse]
	setupReplication    *connect.Client[endpoints.SetupReplicationRequest, endpoints.ReplicationProgress]
	promoteNode         *connect.Client[endpoints.PromoteNodeRequest, endpoints.PromoteNodeResponse]
	initializeDatabase  *connect.Client[endpoints.InitializeDatabaseRequest, endpoints.InitializeProgress]
	installDatabase     *connect.Client[endpoints.InstallDatabaseRequest, endpoints.InstallProgress]
	backupDatabase      *connect.Client[endpoints.BackupDatabaseRequest, endpoints.BackupProgress]
	restoreDatabase     *connect.Client[endpoints.RestoreDatabaseRequest, endpoints.RestoreProgress]
	getPostgresInsights *connect.Client[endpoints.GetPostgresInsightsRequest, endpoints.GetPostgresInsightsResponse]
	shutdownDatabase    *connect.Client[endpoints.ShutdownDatabaseRequest, endpoints.ShutdownDatabaseResponse]
	removeDatabase      *connect.Client[endpoints.RemoveDatabaseRequest, endpoints.RemoveDatabaseResponse]
	vacuumDatabase      *connect.Client[endpoints.VacuumDatabaseRequest, endpoints.VacuumProgress]
}

// GetSystemInfo calls api.proto.service.AgentService.GetSystemInfo.
func (c *agentServiceClient) GetSystemInfo(ctx context.Context, req *connect.Request[endpoints.GetSystemInfoRequest]) (*connect.Response[endpoints.GetSystemInfoResponse], error) {
	return c.getSystemInfo.CallUnary(ctx, req)
}

// UpdateConfig calls api.proto.service.AgentService.UpdateConfig.
func (c *agentServiceClient) UpdateConfig(ctx context.Context, req *connect.Request[endpoints.UpdateConfigRequest]) (*connect.Response[endpoints.UpdateConfigResponse], error) {
	return c.updateConfig.CallUnary(ctx, req)
}

// ExecuteCommand calls api.proto.service.AgentService.ExecuteCommand.
func (c *agentServiceClient) ExecuteCommand(ctx context.Context, req *connect.Request[endpoints.ExecuteCommandRequest]) (*connect.ServerStreamForClient[endpoints.ExecuteCommandResponse], error) {
	return c.executeCommand.CallServerStream(ctx, req)
}

// RestartService calls api.proto.service.AgentService.RestartService.
func (c *agentServiceClient) RestartService(ctx context.Context, req *connect.Request[endpoints.RestartServiceRequest]) (*connect.Response[endpoints.RestartServiceResponse], error) {
	return c.restartService.CallUnary(ctx, req)
}

// StreamLogs calls api.proto.service.AgentService.StreamLogs.
func (c *agentServiceClient) StreamLogs(ctx context.Context, req *connect.Request[endpoints.LogStreamRequest]) (*connect.ServerStreamForClient[endpoints.LogStreamResponse], error) {
	return c.streamLogs.CallServerStream(ctx, req)
}

// ScheduleMaintenance calls api.proto.service.AgentService.ScheduleMaintenance.
func (c *agentServiceClient) ScheduleMaintenance(ctx context.Context, req *connect.Request[endpoints.ScheduleMaintenanceRequest]) (*connect.Response[endpoints.ScheduleMaintenanceResponse], error) {
	return c.scheduleMaintenance.CallUnary(ctx, req)
}

// SetupReplication calls api.proto.service.AgentService.SetupReplication.
func (c *agentServiceClient) SetupReplication(ctx context.Context, req *connect.Request[endpoints.SetupReplicationRequest]) (*connect.ServerStreamForClient[endpoints.ReplicationProgress], error) {
	return c.setupReplication.CallServerStream(ctx, req)
}

// PromoteNode calls api.proto.service.AgentService.PromoteNode.
func (c *agentServiceClient) PromoteNode(ctx context.Context, req *connect.Request[endpoints.PromoteNodeRequest]) (*connect.Response[endpoints.PromoteNodeResponse], error) {
	return c.promoteNode.CallUnary(ctx, req)
}

// InitializeDatabase calls api.proto.service.AgentService.InitializeDatabase.
func (c *agentServiceClient) InitializeDatabase(ctx context.Context, req *connect.Request[endpoints.InitializeDatabaseRequest]) (*connect.ServerStreamForClient[endpoints.InitializeProgress], error) {
	return c.initializeDatabase.CallServerStream(ctx, req)
}

// InstallDatabase calls api.proto.service.AgentService.InstallDatabase.
func (c *agentServiceClient) InstallDatabase(ctx context.Context, req *connect.Request[endpoints.InstallDatabaseRequest]) (*connect.ServerStreamForClient[endpoints.InstallProgress], error) {
	return c.installDatabase.CallServerStream(ctx, req)
}

// BackupDatabase calls api.proto.service.AgentService.BackupDatabase.
func (c *agentServiceClient) BackupDatabase(ctx context.Context, req *connect.Request[endpoints.BackupDatabaseRequest]) (*connect.ServerStreamForClient[endpoints.BackupProgress], error) {
	return c.backupDatabase.CallServerStream(ctx, req)
}

// RestoreDatabase calls api.proto.service.AgentService.RestoreDatabase.
func (c *agentServiceClient) RestoreDatabase(ctx context.Context, req *connect.Request[endpoints.RestoreDatabaseRequest]) (*connect.ServerStreamForClient[endpoints.RestoreProgress], error) {
	return c.restoreDatabase.CallServerStream(ctx, req)
}

// GetPostgresInsights calls api.proto.service.AgentService.GetPostgresInsights.
func (c *agentServiceClient) GetPostgresInsights(ctx context.Context, req *connect.Request[endpoints.GetPostgresInsightsRequest]) (*connect.Response[endpoints.GetPostgresInsightsResponse], error) {
	return c.getPostgresInsights.CallUnary(ctx, req)
}

// ShutdownDatabase calls api.proto.service.AgentService.ShutdownDatabase.
func (c *agentServiceClient) ShutdownDatabase(ctx context.Context, req *connect.Request[endpoints.ShutdownDatabaseRequest]) (*connect.Response[endpoints.ShutdownDatabaseResponse], error) {
	return c.shutdownDatabase.CallUnary(ctx, req)
}

// RemoveDatabase calls api.proto.service.AgentService.RemoveDatabase.
func (c *agentServiceClient) RemoveDatabase(ctx context.Context, req *connect.Request[endpoints.RemoveDatabaseRequest]) (*connect.Response[endpoints.RemoveDatabaseResponse], error) {
	return c.removeDatabase.CallUnary(ctx, req)
}

// VacuumDatabase calls api.proto.service.AgentService.VacuumDatabase.
func (c *agentServiceClient) VacuumDatabase(ctx context.Context, req *connect.Request[endpoints.VacuumDatabaseRequest]) (*connect.ServerStreamForClient[endpoints.VacuumProgress], error) {
	return c.vacuumDatabase.CallServerStream(ctx, req)
}

// AgentServiceHandler is an implementation of the api.proto.service.AgentService service.
type AgentServiceHandler interface {
	// GetSystemInfo returns basic information about the host system.
	GetSystemInfo(context.Context, *connect.Request[endpoints.GetSystemInfoRequest]) (*connect.Response[endpoints.GetSystemInfoResponse], error)
	// UpdateConfig updates a configuration file on the host.
	UpdateConfig(context.Context, *connect.Request[endpoints.UpdateConfigRequest]) (*connect.Response[endpoints.UpdateConfigResponse], error)
	// ExecuteCommand executes a shell command on the host and streams the output.
	ExecuteCommand(context.Context, *connect.Request[endpoints.ExecuteCommandRequest], *connect.ServerStream[endpoints.ExecuteCommandResponse]) error
	// RestartService restarts a system service (e.g., postgresql).
	RestartService(context.Context, *connect.Request[endpoints.RestartServiceRequest]) (*connect.Response[endpoints.RestartServiceResponse], error)
	// StreamLogs streams the logs of a database instance.
	StreamLogs(context.Context, *connect.Request[endpoints.LogStreamRequest], *connect.ServerStream[endpoints.LogStreamResponse]) error
	// ScheduleMaintenance schedules a maintenance task.
	ScheduleMaintenance(context.Context, *connect.Request[endpoints.ScheduleMaintenanceRequest]) (*connect.Response[endpoints.ScheduleMaintenanceResponse], error)
	// SetupReplication configures the host as a replica of another host.
	SetupReplication(context.Context, *connect.Request[endpoints.SetupReplicationRequest], *connect.ServerStream[endpoints.ReplicationProgress]) error
	// PromoteNode promotes a replica to a primary.
	PromoteNode(context.Context, *connect.Request[endpoints.PromoteNodeRequest]) (*connect.Response[endpoints.PromoteNodeResponse], error)
	// InitializeDatabase initializes a new database instance.
	InitializeDatabase(context.Context, *connect.Request[endpoints.InitializeDatabaseRequest], *connect.ServerStream[endpoints.InitializeProgress]) error
	// InstallDatabase installs the database software.
	InstallDatabase(context.Context, *connect.Request[endpoints.InstallDatabaseRequest], *connect.ServerStream[endpoints.InstallProgress]) error
	// BackupDatabase creates a backup of the database.
	BackupDatabase(context.Context, *connect.Request[endpoints.BackupDatabaseRequest], *connect.ServerStream[endpoints.BackupProgress]) error
	// RestoreDatabase restores the database from a backup.
	RestoreDatabase(context.Context, *connect.Request[endpoints.RestoreDatabaseRequest], *connect.ServerStream[endpoints.RestoreProgress]) error
	// GetPostgresInsights returns database-specific insights for Postgres.
	GetPostgresInsights(context.Context, *connect.Request[endpoints.GetPostgresInsightsRequest]) (*connect.Response[endpoints.GetPostgresInsightsResponse], error)
	// ShutdownDatabase stops the database service.
	ShutdownDatabase(context.Context, *connect.Request[endpoints.ShutdownDatabaseRequest]) (*connect.Response[endpoints.ShutdownDatabaseResponse], error)
	// RemoveDatabase stops the database and removes its data directory.
	RemoveDatabase(context.Context, *connect.Request[endpoints.RemoveDatabaseRequest]) (*connect.Response[endpoints.RemoveDatabaseResponse], error)
	// VacuumDatabase performs a VACUUM operation on the database.
	VacuumDatabase(context.Context, *connect.Request[endpoints.VacuumDatabaseRequest], *connect.ServerStream[endpoints.VacuumProgress]) error
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := service.File_api_proto_service_agent_proto.Services().ByName("AgentService").Methods()
	agentServiceGetSystemInfoHandler := connect.NewUnaryHandler(
		AgentServiceGetSystemInfoProcedure,
		svc.GetSystemInfo,
		connect.WithSchema(agentServiceMethods.ByName("GetSystemInfo")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceUpdateConfigHandler := connect.NewUnaryHandler(
		AgentServiceUpdateConfigProcedure,
		svc.UpdateConfig,
		connect.WithSchema(agentServiceMethods.ByName("UpdateConfig")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceExecuteCommandHandler := connect.NewServerStreamHandler(
		AgentServiceExecuteCommandProcedure,
		svc.ExecuteCommand,
		connect.WithSchema(agentServiceMethods.ByName("ExecuteCommand")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceRestartServiceHandler := connect.NewUnaryHandler(
		AgentServiceRestartServiceProcedure,
		svc.RestartService,
		connect.WithSchema(agentServiceMethods.ByName("RestartService")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceStreamLogsHandler := connect.NewServerStreamHandler(
		AgentServiceStreamLogsProcedure,
		svc.StreamLogs,
		connect.WithSchema(agentServiceMethods.ByName("StreamLogs")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceScheduleMaintenanceHandler := connect.NewUnaryHandler(
		AgentServiceScheduleMaintenanceProcedure,
		svc.ScheduleMaintenance,
		connect.WithSchema(agentServiceMethods.ByName("ScheduleMaintenance")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceSetupReplicationHandler := connect.NewServerStreamHandler(
		AgentServiceSetupReplicationProcedure,
		svc.SetupReplication,
		connect.WithSchema(agentServiceMethods.ByName("SetupReplication")),
		connect.WithHandlerOptions(opts...),
	)
	agentServicePromoteNodeHandler := connect.NewUnaryHandler(
		AgentServicePromoteNodeProcedure,
		svc.PromoteNode,
		connect.WithSchema(agentServiceMethods.ByName("PromoteNode")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceInitializeDatabaseHandler := connect.NewServerStreamHandler(
		AgentServiceInitializeDatabaseProcedure,
		svc.InitializeDatabase,
		connect.WithSchema(agentServiceMethods.ByName("InitializeDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceInstallDatabaseHandler := connect.NewServerStreamHandler(
		AgentServiceInstallDatabaseProcedure,
		svc.InstallDatabase,
		connect.WithSchema(agentServiceMethods.ByName("InstallDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceBackupDatabaseHandler := connect.NewServerStreamHandler(
		AgentServiceBackupDatabaseProcedure,
		svc.BackupDatabase,
		connect.WithSchema(agentServiceMethods.ByName("BackupDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceRestoreDatabaseHandler := connect.NewServerStreamHandler(
		AgentServiceRestoreDatabaseProcedure,
		svc.RestoreDatabase,
		connect.WithSchema(agentServiceMethods.ByName("RestoreDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetPostgresInsightsHandler := connect.NewUnaryHandler(
		AgentServiceGetPostgresInsightsProcedure,
		svc.GetPostgresInsights,
		connect.WithSchema(agentServiceMethods.ByName("GetPostgresInsights")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceShutdownDatabaseHandler := connect.NewUnaryHandler(
		AgentServiceShutdownDatabaseProcedure,
		svc.ShutdownDatabase,
		connect.WithSchema(agentServiceMethods.ByName("ShutdownDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceRemoveDatabaseHandler := connect.NewUnaryHandler(
		AgentServiceRemoveDatabaseProcedure,
		svc.RemoveDatabase,
		connect.WithSchema(agentServiceMethods.ByName("RemoveDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceVacuumDatabaseHandler := connect.NewServerStreamHandler(
		AgentServiceVacuumDatabaseProcedure,
		svc.VacuumDatabase,
		connect.WithSchema(agentServiceMethods.ByName("VacuumDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.proto.service.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceGetSystemInfoProcedure:
			agentServiceGetSystemInfoHandler.ServeHTTP(w, r)
		case AgentServiceUpdateConfigProcedure:
			agentServiceUpdateConfigHandler.ServeHTTP(w, r)
		case AgentServiceExecuteCommandProcedure:
			agentServiceExecuteCommandHandler.ServeHTTP(w, r)
		case AgentServiceRestartServiceProcedure:
			agentServiceRestartServiceHandler.ServeHTTP(w, r)
		case AgentServiceStreamLogsProcedure:
			agentServiceStreamLogsHandler.ServeHTTP(w, r)
		case AgentServiceScheduleMaintenanceProcedure:
			agentServiceScheduleMaintenanceHandler.ServeHTTP(w, r)
		case AgentServiceSetupReplicationProcedure:
			agentServiceSetupReplicationHandler.ServeHTTP(w, r)
		case AgentServicePromoteNodeProcedure:
			agentServicePromoteNodeHandler.ServeHTTP(w, r)
		case AgentServiceInitializeDatabaseProcedure:
			agentServiceInitializeDatabaseHandler.ServeHTTP(w, r)
		case AgentServiceInstallDatabaseProcedure:
			agentServiceInstallDatabaseHandler.ServeHTTP(w, r)
		case AgentServiceBackupDatabaseProcedure:
			agentServiceBackupDatabaseHandler.ServeHTTP(w, r)
		case AgentServiceRestoreDatabaseProcedure:
			agentServiceRestoreDatabaseHandler.ServeHTTP(w, r)
		case AgentServiceGetPostgresInsightsProcedure:
			agentServiceGetPostgresInsightsHandler.ServeHTTP(w, r)
		case AgentServiceShutdownDatabaseProcedure:
			agentServiceShutdownDatabaseHandler.ServeHTTP(w, r)
		case AgentServiceRemoveDatabaseProcedure:
			agentServiceRemoveDatabaseHandler.ServeHTTP(w, r)
		case AgentServiceVacuumDatabaseProcedure:
			agentServiceVacuumDatabaseHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) GetSystemInfo(context.Context, *connect.Request[endpoints.GetSystemInfoRequest]) (*connect.Response[endpoints.GetSystemInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.GetSystemInfo is not implemented"))
}

func (UnimplementedAgentServiceHandler) UpdateConfig(context.Context, *connect.Request[endpoints.UpdateConfigRequest]) (*connect.Response[endpoints.UpdateConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.UpdateConfig is not implemented"))
}

func (UnimplementedAgentServiceHandler) ExecuteCommand(context.Context, *connect.Request[endpoints.ExecuteCommandRequest], *connect.ServerStream[endpoints.ExecuteCommandResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.ExecuteCommand is not implemented"))
}

func (UnimplementedAgentServiceHandler) RestartService(context.Context, *connect.Request[endpoints.RestartServiceRequest]) (*connect.Response[endpoints.RestartServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.RestartService is not implemented"))
}

func (UnimplementedAgentServiceHandler) StreamLogs(context.Context, *connect.Request[endpoints.LogStreamRequest], *connect.ServerStream[endpoints.LogStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.StreamLogs is not implemented"))
}

func (UnimplementedAgentServiceHandler) ScheduleMaintenance(context.Context, *connect.Request[endpoints.ScheduleMaintenanceRequest]) (*connect.Response[endpoints.ScheduleMaintenanceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.ScheduleMaintenance is not implemented"))
}

func (UnimplementedAgentServiceHandler) SetupReplication(context.Context, *connect.Request[endpoints.SetupReplicationRequest], *connect.ServerStream[endpoints.ReplicationProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.SetupReplication is not implemented"))
}

func (UnimplementedAgentServiceHandler) PromoteNode(context.Context, *connect.Request[endpoints.PromoteNodeRequest]) (*connect.Response[endpoints.PromoteNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.PromoteNode is not implemented"))
}

func (UnimplementedAgentServiceHandler) InitializeDatabase(context.Context, *connect.Request[endpoints.InitializeDatabaseRequest], *connect.ServerStream[endpoints.InitializeProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.InitializeDatabase is not implemented"))
}

func (UnimplementedAgentServiceHandler) InstallDatabase(context.Context, *connect.Request[endpoints.InstallDatabaseRequest], *connect.ServerStream[endpoints.InstallProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.InstallDatabase is not implemented"))
}

func (UnimplementedAgentServiceHandler) BackupDatabase(context.Context, *connect.Request[endpoints.BackupDatabaseRequest], *connect.ServerStream[endpoints.BackupProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.BackupDatabase is not implemented"))
}

func (UnimplementedAgentServiceHandler) RestoreDatabase(context.Context, *connect.Request[endpoints.RestoreDatabaseRequest], *connect.ServerStream[endpoints.RestoreProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.RestoreDatabase is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetPostgresInsights(context.Context, *connect.Request[endpoints.GetPostgresInsightsRequest]) (*connect.Response[endpoints.GetPostgresInsightsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.GetPostgresInsights is not implemented"))
}

func (UnimplementedAgentServiceHandler) ShutdownDatabase(context.Context, *connect.Request[endpoints.ShutdownDatabaseRequest]) (*connect.Response[endpoints.ShutdownDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.ShutdownDatabase is not implemented"))
}

func (UnimplementedAgentServiceHandler) RemoveDatabase(context.Context, *connect.Request[endpoints.RemoveDatabaseRequest]) (*connect.Response[endpoints.RemoveDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.RemoveDatabase is not implemented"))
}

func (UnimplementedAgentServiceHandler) VacuumDatabase(context.Context, *connect.Request[endpoints.VacuumDatabaseRequest], *connect.ServerStream[endpoints.VacuumProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.AgentService.VacuumDatabase is not implemented"))
}
