// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/proto/service/management.proto

package serviceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	domain "github.com/gsoultan/pontus/api/proto/domain"
	endpoints "github.com/gsoultan/pontus/api/proto/endpoints"
	service "github.com/gsoultan/pontus/api/proto/service"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ManagementServiceName is the fully-qualified name of the ManagementService service.
	ManagementServiceName = "api.proto.service.ManagementService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ManagementServiceListProjectsProcedure is the fully-qualified name of the ManagementService's
	// ListProjects RPC.
	ManagementServiceListProjectsProcedure = "/api.proto.service.ManagementService/ListProjects"
	// ManagementServiceCreateProjectProcedure is the fully-qualified name of the ManagementService's
	// CreateProject RPC.
	ManagementServiceCreateProjectProcedure = "/api.proto.service.ManagementService/CreateProject"
	// ManagementServiceDeleteProjectProcedure is the fully-qualified name of the ManagementService's
	// DeleteProject RPC.
	ManagementServiceDeleteProjectProcedure = "/api.proto.service.ManagementService/DeleteProject"
	// ManagementServiceAddProxyProcedure is the fully-qualified name of the ManagementService's
	// AddProxy RPC.
	ManagementServiceAddProxyProcedure = "/api.proto.service.ManagementService/AddProxy"
	// ManagementServiceRemoveProxyProcedure is the fully-qualified name of the ManagementService's
	// RemoveProxy RPC.
	ManagementServiceRemoveProxyProcedure = "/api.proto.service.ManagementService/RemoveProxy"
	// ManagementServiceUpdateProxyProcedure is the fully-qualified name of the ManagementService's
	// UpdateProxy RPC.
	ManagementServiceUpdateProxyProcedure = "/api.proto.service.ManagementService/UpdateProxy"
	// ManagementServiceGetStatusProcedure is the fully-qualified name of the ManagementService's
	// GetStatus RPC.
	ManagementServiceGetStatusProcedure = "/api.proto.service.ManagementService/GetStatus"
	// ManagementServiceStreamStatusProcedure is the fully-qualified name of the ManagementService's
	// StreamStatus RPC.
	ManagementServiceStreamStatusProcedure = "/api.proto.service.ManagementService/StreamStatus"
	// ManagementServiceAddBackendProcedure is the fully-qualified name of the ManagementService's
	// AddBackend RPC.
	ManagementServiceAddBackendProcedure = "/api.proto.service.ManagementService/AddBackend"
	// ManagementServiceRemoveBackendProcedure is the fully-qualified name of the ManagementService's
	// RemoveBackend RPC.
	ManagementServiceRemoveBackendProcedure = "/api.proto.service.ManagementService/RemoveBackend"
	// ManagementServiceUpdateBackendProcedure is the fully-qualified name of the ManagementService's
	// UpdateBackend RPC.
	ManagementServiceUpdateBackendProcedure = "/api.proto.service.ManagementService/UpdateBackend"
	// ManagementServiceProvisionReplicaProcedure is the fully-qualified name of the ManagementService's
	// ProvisionReplica RPC.
	ManagementServiceProvisionReplicaProcedure = "/api.proto.service.ManagementService/ProvisionReplica"
	// ManagementServiceValidateBackendProcedure is the fully-qualified name of the ManagementService's
	// ValidateBackend RPC.
	ManagementServiceValidateBackendProcedure = "/api.proto.service.ManagementService/ValidateBackend"
	// ManagementServiceStreamLogsProcedure is the fully-qualified name of the ManagementService's
	// StreamLogs RPC.
	ManagementServiceStreamLogsProcedure = "/api.proto.service.ManagementService/StreamLogs"
	// ManagementServiceInitializeNodeProcedure is the fully-qualified name of the ManagementService's
	// InitializeNode RPC.
	ManagementServiceInitializeNodeProcedure = "/api.proto.service.ManagementService/InitializeNode"
	// ManagementServiceInstallNodeProcedure is the fully-qualified name of the ManagementService's
	// InstallNode RPC.
	ManagementServiceInstallNodeProcedure = "/api.proto.service.ManagementService/InstallNode"
	// ManagementServiceBackupBackendProcedure is the fully-qualified name of the ManagementService's
	// BackupBackend RPC.
	ManagementServiceBackupBackendProcedure = "/api.proto.service.ManagementService/BackupBackend"
	// ManagementServiceRestoreBackendProcedure is the fully-qualified name of the ManagementService's
	// RestoreBackend RPC.
	ManagementServiceRestoreBackendProcedure = "/api.proto.service.ManagementService/RestoreBackend"
	// ManagementServicePromoteBackendProcedure is the fully-qualified name of the ManagementService's
	// PromoteBackend RPC.
	ManagementServicePromoteBackendProcedure = "/api.proto.service.ManagementService/PromoteBackend"
	// ManagementServiceGetMetricsHistoryProcedure is the fully-qualified name of the
	// ManagementService's GetMetricsHistory RPC.
	ManagementServiceGetMetricsHistoryProcedure = "/api.proto.service.ManagementService/GetMetricsHistory"
	// ManagementServiceGetTopQueriesHistoryProcedure is the fully-qualified name of the
	// ManagementService's GetTopQueriesHistory RPC.
	ManagementServiceGetTopQueriesHistoryProcedure = "/api.proto.service.ManagementService/GetTopQueriesHistory"
	// ManagementServiceSetClusterConfigProcedure is the fully-qualified name of the ManagementService's
	// SetClusterConfig RPC.
	ManagementServiceSetClusterConfigProcedure = "/api.proto.service.ManagementService/SetClusterConfig"
	// ManagementServiceGetClusterConfigProcedure is the fully-qualified name of the ManagementService's
	// GetClusterConfig RPC.
	ManagementServiceGetClusterConfigProcedure = "/api.proto.service.ManagementService/GetClusterConfig"
	// ManagementServiceDiscoverClusterProcedure is the fully-qualified name of the ManagementService's
	// DiscoverCluster RPC.
	ManagementServiceDiscoverClusterProcedure = "/api.proto.service.ManagementService/DiscoverCluster"
	// ManagementServiceVacuumBackendProcedure is the fully-qualified name of the ManagementService's
	// VacuumBackend RPC.
	ManagementServiceVacuumBackendProcedure = "/api.proto.service.ManagementService/VacuumBackend"
	// ManagementServiceExplainQueryProcedure is the fully-qualified name of the ManagementService's
	// ExplainQuery RPC.
	ManagementServiceExplainQueryProcedure = "/api.proto.service.ManagementService/ExplainQuery"
	// ManagementServiceGetLogsProcedure is the fully-qualified name of the ManagementService's GetLogs
	// RPC.
	ManagementServiceGetLogsProcedure = "/api.proto.service.ManagementService/GetLogs"
	// ManagementServiceTuneDatabaseProcedure is the fully-qualified name of the ManagementService's
	// TuneDatabase RPC.
	ManagementServiceTuneDatabaseProcedure = "/api.proto.service.ManagementService/TuneDatabase"
	// ManagementServiceApplyTuningProcedure is the fully-qualified name of the ManagementService's
	// ApplyTuning RPC.
	ManagementServiceApplyTuningProcedure = "/api.proto.service.ManagementService/ApplyTuning"
	// ManagementServiceGetAgentInfoProcedure is the fully-qualified name of the ManagementService's
	// GetAgentInfo RPC.
	ManagementServiceGetAgentInfoProcedure = "/api.proto.service.ManagementService/GetAgentInfo"
	// ManagementServiceGetAvailableVersionsProcedure is the fully-qualified name of the
	// ManagementService's GetAvailableVersions RPC.
	ManagementServiceGetAvailableVersionsProcedure = "/api.proto.service.ManagementService/GetAvailableVersions"
	// ManagementServiceLoginProcedure is the fully-qualified name of the ManagementService's Login RPC.
	ManagementServiceLoginProcedure = "/api.proto.service.ManagementService/Login"
	// ManagementServiceCreateUserProcedure is the fully-qualified name of the ManagementService's
	// CreateUser RPC.
	ManagementServiceCreateUserProcedure = "/api.proto.service.ManagementService/CreateUser"
	// ManagementServiceGetServerInfoProcedure is the fully-qualified name of the ManagementService's
	// GetServerInfo RPC.
	ManagementServiceGetServerInfoProcedure = "/api.proto.service.ManagementService/GetServerInfo"
	// ManagementServiceGetPostgresInsightsProcedure is the fully-qualified name of the
	// ManagementService's GetPostgresInsights RPC.
	ManagementServiceGetPostgresInsightsProcedure = "/api.proto.service.ManagementService/GetPostgresInsights"
	// ManagementServiceRestartBackendServiceProcedure is the fully-qualified name of the
	// ManagementService's RestartBackendService RPC.
	ManagementServiceRestartBackendServiceProcedure = "/api.proto.service.ManagementService/RestartBackendService"
	// ManagementServiceShutdownBackendProcedure is the fully-qualified name of the ManagementService's
	// ShutdownBackend RPC.
	ManagementServiceShutdownBackendProcedure = "/api.proto.service.ManagementService/ShutdownBackend"
)

// ManagementServiceClient is a client for the api.proto.service.ManagementService service.
type ManagementServiceClient interface {
	// Projects management
	ListProjects(context.Context, *connect.Request[endpoints.ListProjectsRequest]) (*connect.Response[endpoints.ListProjectsResponse], error)
	CreateProject(context.Context, *connect.Request[endpoints.CreateProjectRequest]) (*connect.Response[endpoints.CreateProjectResponse], error)
	DeleteProject(context.Context, *connect.Request[endpoints.DeleteProjectRequest]) (*connect.Response[endpoints.DeleteProjectResponse], error)
	// Proxies management
	AddProxy(context.Context, *connect.Request[endpoints.AddProxyRequest]) (*connect.Response[endpoints.AddProxyResponse], error)
	RemoveProxy(context.Context, *connect.Request[endpoints.RemoveProxyRequest]) (*connect.Response[endpoints.RemoveProxyResponse], error)
	UpdateProxy(context.Context, *connect.Request[endpoints.UpdateProxyRequest]) (*connect.Response[endpoints.UpdateProxyResponse], error)
	// GetStatus returns the current status of all backends and global metrics.
	GetStatus(context.Context, *connect.Request[endpoints.GetStatusRequest]) (*connect.Response[endpoints.GetStatusResponse], error)
	// StreamStatus pushes status updates for as long as the client is connected.
	//
	// Replaces polling GetStatus on a timer. The dashboard re-fetched the entire
	// payload — every backend, twenty top queries with full SQL text, topology,
	// system metrics — on a fixed interval whether anything had changed or not,
	// per connected dashboard. Read-only, same as GetStatus.
	StreamStatus(context.Context, *connect.Request[endpoints.StreamStatusRequest]) (*connect.ServerStreamForClient[endpoints.GetStatusResponse], error)
	// AddBackend adds a new backend to the pool.
	AddBackend(context.Context, *connect.Request[endpoints.AddBackendRequest]) (*connect.Response[endpoints.AddBackendResponse], error)
	// RemoveBackend removes a backend from the pool.
	RemoveBackend(context.Context, *connect.Request[endpoints.RemoveBackendRequest]) (*connect.Response[endpoints.RemoveBackendResponse], error)
	// UpdateBackend updates an existing backend configuration.
	UpdateBackend(context.Context, *connect.Request[endpoints.UpdateBackendRequest]) (*connect.Response[endpoints.UpdateBackendResponse], error)
	// ProvisionReplica provisions a new replica from a source.
	ProvisionReplica(context.Context, *connect.Request[endpoints.ProvisionReplicaRequest]) (*connect.ServerStreamForClient[endpoints.ProvisionProgress], error)
	// ValidateBackend checks if a backend is accessible.
	ValidateBackend(context.Context, *connect.Request[endpoints.ValidateBackendRequest]) (*connect.Response[endpoints.ValidateBackendResponse], error)
	// StreamLogs returns a real-time stream of logs.
	StreamLogs(context.Context, *connect.Request[endpoints.StreamLogsRequest]) (*connect.ServerStreamForClient[domain.LogEntry], error)
	// InitializeNode initializes a database on a clean host via Agent.
	InitializeNode(context.Context, *connect.Request[endpoints.InitializeNodeRequest]) (*connect.ServerStreamForClient[endpoints.InitializeNodeProgress], error)
	// InstallNode installs the database software on a clean host via Agent.
	InstallNode(context.Context, *connect.Request[endpoints.InstallNodeRequest]) (*connect.ServerStreamForClient[endpoints.InstallNodeProgress], error)
	// BackupBackend triggers a database backup on a backend via Agent.
	BackupBackend(context.Context, *connect.Request[endpoints.BackupBackendRequest]) (*connect.ServerStreamForClient[endpoints.BackupBackendProgress], error)
	// RestoreBackend triggers a database restore on a backend via Agent.
	RestoreBackend(context.Context, *connect.Request[endpoints.RestoreBackendRequest]) (*connect.ServerStreamForClient[endpoints.RestoreBackendProgress], error)
	// PromoteBackend promotes a replica to primary.
	PromoteBackend(context.Context, *connect.Request[endpoints.PromoteBackendRequest]) (*connect.Response[endpoints.PromoteBackendResponse], error)
	// GetMetricsHistory returns historical metrics.
	GetMetricsHistory(context.Context, *connect.Request[endpoints.GetMetricsHistoryRequest]) (*connect.Response[endpoints.GetMetricsHistoryResponse], error)
	// GetTopQueriesHistory returns historical top queries.
	GetTopQueriesHistory(context.Context, *connect.Request[endpoints.GetTopQueriesHistoryRequest]) (*connect.Response[endpoints.GetTopQueriesHistoryResponse], error)
	// SetClusterConfig updates configuration across the cluster.
	SetClusterConfig(context.Context, *connect.Request[endpoints.SetClusterConfigRequest]) (*connect.Response[endpoints.SetClusterConfigResponse], error)
	// GetClusterConfig returns the current cluster configuration.
	GetClusterConfig(context.Context, *connect.Request[endpoints.GetClusterConfigRequest]) (*connect.Response[endpoints.GetClusterConfigResponse], error)
	// DiscoverCluster auto-discovers and adds all nodes in a cluster.
	DiscoverCluster(context.Context, *connect.Request[endpoints.DiscoverClusterRequest]) (*connect.Response[endpoints.DiscoverClusterResponse], error)
	// VacuumBackend triggers a VACUUM operation on a backend via Agent.
	VacuumBackend(context.Context, *connect.Request[endpoints.VacuumBackendRequest]) (*connect.ServerStreamForClient[endpoints.VacuumBackendProgress], error)
	// ExplainQuery analyzes a SQL query.
	ExplainQuery(context.Context, *connect.Request[endpoints.ExplainQueryRequest]) (*connect.Response[endpoints.ExplainQueryResponse], error)
	// GetLogs returns historical logs with filtering and pagination.
	GetLogs(context.Context, *connect.Request[endpoints.GetLogsRequest]) (*connect.Response[endpoints.GetLogsResponse], error)
	// TuneDatabase provides tuning recommendations based on system resources.
	TuneDatabase(context.Context, *connect.Request[endpoints.TuneDatabaseRequest]) (*connect.Response[endpoints.TuneDatabaseResponse], error)
	// ApplyTuning applies a tuning suggestion to a backend.
	ApplyTuning(context.Context, *connect.Request[endpoints.ApplyTuningRequest]) (*connect.Response[endpoints.ApplyTuningResponse], error)
	// GetAgentInfo fetches system info from a Pontus Agent.
	GetAgentInfo(context.Context, *connect.Request[endpoints.GetAgentInfoRequest]) (*connect.Response[endpoints.GetAgentInfoResponse], error)
	// GetAvailableVersions returns all supported PostgreSQL versions.
	GetAvailableVersions(context.Context, *connect.Request[endpoints.GetAvailableVersionsRequest]) (*connect.Response[endpoints.GetAvailableVersionsResponse], error)
	// Login authenticates a user and returns a token.
	Login(context.Context, *connect.Request[endpoints.LoginRequest]) (*connect.Response[endpoints.LoginResponse], error)
	// CreateUser creates a new management user.
	CreateUser(context.Context, *connect.Request[endpoints.CreateUserRequest]) (*connect.Response[endpoints.CreateUserResponse], error)
	// GetServerInfo returns information about the Pontus server.
	GetServerInfo(context.Context, *connect.Request[endpoints.GetServerInfoRequest]) (*connect.Response[endpoints.GetServerInfoResponse], error)
	// GetPostgresInsights retrieves database-specific insights for a backend.
	GetPostgresInsights(context.Context, *connect.Request[endpoints.GetBackendPostgresInsightsRequest]) (*connect.Response[endpoints.GetBackendPostgresInsightsResponse], error)
	// RestartBackendService restarts the database service on a backend via Agent.
	RestartBackendService(context.Context, *connect.Request[endpoints.RestartBackendServiceRequest]) (*connect.Response[endpoints.RestartBackendServiceResponse], error)
	// ShutdownBackend shuts down the database on a backend via Agent.
	ShutdownBackend(context.Context, *connect.Request[endpoints.ShutdownBackendRequest]) (*connect.Response[endpoints.ShutdownBackendResponse], error)
}

// NewManagementServiceClient constructs a client for the api.proto.service.ManagementService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewManagementServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ManagementServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	managementServiceMethods := service.File_api_proto_service_management_proto.Services().ByName("ManagementService").Methods()
	return &managementServiceClient{
		listProjects: connect.NewClient[endpoints.ListProjectsRequest, endpoints.ListProjectsResponse](
			httpClient,
			baseURL+ManagementServiceListProjectsProcedure,
			connect.WithSchema(managementServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		createProject: connect.NewClient[endpoints.CreateProjectRequest, endpoints.CreateProjectResponse](
			httpClient,
			baseURL+ManagementServiceCreateProjectProcedure,
			connect.WithSchema(managementServiceMethods.ByName("CreateProject")),
			connect.WithClientOptions(opts...),
		),
		deleteProject: connect.NewClient[endpoints.DeleteProjectRequest, endpoints.DeleteProjectResponse](
			httpClient,
			baseURL+ManagementServiceDeleteProjectProcedure,
			connect.WithSchema(managementServiceMethods.ByName("DeleteProject")),
			connect.WithClientOptions(opts...),
		),
		addProxy: connect.NewClient[endpoints.AddProxyRequest, endpoints.AddProxyResponse](
			httpClient,
			baseURL+ManagementServiceAddProxyProcedure,
			connect.WithSchema(managementServiceMethods.ByName("AddProxy")),
			connect.WithClientOptions(opts...),
		),
		removeProxy: connect.NewClient[endpoints.RemoveProxyRequest, endpoints.RemoveProxyResponse](
			httpClient,
			baseURL+ManagementServiceRemoveProxyProcedure,
			connect.WithSchema(managementServiceMethods.ByName("RemoveProxy")),
			connect.WithClientOptions(opts...),
		),
		updateProxy: connect.NewClient[endpoints.UpdateProxyRequest, endpoints.UpdateProxyResponse](
			httpClient,
			baseURL+ManagementServiceUpdateProxyProcedure,
			connect.WithSchema(managementServiceMethods.ByName("UpdateProxy")),
			connect.WithClientOptions(opts...),
		),
		getStatus: connect.NewClient[endpoints.GetStatusRequest, endpoints.GetStatusResponse](
			httpClient,
			baseURL+ManagementServiceGetStatusProcedure,
			connect.WithSchema(managementServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
		streamStatus: connect.NewClient[endpoints.StreamStatusRequest, endpoints.GetStatusResponse](
			httpClient,
			baseURL+ManagementServiceStreamStatusProcedure,
			connect.WithSchema(managementServiceMethods.ByName("StreamStatus")),
			connect.WithClientOptions(opts...),
		),
		addBackend: connect.NewClient[endpoints.AddBackendRequest, endpoints.AddBackendResponse](
			httpClient,
			baseURL+ManagementServiceAddBackendProcedure,
			connect.WithSchema(managementServiceMethods.ByName("AddBackend")),
			connect.WithClientOptions(opts...),
		),
		removeBackend: connect.NewClient[endpoints.RemoveBackendRequest, endpoints.RemoveBackendResponse](
			httpClient,
			baseURL+ManagementServiceRemoveBackendProcedure,
			connect.WithSchema(managementServiceMethods.ByName("RemoveBackend")),
			connect.WithClientOptions(opts...),
		),
		updateBackend: connect.NewClient[endpoints.UpdateBackendRequest, endpoints.UpdateBackendResponse](
			httpClient,
			baseURL+ManagementServiceUpdateBackendProcedure,
			connect.WithSchema(managementServiceMethods.ByName("UpdateBackend")),
			connect.WithClientOptions(opts...),
		),
		provisionReplica: connect.NewClient[endpoints.ProvisionReplicaRequest, endpoints.ProvisionProgress](
			httpClient,
			baseURL+ManagementServiceProvisionReplicaProcedure,
			connect.WithSchema(managementServiceMethods.ByName("ProvisionReplica")),
			connect.WithClientOptions(opts...),
		),
		validateBackend: connect.NewClient[endpoints.ValidateBackendRequest, endpoints.ValidateBackendResponse](
			httpClient,
			baseURL+ManagementServiceValidateBackendProcedure,
			connect.WithSchema(managementServiceMethods.ByName("ValidateBackend")),
			connect.WithClientOptions(opts...),
		),
		streamLogs: connect.NewClient[endpoints.StreamLogsRequest, domain.LogEntry](
			httpClient,
			baseURL+ManagementServiceStreamLogsProcedure,
			connect.WithSchema(managementServiceMethods.ByName("StreamLogs")),
			connect.WithClientOptions(opts...),
		),
		initializeNode: connect.NewClient[endpoints.InitializeNodeRequest, endpoints.InitializeNodeProgress](
			httpClient,
			baseURL+ManagementServiceInitializeNodeProcedure,
			connect.WithSchema(managementServiceMethods.ByName("InitializeNode")),
			connect.WithClientOptions(opts...),
		),
		installNode: connect.NewClient[endpoints.InstallNodeRequest, endpoints.InstallNodeProgress](
			httpClient,
			baseURL+ManagementServiceInstallNodeProcedure,
			connect.WithSchema(managementServiceMethods.ByName("InstallNode")),
			connect.WithClientOptions(opts...),
		),
		backupBackend: connect.NewClient[endpoints.BackupBackendRequest, endpoints.BackupBackendProgress](
			httpClient,
			baseURL+ManagementServiceBackupBackendProcedure,
			connect.WithSchema(managementServiceMethods.ByName("BackupBackend")),
			connect.WithClientOptions(opts...),
		),
		restoreBackend: connect.NewClient[endpoints.RestoreBackendRequest, endpoints.RestoreBackendProgress](
			httpClient,
			baseURL+ManagementServiceRestoreBackendProcedure,
			connect.WithSchema(managementServiceMethods.ByName("RestoreBackend")),
			connect.WithClientOptions(opts...),
		),
		promoteBackend: connect.NewClient[endpoints.PromoteBackendRequest, endpoints.PromoteBackendResponse](
			httpClient,
			baseURL+ManagementServicePromoteBackendProcedure,
			connect.WithSchema(managementServiceMethods.ByName("PromoteBackend")),
			connect.WithClientOptions(opts...),
		),
		getMetricsHistory: connect.NewClient[endpoints.GetMetricsHistoryRequest, endpoints.GetMetricsHistoryResponse](
			httpClient,
			baseURL+ManagementServiceGetMetricsHistoryProcedure,
			connect.WithSchema(managementServiceMethods.ByName("GetMetricsHistory")),
			connect.WithClientOptions(opts...),
		),
		getTopQueriesHistory: connect.NewClient[endpoints.GetTopQueriesHistoryRequest, endpoints.GetTopQueriesHistoryResponse](
			httpClient,
			baseURL+ManagementServiceGetTopQueriesHistoryProcedure,
			connect.WithSchema(managementServiceMethods.ByName("GetTopQueriesHistory")),
			connect.WithClientOptions(opts...),
		),
		setClusterConfig: connect.NewClient[endpoints.SetClusterConfigRequest, endpoints.SetClusterConfigResponse](
			httpClient,
			baseURL+ManagementServiceSetClusterConfigProcedure,
			connect.WithSchema(managementServiceMethods.ByName("SetClusterConfig")),
			connect.WithClientOptions(opts...),
		),
		getClusterConfig: connect.NewClient[endpoints.GetClusterConfigRequest, endpoints.GetClusterConfigResponse](
			httpClient,
			baseURL+ManagementServiceGetClusterConfigProcedure,
			connect.WithSchema(managementServiceMethods.ByName("GetClusterConfig")),
			connect.WithClientOptions(opts...),
		),
		discoverCluster: connect.NewClient[endpoints.DiscoverClusterRequest, endpoints.DiscoverClusterResponse](
			httpClient,
			baseURL+ManagementServiceDiscoverClusterProcedure,
			connect.WithSchema(managementServiceMethods.ByName("DiscoverCluster")),
			connect.WithClientOptions(opts...),
		),
		vacuumBackend: connect.NewClient[endpoints.VacuumBackendRequest, endpoints.VacuumBackendProgress](
			httpClient,
			baseURL+ManagementServiceVacuumBackendProcedure,
			connect.WithSchema(managementServiceMethods.ByName("VacuumBackend")),
			connect.WithClientOptions(opts...),
		),
		explainQuery: connect.NewClient[endpoints.ExplainQueryRequest, endpoints.ExplainQueryResponse](
			httpClient,
			baseURL+ManagementServiceExplainQueryProcedure,
			connect.WithSchema(managementServiceMethods.ByName("ExplainQuery")),
			connect.WithClientOptions(opts...),
		),
		getLogs: connect.NewClient[endpoints.GetLogsRequest, endpoints.GetLogsResponse](
			httpClient,
			baseURL+ManagementServiceGetLogsProcedure,
			connect.WithSchema(managementServiceMethods.ByName("GetLogs")),
			connect.WithClientOptions(opts...),
		),
		tuneDatabase: connect.NewClient[endpoints.TuneDatabaseRequest, endpoints.TuneDatabaseResponse](
			httpClient,
			baseURL+ManagementServiceTuneDatabaseProcedure,
			connect.WithSchema(managementServiceMethods.ByName("TuneDatabase")),
			connect.WithClientOptions(opts...),
		),
		applyTuning: connect.NewClient[endpoints.ApplyTuningRequest, endpoints.ApplyTuningResponse](
			httpClient,
			baseURL+ManagementServiceApplyTuningProcedure,
			connect.WithSchema(managementServiceMethods.ByName("ApplyTuning")),
			connect.WithClientOptions(opts...),
		),
		getAgentInfo: connect.NewClient[endpoints.GetAgentInfoRequest, endpoints.GetAgentInfoResponse](
			httpClient,
			baseURL+ManagementServiceGetAgentInfoProcedure,
			connect.WithSchema(managementServiceMethods.ByName("GetAgentInfo")),
			connect.WithClientOptions(opts...),
		),
		getAvailableVersions: connect.NewClient[endpoints.GetAvailableVersionsRequest, endpoints.GetAvailableVersionsResponse](
			httpClient,
			baseURL+ManagementServiceGetAvailableVersionsProcedure,
			connect.WithSchema(managementServiceMethods.ByName("GetAvailableVersions")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[endpoints.LoginRequest, endpoints.LoginResponse](
			httpClient,
			baseURL+ManagementServiceLoginProcedure,
			connect.WithSchema(managementServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		createUser: connect.NewClient[endpoints.CreateUserRequest, endpoints.CreateUserResponse](
			httpClient,
			baseURL+ManagementServiceCreateUserProcedure,
			connect.WithSchema(managementServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		getServerInfo: connect.NewClient[endpoints.GetServerInfoRequest, endpoints.GetServerInfoResponse](
			httpClient,
			baseURL+ManagementServiceGetServerInfoProcedure,
			connect.WithSchema(managementServiceMethods.ByName("GetServerInfo")),
			connect.WithClientOptions(opts...),
		),
		getPostgresInsights: connect.NewClient[endpoints.GetBackendPostgresInsightsRequest, endpoints.GetBackendPostgresInsightsResponse](
			httpClient,
			baseURL+ManagementServiceGetPostgresInsightsProcedure,
			connect.WithSchema(managementServiceMethods.ByName("GetPostgresInsights")),
			connect.WithClientOptions(opts...),
		),
		restartBackendService: connect.NewClient[endpoints.RestartBackendServiceRequest, endpoints.RestartBackendServiceResponse](
			httpClient,
			baseURL+ManagementServiceRestartBackendServiceProcedure,
			connect.WithSchema(managementServiceMethods.ByName("RestartBackendService")),
			connect.WithClientOptions(opts...),
		),
		shutdownBackend: connect.NewClient[endpoints.ShutdownBackendRequest, endpoints.ShutdownBackendResponse](
			httpClient,
			baseURL+ManagementServiceShutdownBackendProcedure,
			connect.WithSchema(managementServiceMethods.ByName("ShutdownBackend")),
			connect.WithClientOptions(opts...),
		),
	}
}

// managementServiceClient implements ManagementServiceClient.
type managementServiceClient struct {
	listProjects          *connect.Client[endpoints.ListProjectsRequest, endpoints.ListProjectsResponse]
	createProject         *connect.Client[endpoints.CreateProjectRequest, endpoints.CreateProjectResponse]
	deleteProject         *connect.Client[endpoints.DeleteProjectRequest, endpoints.DeleteProjectResponse]
	addProxy              *connect.Client[endpoints.AddProxyRequest, endpoints.AddProxyResponse]
	removeProxy           *connect.Client[endpoints.RemoveProxyRequest, endpoints.RemoveProxyResponse]
	updateProxy           *connect.Client[endpoints.UpdateProxyRequest, endpoints.UpdateProxyResponse]
	getStatus             *connect.Client[endpoints.GetStatusRequest, endpoints.GetStatusResponse]
	streamStatus          *connect.Client[endpoints.StreamStatusRequest, endpoints.GetStatusResponse]
	addBackend            *connect.Client[endpoints.AddBackendRequest, endpoints.AddBackendResponse]
	removeBackend         *connect.Client[endpoints.RemoveBackendRequest, endpoints.RemoveBackendResponse]
	updateBackend         *connect.Client[endpoints.UpdateBackendRequest, endpoints.UpdateBackendResponse]
	provisionReplica      *connect.Client[endpoints.ProvisionReplicaRequest, endpoints.ProvisionProgress]
	validateBackend       *connect.Client[endpoints.ValidateBackendRequest, endpoints.ValidateBackendResponse]
	streamLogs            *connect.Client[endpoints.StreamLogsRequest, domain.LogEntry]
	initializeNode        *connect.Client[endpoints.InitializeNodeRequest, endpoints.InitializeNodeProgress]
	installNode           *connect.Client[endpoints.InstallNodeRequest, endpoints.InstallNodeProgress]
	backupBackend         *connect.Client[endpoints.BackupBackendRequest, endpoints.BackupBackendProgress]
	restoreBackend        *connect.Client[endpoints.RestoreBackendRequest, endpoints.RestoreBackendProgress]
	promoteBackend        *connect.Client[endpoints.PromoteBackendRequest, endpoints.PromoteBackendResponse]
	getMetricsHistory     *connect.Client[endpoints.GetMetricsHistoryRequest, endpoints.GetMetricsHistoryResponse]
	getTopQueriesHistory  *connect.Client[endpoints.GetTopQueriesHistoryRequest, endpoints.GetTopQueriesHistoryResponse]
	setClusterConfig      *connect.Client[endpoints.SetClusterConfigRequest, endpoints.SetClusterConfigResponse]
	getClusterConfig      *connect.Client[endpoints.GetClusterConfigRequest, endpoints.GetClusterConfigResponse]
	discoverCluster       *connect.Client[endpoints.DiscoverClusterRequest, endpoints.DiscoverClusterResponse]
	vacuumBackend         *connect.Client[endpoints.VacuumBackendRequest, endpoints.VacuumBackendProgress]
	explainQuery          *connect.Client[endpoints.ExplainQueryRequest, endpoints.ExplainQueryResponse]
	getLogs               *connect.Client[endpoints.GetLogsRequest, endpoints.GetLogsResponse]
	tuneDatabase          *connect.Client[endpoints.TuneDatabaseRequest, endpoints.TuneDatabaseResponse]
	applyTuning           *connect.Client[endpoints.ApplyTuningRequest, endpoints.ApplyTuningResponse]
	getAgentInfo          *connect.Client[endpoints.GetAgentInfoRequest, endpoints.GetAgentInfoResponse]
	getAvailableVersions  *connect.Client[endpoints.GetAvailableVersionsRequest, endpoints.GetAvailableVersionsResponse]
	login                 *connect.Client[endpoints.LoginRequest, endpoints.LoginResponse]
	createUser            *connect.Client[endpoints.CreateUserRequest, endpoints.CreateUserResponse]
	getServerInfo         *connect.Client[endpoints.GetServerInfoRequest, endpoints.GetServerInfoResponse]
	getPostgresInsights   *connect.Client[endpoints.GetBackendPostgresInsightsRequest, endpoints.GetBackendPostgresInsightsResponse]
	restartBackendService *connect.Client[endpoints.RestartBackendServiceRequest, endpoints.RestartBackendServiceResponse]
	shutdownBackend       *connect.Client[endpoints.ShutdownBackendRequest, endpoints.ShutdownBackendResponse]
}

// ListProjects calls api.proto.service.ManagementService.ListProjects.
func (c *managementServiceClient) ListProjects(ctx context.Context, req *connect.Request[endpoints.ListProjectsRequest]) (*connect.Response[endpoints.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// CreateProject calls api.proto.service.ManagementService.CreateProject.
func (c *managementServiceClient) CreateProject(ctx context.Context, req *connect.Request[endpoints.CreateProjectRequest]) (*connect.Response[endpoints.CreateProjectResponse], error) {
	return c.createProject.CallUnary(ctx, req)
}

// DeleteProject calls api.proto.service.ManagementService.DeleteProject.
func (c *managementServiceClient) DeleteProject(ctx context.Context, req *connect.Request[endpoints.DeleteProjectRequest]) (*connect.Response[endpoints.DeleteProjectResponse], error) {
	return c.deleteProject.CallUnary(ctx, req)
}

// AddProxy calls api.proto.service.ManagementService.AddProxy.
func (c *managementServiceClient) AddProxy(ctx context.Context, req *connect.Request[endpoints.AddProxyRequest]) (*connect.Response[endpoints.AddProxyResponse], error) {
	return c.addProxy.CallUnary(ctx, req)
}

// RemoveProxy calls api.proto.service.ManagementService.RemoveProxy.
func (c *managementServiceClient) RemoveProxy(ctx context.Context, req *connect.Request[endpoints.RemoveProxyRequest]) (*connect.Response[endpoints.RemoveProxyResponse], error) {
	return c.removeProxy.CallUnary(ctx, req)
}

// UpdateProxy calls api.proto.service.ManagementService.UpdateProxy.
func (c *managementServiceClient) UpdateProxy(ctx context.Context, req *connect.Request[endpoints.UpdateProxyRequest]) (*connect.Response[endpoints.UpdateProxyResponse], error) {
	return c.updateProxy.CallUnary(ctx, req)
}

// GetStatus calls api.proto.service.ManagementService.GetStatus.
func (c *managementServiceClient) GetStatus(ctx context.Context, req *connect.Request[endpoints.GetStatusRequest]) (*connect.Response[endpoints.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// StreamStatus calls api.proto.service.ManagementService.StreamStatus.
func (c *managementServiceClient) StreamStatus(ctx context.Context, req *connect.Request[endpoints.StreamStatusRequest]) (*connect.ServerStreamForClient[endpoints.GetStatusResponse], error) {
	return c.streamStatus.CallServerStream(ctx, req)
}

// AddBackend calls api.proto.service.ManagementService.AddBackend.
func (c *managementServiceClient) AddBackend(ctx context.Context, req *connect.Request[endpoints.AddBackendRequest]) (*connect.Response[endpoints.AddBackendResponse], error) {
	return c.addBackend.CallUnary(ctx, req)
}

// RemoveBackend calls api.proto.service.ManagementService.RemoveBackend.
func (c *managementServiceClient) RemoveBackend(ctx context.Context, req *connect.Request[endpoints.RemoveBackendRequest]) (*connect.Response[endpoints.RemoveBackendResponse], error) {
	return c.removeBackend.CallUnary(ctx, req)
}

// UpdateBackend calls api.proto.service.ManagementService.UpdateBackend.
func (c *managementServiceClient) UpdateBackend(ctx context.Context, req *connect.Request[endpoints.UpdateBackendRequest]) (*connect.Response[endpoints.UpdateBackendResponse], error) {
	return c.updateBackend.CallUnary(ctx, req)
}

// ProvisionReplica calls api.proto.service.ManagementService.ProvisionReplica.
func (c *managementServiceClient) ProvisionReplica(ctx context.Context, req *connect.Request[endpoints.ProvisionReplicaRequest]) (*connect.ServerStreamForClient[endpoints.ProvisionProgress], error) {
	return c.provisionReplica.CallServerStream(ctx, req)
}

// ValidateBackend calls api.proto.service.ManagementService.ValidateBackend.
func (c *managementServiceClient) ValidateBackend(ctx context.Context, req *connect.Request[endpoints.ValidateBackendRequest]) (*connect.Response[endpoints.ValidateBackendResponse], error) {
	return c.validateBackend.CallUnary(ctx, req)
}

// StreamLogs calls api.proto.service.ManagementService.StreamLogs.
func (c *managementServiceClient) StreamLogs(ctx context.Context, req *connect.Request[endpoints.StreamLogsRequest]) (*connect.ServerStreamForClient[domain.LogEntry], error) {
	return c.streamLogs.CallServerStream(ctx, req)
}

// InitializeNode calls api.proto.service.ManagementService.InitializeNode.
func (c *managementServiceClient) InitializeNode(ctx context.Context, req *connect.Request[endpoints.InitializeNodeRequest]) (*connect.ServerStreamForClient[endpoints.InitializeNodeProgress], error) {
	return c.initializeNode.CallServerStream(ctx, req)
}

// InstallNode calls api.proto.service.ManagementService.InstallNode.
func (c *managementServiceClient) InstallNode(ctx context.Context, req *connect.Request[endpoints.InstallNodeRequest]) (*connect.ServerStreamForClient[endpoints.InstallNodeProgress], error) {
	return c.installNode.CallServerStream(ctx, req)
}

// BackupBackend calls api.proto.service.ManagementService.BackupBackend.
func (c *managementServiceClient) BackupBackend(ctx context.Context, req *connect.Request[endpoints.BackupBackendRequest]) (*connect.ServerStreamForClient[endpoints.BackupBackendProgress], error) {
	return c.backupBackend.CallServerStream(ctx, req)
}

// RestoreBackend calls api.proto.service.ManagementService.RestoreBackend.
func (c *managementServiceClient) RestoreBackend(ctx context.Context, req *connect.Request[endpoints.RestoreBackendRequest]) (*connect.ServerStreamForClient[endpoints.RestoreBackendProgress], error) {
	return c.restoreBackend.CallServerStream(ctx, req)
}

// PromoteBackend calls api.proto.service.ManagementService.PromoteBackend.
func (c *managementServiceClient) PromoteBackend(ctx context.Context, req *connect.Request[endpoints.PromoteBackendRequest]) (*connect.Response[endpoints.PromoteBackendResponse], error) {
	return c.promoteBackend.CallUnary(ctx, req)
}

// GetMetricsHistory calls api.proto.service.ManagementService.GetMetricsHistory.
func (c *managementServiceClient) GetMetricsHistory(ctx context.Context, req *connect.Request[endpoints.GetMetricsHistoryRequest]) (*connect.Response[endpoints.GetMetricsHistoryResponse], error) {
	return c.getMetricsHistory.CallUnary(ctx, req)
}

// GetTopQueriesHistory calls api.proto.service.ManagementService.GetTopQueriesHistory.
func (c *managementServiceClient) GetTopQueriesHistory(ctx context.Context, req *connect.Request[endpoints.GetTopQueriesHistoryRequest]) (*connect.Response[endpoints.GetTopQueriesHistoryResponse], error) {
	return c.getTopQueriesHistory.CallUnary(ctx, req)
}

// SetClusterConfig calls api.proto.service.ManagementService.SetClusterConfig.
func (c *managementServiceClient) SetClusterConfig(ctx context.Context, req *connect.Request[endpoints.SetClusterConfigRequest]) (*connect.Response[endpoints.SetClusterConfigResponse], error) {
	return c.setClusterConfig.CallUnary(ctx, req)
}

// GetClusterConfig calls api.proto.service.ManagementService.GetClusterConfig.
func (c *managementServiceClient) GetClusterConfig(ctx context.Context, req *connect.Request[endpoints.GetClusterConfigRequest]) (*connect.Response[endpoints.GetClusterConfigResponse], error) {
	return c.getClusterConfig.CallUnary(ctx, req)
}

// DiscoverCluster calls api.proto.service.ManagementService.DiscoverCluster.
func (c *managementServiceClient) DiscoverCluster(ctx context.Context, req *connect.Request[endpoints.DiscoverClusterRequest]) (*connect.Response[endpoints.DiscoverClusterResponse], error) {
	return c.discoverCluster.CallUnary(ctx, req)
}

// VacuumBackend calls api.proto.service.ManagementService.VacuumBackend.
func (c *managementServiceClient) VacuumBackend(ctx context.Context, req *connect.Request[endpoints.VacuumBackendRequest]) (*connect.ServerStreamForClient[endpoints.VacuumBackendProgress], error) {
	return c.vacuumBackend.CallServerStream(ctx, req)
}

// ExplainQuery calls api.proto.service.ManagementService.ExplainQuery.
func (c *managementServiceClient) ExplainQuery(ctx context.Context, req *connect.Request[endpoints.ExplainQueryRequest]) (*connect.Response[endpoints.ExplainQueryResponse], error) {
	return c.explainQuery.CallUnary(ctx, req)
}

// GetLogs calls api.proto.service.ManagementService.GetLogs.
func (c *managementServiceClient) GetLogs(ctx context.Context, req *connect.Request[endpoints.GetLogsRequest]) (*connect.Response[endpoints.GetLogsResponse], error) {
	return c.getLogs.CallUnary(ctx, req)
}

// TuneDatabase calls api.proto.service.ManagementService.TuneDatabase.
func (c *managementServiceClient) TuneDatabase(ctx context.Context, req *connect.Request[endpoints.TuneDatabaseRequest]) (*connect.Response[endpoints.TuneDatabaseResponse], error) {
	return c.tuneDatabase.CallUnary(ctx, req)
}

// ApplyTuning calls api.proto.service.ManagementService.ApplyTuning.
func (c *managementServiceClient) ApplyTuning(ctx context.Context, req *connect.Request[endpoints.ApplyTuningRequest]) (*connect.Response[endpoints.ApplyTuningResponse], error) {
	return c.applyTuning.CallUnary(ctx, req)
}

// GetAgentInfo calls api.proto.service.ManagementService.GetAgentInfo.
func (c *managementServiceClient) GetAgentInfo(ctx context.Context, req *connect.Request[endpoints.GetAgentInfoRequest]) (*connect.Response[endpoints.GetAgentInfoResponse], error) {
	return c.getAgentInfo.CallUnary(ctx, req)
}

// GetAvailableVersions calls api.proto.service.ManagementService.GetAvailableVersions.
func (c *managementServiceClient) GetAvailableVersions(ctx context.Context, req *connect.Request[endpoints.GetAvailableVersionsRequest]) (*connect.Response[endpoints.GetAvailableVersionsResponse], error) {
	return c.getAvailableVersions.CallUnary(ctx, req)
}

// Login calls api.proto.service.ManagementService.Login.
func (c *managementServiceClient) Login(ctx context.Context, req *connect.Request[endpoints.LoginRequest]) (*connect.Response[endpoints.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// CreateUser calls api.proto.service.ManagementService.CreateUser.
func (c *managementServiceClient) CreateUser(ctx context.Context, req *connect.Request[endpoints.CreateUserRequest]) (*connect.Response[endpoints.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// GetServerInfo calls api.proto.service.ManagementService.GetServerInfo.
func (c *managementServiceClient) GetServerInfo(ctx context.Context, req *connect.Request[endpoints.GetServerInfoRequest]) (*connect.Response[endpoints.GetServerInfoResponse], error) {
	return c.getServerInfo.CallUnary(ctx, req)
}

// GetPostgresInsights calls api.proto.service.ManagementService.GetPostgresInsights.
func (c *managementServiceClient) GetPostgresInsights(ctx context.Context, req *connect.Request[endpoints.GetBackendPostgresInsightsRequest]) (*connect.Response[endpoints.GetBackendPostgresInsightsResponse], error) {
	return c.getPostgresInsights.CallUnary(ctx, req)
}

// RestartBackendService calls api.proto.service.ManagementService.RestartBackendService.
func (c *managementServiceClient) RestartBackendService(ctx context.Context, req *connect.Request[endpoints.RestartBackendServiceRequest]) (*connect.Response[endpoints.RestartBackendServiceResponse], error) {
	return c.restartBackendService.CallUnary(ctx, req)
}

// ShutdownBackend calls api.proto.service.ManagementService.ShutdownBackend.
func (c *managementServiceClient) ShutdownBackend(ctx context.Context, req *connect.Request[endpoints.ShutdownBackendRequest]) (*connect.Response[endpoints.ShutdownBackendResponse], error) {
	return c.shutdownBackend.CallUnary(ctx, req)
}

// ManagementServiceHandler is an implementation of the api.proto.service.ManagementService service.
type ManagementServiceHandler interface {
	// Projects management
	ListProjects(context.Context, *connect.Request[endpoints.ListProjectsRequest]) (*connect.Response[endpoints.ListProjectsResponse], error)
	CreateProject(context.Context, *connect.Request[endpoints.CreateProjectRequest]) (*connect.Response[endpoints.CreateProjectResponse], error)
	DeleteProject(context.Context, *connect.Request[endpoints.DeleteProjectRequest]) (*connect.Response[endpoints.DeleteProjectResponse], error)
	// Proxies management
	AddProxy(context.Context, *connect.Request[endpoints.AddProxyRequest]) (*connect.Response[endpoints.AddProxyResponse], error)
	RemoveProxy(context.Context, *connect.Request[endpoints.RemoveProxyRequest]) (*connect.Response[endpoints.RemoveProxyResponse], error)
	UpdateProxy(context.Context, *connect.Request[endpoints.UpdateProxyRequest]) (*connect.Response[endpoints.UpdateProxyResponse], error)
	// GetStatus returns the current status of all backends and global metrics.
	GetStatus(context.Context, *connect.Request[endpoints.GetStatusRequest]) (*connect.Response[endpoints.GetStatusResponse], error)
	// StreamStatus pushes status updates for as long as the client is connected.
	//
	// Replaces polling GetStatus on a timer. The dashboard re-fetched the entire
	// payload — every backend, twenty top queries with full SQL text, topology,
	// system metrics — on a fixed interval whether anything had changed or not,
	// per connected dashboard. Read-only, same as GetStatus.
	StreamStatus(context.Context, *connect.Request[endpoints.StreamStatusRequest], *connect.ServerStream[endpoints.GetStatusResponse]) error
	// AddBackend adds a new backend to the pool.
	AddBackend(context.Context, *connect.Request[endpoints.AddBackendRequest]) (*connect.Response[endpoints.AddBackendResponse], error)
	// RemoveBackend removes a backend from the pool.
	RemoveBackend(context.Context, *connect.Request[endpoints.RemoveBackendRequest]) (*connect.Response[endpoints.RemoveBackendResponse], error)
	// UpdateBackend updates an existing backend configuration.
	UpdateBackend(context.Context, *connect.Request[endpoints.UpdateBackendRequest]) (*connect.Response[endpoints.UpdateBackendResponse], error)
	// ProvisionReplica provisions a new replica from a source.
	ProvisionReplica(context.Context, *connect.Request[endpoints.ProvisionReplicaRequest], *connect.ServerStream[endpoints.ProvisionProgress]) error
	// ValidateBackend checks if a backend is accessible.
	ValidateBackend(context.Context, *connect.Request[endpoints.ValidateBackendRequest]) (*connect.Response[endpoints.ValidateBackendResponse], error)
	// StreamLogs returns a real-time stream of logs.
	StreamLogs(context.Context, *connect.Request[endpoints.StreamLogsRequest], *connect.ServerStream[domain.LogEntry]) error
	// InitializeNode initializes a database on a clean host via Agent.
	InitializeNode(context.Context, *connect.Request[endpoints.InitializeNodeRequest], *connect.ServerStream[endpoints.InitializeNodeProgress]) error
	// InstallNode installs the database software on a clean host via Agent.
	InstallNode(context.Context, *connect.Request[endpoints.InstallNodeRequest], *connect.ServerStream[endpoints.InstallNodeProgress]) error
	// BackupBackend triggers a database backup on a backend via Agent.
	BackupBackend(context.Context, *connect.Request[endpoints.BackupBackendRequest], *connect.ServerStream[endpoints.BackupBackendProgress]) error
	// RestoreBackend triggers a database restore on a backend via Agent.
	RestoreBackend(context.Context, *connect.Request[endpoints.RestoreBackendRequest], *connect.ServerStream[endpoints.RestoreBackendProgress]) error
	// PromoteBackend promotes a replica to primary.
	PromoteBackend(context.Context, *connect.Request[endpoints.PromoteBackendRequest]) (*connect.Response[endpoints.PromoteBackendResponse], error)
	// GetMetricsHistory returns historical metrics.
	GetMetricsHistory(context.Context, *connect.Request[endpoints.GetMetricsHistoryRequest]) (*connect.Response[endpoints.GetMetricsHistoryResponse], error)
	// GetTopQueriesHistory returns historical top queries.
	GetTopQueriesHistory(context.Context, *connect.Request[endpoints.GetTopQueriesHistoryRequest]) (*connect.Response[endpoints.GetTopQueriesHistoryResponse], error)
	// SetClusterConfig updates configuration across the cluster.
	SetClusterConfig(context.Context, *connect.Request[endpoints.SetClusterConfigRequest]) (*connect.Response[endpoints.SetClusterConfigResponse], error)
	// GetClusterConfig returns the current cluster configuration.
	GetClusterConfig(context.Context, *connect.Request[endpoints.GetClusterConfigRequest]) (*connect.Response[endpoints.GetClusterConfigResponse], error)
	// DiscoverCluster auto-discovers and adds all nodes in a cluster.
	DiscoverCluster(context.Context, *connect.Request[endpoints.DiscoverClusterRequest]) (*connect.Response[endpoints.DiscoverClusterResponse], error)
	// VacuumBackend triggers a VACUUM operation on a backend via Agent.
	VacuumBackend(context.Context, *connect.Request[endpoints.VacuumBackendRequest], *connect.ServerStream[endpoints.VacuumBackendProgress]) error
	// ExplainQuery analyzes a SQL query.
	ExplainQuery(context.Context, *connect.Request[endpoints.ExplainQueryRequest]) (*connect.Response[endpoints.ExplainQueryResponse], error)
	// GetLogs returns historical logs with filtering and pagination.
	GetLogs(context.Context, *connect.Request[endpoints.GetLogsRequest]) (*connect.Response[endpoints.GetLogsResponse], error)
	// TuneDatabase provides tuning recommendations based on system resources.
	TuneDatabase(context.Context, *connect.Request[endpoints.TuneDatabaseRequest]) (*connect.Response[endpoints.TuneDatabaseResponse], error)
	// ApplyTuning applies a tuning suggestion to a backend.
	ApplyTuning(context.Context, *connect.Request[endpoints.ApplyTuningRequest]) (*connect.Response[endpoints.ApplyTuningResponse], error)
	// GetAgentInfo fetches system info from a Pontus Agent.
	GetAgentInfo(context.Context, *connect.Request[endpoints.GetAgentInfoRequest]) (*connect.Response[endpoints.GetAgentInfoResponse], error)
	// GetAvailableVersions returns all supported PostgreSQL versions.
	GetAvailableVersions(context.Context, *connect.Request[endpoints.GetAvailableVersionsRequest]) (*connect.Response[endpoints.GetAvailableVersionsResponse], error)
	// Login authenticates a user and returns a token.
	Login(context.Context, *connect.Request[endpoints.LoginRequest]) (*connect.Response[endpoints.LoginResponse], error)
	// CreateUser creates a new management user.
	CreateUser(context.Context, *connect.Request[endpoints.CreateUserRequest]) (*connect.Response[endpoints.CreateUserResponse], error)
	// GetServerInfo returns information about the Pontus server.
	GetServerInfo(context.Context, *connect.Request[endpoints.GetServerInfoRequest]) (*connect.Response[endpoints.GetServerInfoResponse], error)
	// GetPostgresInsights retrieves database-specific insights for a backend.
	GetPostgresInsights(context.Context, *connect.Request[endpoints.GetBackendPostgresInsightsRequest]) (*connect.Response[endpoints.GetBackendPostgresInsightsResponse], error)
	// RestartBackendService restarts the database service on a backend via Agent.
	RestartBackendService(context.Context, *connect.Request[endpoints.RestartBackendServiceRequest]) (*connect.Response[endpoints.RestartBackendServiceResponse], error)
	// ShutdownBackend shuts down the database on a backend via Agent.
	ShutdownBackend(context.Context, *connect.Request[endpoints.ShutdownBackendRequest]) (*connect.Response[endpoints.ShutdownBackendResponse], error)
}

// NewManagementServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewManagementServiceHandler(svc ManagementServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	managementServiceMethods := service.File_api_proto_service_management_proto.Services().ByName("ManagementService").Methods()
	managementServiceListProjectsHandler := connect.NewUnaryHandler(
		ManagementServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(managementServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceCreateProjectHandler := connect.NewUnaryHandler(
		ManagementServiceCreateProjectProcedure,
		svc.CreateProject,
		connect.WithSchema(managementServiceMethods.ByName("CreateProject")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceDeleteProjectHandler := connect.NewUnaryHandler(
		ManagementServiceDeleteProjectProcedure,
		svc.DeleteProject,
		connect.WithSchema(managementServiceMethods.ByName("DeleteProject")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceAddProxyHandler := connect.NewUnaryHandler(
		ManagementServiceAddProxyProcedure,
		svc.AddProxy,
		connect.WithSchema(managementServiceMethods.ByName("AddProxy")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceRemoveProxyHandler := connect.NewUnaryHandler(
		ManagementServiceRemoveProxyProcedure,
		svc.RemoveProxy,
		connect.WithSchema(managementServiceMethods.ByName("RemoveProxy")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceUpdateProxyHandler := connect.NewUnaryHandler(
		ManagementServiceUpdateProxyProcedure,
		svc.UpdateProxy,
		connect.WithSchema(managementServiceMethods.ByName("UpdateProxy")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceGetStatusHandler := connect.NewUnaryHandler(
		ManagementServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(managementServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceStreamStatusHandler := connect.NewServerStreamHandler(
		ManagementServiceStreamStatusProcedure,
		svc.StreamStatus,
		connect.WithSchema(managementServiceMethods.ByName("StreamStatus")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceAddBackendHandler := connect.NewUnaryHandler(
		ManagementServiceAddBackendProcedure,
		svc.AddBackend,
		connect.WithSchema(managementServiceMethods.ByName("AddBackend")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceRemoveBackendHandler := connect.NewUnaryHandler(
		ManagementServiceRemoveBackendProcedure,
		svc.RemoveBackend,
		connect.WithSchema(managementServiceMethods.ByName("RemoveBackend")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceUpdateBackendHandler := connect.NewUnaryHandler(
		ManagementServiceUpdateBackendProcedure,
		svc.UpdateBackend,
		connect.WithSchema(managementServiceMethods.ByName("UpdateBackend")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceProvisionReplicaHandler := connect.NewServerStreamHandler(
		ManagementServiceProvisionReplicaProcedure,
		svc.ProvisionReplica,
		connect.WithSchema(managementServiceMethods.ByName("ProvisionReplica")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceValidateBackendHandler := connect.NewUnaryHandler(
		ManagementServiceValidateBackendProcedure,
		svc.ValidateBackend,
		connect.WithSchema(managementServiceMethods.ByName("ValidateBackend")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceStreamLogsHandler := connect.NewServerStreamHandler(
		ManagementServiceStreamLogsProcedure,
		svc.StreamLogs,
		connect.WithSchema(managementServiceMethods.ByName("StreamLogs")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceInitializeNodeHandler := connect.NewServerStreamHandler(
		ManagementServiceInitializeNodeProcedure,
		svc.InitializeNode,
		connect.WithSchema(managementServiceMethods.ByName("InitializeNode")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceInstallNodeHandler := connect.NewServerStreamHandler(
		ManagementServiceInstallNodeProcedure,
		svc.InstallNode,
		connect.WithSchema(managementServiceMethods.ByName("InstallNode")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceBackupBackendHandler := connect.NewServerStreamHandler(
		ManagementServiceBackupBackendProcedure,
		svc.BackupBackend,
		connect.WithSchema(managementServiceMethods.ByName("BackupBackend")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceRestoreBackendHandler := connect.NewServerStreamHandler(
		ManagementServiceRestoreBackendProcedure,
		svc.RestoreBackend,
		connect.WithSchema(managementServiceMethods.ByName("RestoreBackend")),
		connect.WithHandlerOptions(opts...),
	)
	managementServicePromoteBackendHandler := connect.NewUnaryHandler(
		ManagementServicePromoteBackendProcedure,
		svc.PromoteBackend,
		connect.WithSchema(managementServiceMethods.ByName("PromoteBackend")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceGetMetricsHistoryHandler := connect.NewUnaryHandler(
		ManagementServiceGetMetricsHistoryProcedure,
		svc.GetMetricsHistory,
		connect.WithSchema(managementServiceMethods.ByName("GetMetricsHistory")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceGetTopQueriesHistoryHandler := connect.NewUnaryHandler(
		ManagementServiceGetTopQueriesHistoryProcedure,
		svc.GetTopQueriesHistory,
		connect.WithSchema(managementServiceMethods.ByName("GetTopQueriesHistory")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceSetClusterConfigHandler := connect.NewUnaryHandler(
		ManagementServiceSetClusterConfigProcedure,
		svc.SetClusterConfig,
		connect.WithSchema(managementServiceMethods.ByName("SetClusterConfig")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceGetClusterConfigHandler := connect.NewUnaryHandler(
		ManagementServiceGetClusterConfigProcedure,
		svc.GetClusterConfig,
		connect.WithSchema(managementServiceMethods.ByName("GetClusterConfig")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceDiscoverClusterHandler := connect.NewUnaryHandler(
		ManagementServiceDiscoverClusterProcedure,
		svc.DiscoverCluster,
		connect.WithSchema(managementServiceMethods.ByName("DiscoverCluster")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceVacuumBackendHandler := connect.NewServerStreamHandler(
		ManagementServiceVacuumBackendProcedure,
		svc.VacuumBackend,
		connect.WithSchema(managementServiceMethods.ByName("VacuumBackend")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceExplainQueryHandler := connect.NewUnaryHandler(
		ManagementServiceExplainQueryProcedure,
		svc.ExplainQuery,
		connect.WithSchema(managementServiceMethods.ByName("ExplainQuery")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceGetLogsHandler := connect.NewUnaryHandler(
		ManagementServiceGetLogsProcedure,
		svc.GetLogs,
		connect.WithSchema(managementServiceMethods.ByName("GetLogs")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceTuneDatabaseHandler := connect.NewUnaryHandler(
		ManagementServiceTuneDatabaseProcedure,
		svc.TuneDatabase,
		connect.WithSchema(managementServiceMethods.ByName("TuneDatabase")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceApplyTuningHandler := connect.NewUnaryHandler(
		ManagementServiceApplyTuningProcedure,
		svc.ApplyTuning,
		connect.WithSchema(managementServiceMethods.ByName("ApplyTuning")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceGetAgentInfoHandler := connect.NewUnaryHandler(
		ManagementServiceGetAgentInfoProcedure,
		svc.GetAgentInfo,
		connect.WithSchema(managementServiceMethods.ByName("GetAgentInfo")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceGetAvailableVersionsHandler := connect.NewUnaryHandler(
		ManagementServiceGetAvailableVersionsProcedure,
		svc.GetAvailableVersions,
		connect.WithSchema(managementServiceMethods.ByName("GetAvailableVersions")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceLoginHandler := connect.NewUnaryHandler(
		ManagementServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(managementServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceCreateUserHandler := connect.NewUnaryHandler(
		ManagementServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(managementServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceGetServerInfoHandler := connect.NewUnaryHandler(
		ManagementServiceGetServerInfoProcedure,
		svc.GetServerInfo,
		connect.WithSchema(managementServiceMethods.ByName("GetServerInfo")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceGetPostgresInsightsHandler := connect.NewUnaryHandler(
		ManagementServiceGetPostgresInsightsProcedure,
		svc.GetPostgresInsights,
		connect.WithSchema(managementServiceMethods.ByName("GetPostgresInsights")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceRestartBackendServiceHandler := connect.NewUnaryHandler(
		ManagementServiceRestartBackendServiceProcedure,
		svc.RestartBackendService,
		connect.WithSchema(managementServiceMethods.ByName("RestartBackendService")),
		connect.WithHandlerOptions(opts...),
	)
	managementServiceShutdownBackendHandler := connect.NewUnaryHandler(
		ManagementServiceShutdownBackendProcedure,
		svc.ShutdownBackend,
		connect.WithSchema(managementServiceMethods.ByName("ShutdownBackend")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.proto.service.ManagementService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ManagementServiceListProjectsProcedure:
			managementServiceListProjectsHandler.ServeHTTP(w, r)
		case ManagementServiceCreateProjectProcedure:
			managementServiceCreateProjectHandler.ServeHTTP(w, r)
		case ManagementServiceDeleteProjectProcedure:
			managementServiceDeleteProjectHandler.ServeHTTP(w, r)
		case ManagementServiceAddProxyProcedure:
			managementServiceAddProxyHandler.ServeHTTP(w, r)
		case ManagementServiceRemoveProxyProcedure:
			managementServiceRemoveProxyHandler.ServeHTTP(w, r)
		case ManagementServiceUpdateProxyProcedure:
			managementServiceUpdateProxyHandler.ServeHTTP(w, r)
		case ManagementServiceGetStatusProcedure:
			managementServiceGetStatusHandler.ServeHTTP(w, r)
		case ManagementServiceStreamStatusProcedure:
			managementServiceStreamStatusHandler.ServeHTTP(w, r)
		case ManagementServiceAddBackendProcedure:
			managementServiceAddBackendHandler.ServeHTTP(w, r)
		case ManagementServiceRemoveBackendProcedure:
			managementServiceRemoveBackendHandler.ServeHTTP(w, r)
		case ManagementServiceUpdateBackendProcedure:
			managementServiceUpdateBackendHandler.ServeHTTP(w, r)
		case ManagementServiceProvisionReplicaProcedure:
			managementServiceProvisionReplicaHandler.ServeHTTP(w, r)
		case ManagementServiceValidateBackendProcedure:
			managementServiceValidateBackendHandler.ServeHTTP(w, r)
		case ManagementServiceStreamLogsProcedure:
			managementServiceStreamLogsHandler.ServeHTTP(w, r)
		case ManagementServiceInitializeNodeProcedure:
			managementServiceInitializeNodeHandler.ServeHTTP(w, r)
		case ManagementServiceInstallNodeProcedure:
			managementServiceInstallNodeHandler.ServeHTTP(w, r)
		case ManagementServiceBackupBackendProcedure:
			managementServiceBackupBackendHandler.ServeHTTP(w, r)
		case ManagementServiceRestoreBackendProcedure:
			managementServiceRestoreBackendHandler.ServeHTTP(w, r)
		case ManagementServicePromoteBackendProcedure:
			managementServicePromoteBackendHandler.ServeHTTP(w, r)
		case ManagementServiceGetMetricsHistoryProcedure:
			managementServiceGetMetricsHistoryHandler.ServeHTTP(w, r)
		case ManagementServiceGetTopQueriesHistoryProcedure:
			managementServiceGetTopQueriesHistoryHandler.ServeHTTP(w, r)
		case ManagementServiceSetClusterConfigProcedure:
			managementServiceSetClusterConfigHandler.ServeHTTP(w, r)
		case ManagementServiceGetClusterConfigProcedure:
			managementServiceGetClusterConfigHandler.ServeHTTP(w, r)
		case ManagementServiceDiscoverClusterProcedure:
			managementServiceDiscoverClusterHandler.ServeHTTP(w, r)
		case ManagementServiceVacuumBackendProcedure:
			managementServiceVacuumBackendHandler.ServeHTTP(w, r)
		case ManagementServiceExplainQueryProcedure:
			managementServiceExplainQueryHandler.ServeHTTP(w, r)
		case ManagementServiceGetLogsProcedure:
			managementServiceGetLogsHandler.ServeHTTP(w, r)
		case ManagementServiceTuneDatabaseProcedure:
			managementServiceTuneDatabaseHandler.ServeHTTP(w, r)
		case ManagementServiceApplyTuningProcedure:
			managementServiceApplyTuningHandler.ServeHTTP(w, r)
		case ManagementServiceGetAgentInfoProcedure:
			managementServiceGetAgentInfoHandler.ServeHTTP(w, r)
		case ManagementServiceGetAvailableVersionsProcedure:
			managementServiceGetAvailableVersionsHandler.ServeHTTP(w, r)
		case ManagementServiceLoginProcedure:
			managementServiceLoginHandler.ServeHTTP(w, r)
		case ManagementServiceCreateUserProcedure:
			managementServiceCreateUserHandler.ServeHTTP(w, r)
		case ManagementServiceGetServerInfoProcedure:
			managementServiceGetServerInfoHandler.ServeHTTP(w, r)
		case ManagementServiceGetPostgresInsightsProcedure:
			managementServiceGetPostgresInsightsHandler.ServeHTTP(w, r)
		case ManagementServiceRestartBackendServiceProcedure:
			managementServiceRestartBackendServiceHandler.ServeHTTP(w, r)
		case ManagementServiceShutdownBackendProcedure:
			managementServiceShutdownBackendHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedManagementServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedManagementServiceHandler struct{}

func (UnimplementedManagementServiceHandler) ListProjects(context.Context, *connect.Request[endpoints.ListProjectsRequest]) (*connect.Response[endpoints.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.ListProjects is not implemented"))
}

func (UnimplementedManagementServiceHandler) CreateProject(context.Context, *connect.Request[endpoints.CreateProjectRequest]) (*connect.Response[endpoints.CreateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.CreateProject is not implemented"))
}

func (UnimplementedManagementServiceHandler) DeleteProject(context.Context, *connect.Request[endpoints.DeleteProjectRequest]) (*connect.Response[endpoints.DeleteProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.DeleteProject is not implemented"))
}

func (UnimplementedManagementServiceHandler) AddProxy(context.Context, *connect.Request[endpoints.AddProxyRequest]) (*connect.Response[endpoints.AddProxyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.AddProxy is not implemented"))
}

func (UnimplementedManagementServiceHandler) RemoveProxy(context.Context, *connect.Request[endpoints.RemoveProxyRequest]) (*connect.Response[endpoints.RemoveProxyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.RemoveProxy is not implemented"))
}

func (UnimplementedManagementServiceHandler) UpdateProxy(context.Context, *connect.Request[endpoints.UpdateProxyRequest]) (*connect.Response[endpoints.UpdateProxyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.UpdateProxy is not implemented"))
}

func (UnimplementedManagementServiceHandler) GetStatus(context.Context, *connect.Request[endpoints.GetStatusRequest]) (*connect.Response[endpoints.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.GetStatus is not implemented"))
}

func (UnimplementedManagementServiceHandler) StreamStatus(context.Context, *connect.Request[endpoints.StreamStatusRequest], *connect.ServerStream[endpoints.GetStatusResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.StreamStatus is not implemented"))
}

func (UnimplementedManagementServiceHandler) AddBackend(context.Context, *connect.Request[endpoints.AddBackendRequest]) (*connect.Response[endpoints.AddBackendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.AddBackend is not implemented"))
}

func (UnimplementedManagementServiceHandler) RemoveBackend(context.Context, *connect.Request[endpoints.RemoveBackendRequest]) (*connect.Response[endpoints.RemoveBackendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.RemoveBackend is not implemented"))
}

func (UnimplementedManagementServiceHandler) UpdateBackend(context.Context, *connect.Request[endpoints.UpdateBackendRequest]) (*connect.Response[endpoints.UpdateBackendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.UpdateBackend is not implemented"))
}

func (UnimplementedManagementServiceHandler) ProvisionReplica(context.Context, *connect.Request[endpoints.ProvisionReplicaRequest], *connect.ServerStream[endpoints.ProvisionProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.ProvisionReplica is not implemented"))
}

func (UnimplementedManagementServiceHandler) ValidateBackend(context.Context, *connect.Request[endpoints.ValidateBackendRequest]) (*connect.Response[endpoints.ValidateBackendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.ValidateBackend is not implemented"))
}

func (UnimplementedManagementServiceHandler) StreamLogs(context.Context, *connect.Request[endpoints.StreamLogsRequest], *connect.ServerStream[domain.LogEntry]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.StreamLogs is not implemented"))
}

func (UnimplementedManagementServiceHandler) InitializeNode(context.Context, *connect.Request[endpoints.InitializeNodeRequest], *connect.ServerStream[endpoints.InitializeNodeProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.InitializeNode is not implemented"))
}

func (UnimplementedManagementServiceHandler) InstallNode(context.Context, *connect.Request[endpoints.InstallNodeRequest], *connect.ServerStream[endpoints.InstallNodeProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.InstallNode is not implemented"))
}

func (UnimplementedManagementServiceHandler) BackupBackend(context.Context, *connect.Request[endpoints.BackupBackendRequest], *connect.ServerStream[endpoints.BackupBackendProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.BackupBackend is not implemented"))
}

func (UnimplementedManagementServiceHandler) RestoreBackend(context.Context, *connect.Request[endpoints.RestoreBackendRequest], *connect.ServerStream[endpoints.RestoreBackendProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.RestoreBackend is not implemented"))
}

func (UnimplementedManagementServiceHandler) PromoteBackend(context.Context, *connect.Request[endpoints.PromoteBackendRequest]) (*connect.Response[endpoints.PromoteBackendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.PromoteBackend is not implemented"))
}

func (UnimplementedManagementServiceHandler) GetMetricsHistory(context.Context, *connect.Request[endpoints.GetMetricsHistoryRequest]) (*connect.Response[endpoints.GetMetricsHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.GetMetricsHistory is not implemented"))
}

func (UnimplementedManagementServiceHandler) GetTopQueriesHistory(context.Context, *connect.Request[endpoints.GetTopQueriesHistoryRequest]) (*connect.Response[endpoints.GetTopQueriesHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.GetTopQueriesHistory is not implemented"))
}

func (UnimplementedManagementServiceHandler) SetClusterConfig(context.Context, *connect.Request[endpoints.SetClusterConfigRequest]) (*connect.Response[endpoints.SetClusterConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.SetClusterConfig is not implemented"))
}

func (UnimplementedManagementServiceHandler) GetClusterConfig(context.Context, *connect.Request[endpoints.GetClusterConfigRequest]) (*connect.Response[endpoints.GetClusterConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.GetClusterConfig is not implemented"))
}

func (UnimplementedManagementServiceHandler) DiscoverCluster(context.Context, *connect.Request[endpoints.DiscoverClusterRequest]) (*connect.Response[endpoints.DiscoverClusterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.DiscoverCluster is not implemented"))
}

func (UnimplementedManagementServiceHandler) VacuumBackend(context.Context, *connect.Request[endpoints.VacuumBackendRequest], *connect.ServerStream[endpoints.VacuumBackendProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.VacuumBackend is not implemented"))
}

func (UnimplementedManagementServiceHandler) ExplainQuery(context.Context, *connect.Request[endpoints.ExplainQueryRequest]) (*connect.Response[endpoints.ExplainQueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.ExplainQuery is not implemented"))
}

func (UnimplementedManagementServiceHandler) GetLogs(context.Context, *connect.Request[endpoints.GetLogsRequest]) (*connect.Response[endpoints.GetLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.GetLogs is not implemented"))
}

func (UnimplementedManagementServiceHandler) TuneDatabase(context.Context, *connect.Request[endpoints.TuneDatabaseRequest]) (*connect.Response[endpoints.TuneDatabaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.TuneDatabase is not implemented"))
}

func (UnimplementedManagementServiceHandler) ApplyTuning(context.Context, *connect.Request[endpoints.ApplyTuningRequest]) (*connect.Response[endpoints.ApplyTuningResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.ApplyTuning is not implemented"))
}

func (UnimplementedManagementServiceHandler) GetAgentInfo(context.Context, *connect.Request[endpoints.GetAgentInfoRequest]) (*connect.Response[endpoints.GetAgentInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.GetAgentInfo is not implemented"))
}

func (UnimplementedManagementServiceHandler) GetAvailableVersions(context.Context, *connect.Request[endpoints.GetAvailableVersionsRequest]) (*connect.Response[endpoints.GetAvailableVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.GetAvailableVersions is not implemented"))
}

func (UnimplementedManagementServiceHandler) Login(context.Context, *connect.Request[endpoints.LoginRequest]) (*connect.Response[endpoints.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.Login is not implemented"))
}

func (UnimplementedManagementServiceHandler) CreateUser(context.Context, *connect.Request[endpoints.CreateUserRequest]) (*connect.Response[endpoints.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.CreateUser is not implemented"))
}

func (UnimplementedManagementServiceHandler) GetServerInfo(context.Context, *connect.Request[endpoints.GetServerInfoRequest]) (*connect.Response[endpoints.GetServerInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.GetServerInfo is not implemented"))
}

func (UnimplementedManagementServiceHandler) GetPostgresInsights(context.Context, *connect.Request[endpoints.GetBackendPostgresInsightsRequest]) (*connect.Response[endpoints.GetBackendPostgresInsightsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.GetPostgresInsights is not implemented"))
}

func (UnimplementedManagementServiceHandler) RestartBackendService(context.Context, *connect.Request[endpoints.RestartBackendServiceRequest]) (*connect.Response[endpoints.RestartBackendServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.RestartBackendService is not implemented"))
}

func (UnimplementedManagementServiceHandler) ShutdownBackend(context.Context, *connect.Request[endpoints.ShutdownBackendRequest]) (*connect.Response[endpoints.ShutdownBackendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.proto.service.ManagementService.ShutdownBackend is not implemented"))
}
