// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/domain/log.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_proto_domain_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_api_proto_domain_log_proto protoreflect.FileDescriptor

const file_api_proto_domain_log_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/domain/log.proto\x12\x10api.proto.domain\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x01\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12J\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2*.api.proto.domain.LogEntry.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B-Z+github.com/gsoultan/pontus/api/proto/domainb\x06proto3"

var (
	file_api_proto_domain_log_proto_rawDescOnce sync.Once
	file_api_proto_domain_log_proto_rawDescData []byte
)

func file_api_proto_domain_log_proto_rawDescGZIP() []byte {
	file_api_proto_domain_log_proto_rawDescOnce.Do(func() {
		file_api_proto_domain_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_domain_log_proto_rawDesc), len(file_api_proto_domain_log_proto_rawDesc)))
	})
	return file_api_proto_domain_log_proto_rawDescData
}

var file_api_proto_domain_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_domain_log_proto_goTypes = []any{
	(*LogEntry)(nil),              // 0: api.proto.domain.LogEntry
	nil,                           // 1: api.proto.domain.LogEntry.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_proto_domain_log_proto_depIdxs = []int32{
	2, // 0: api.proto.domain.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: api.proto.domain.LogEntry.attributes:type_name -> api.proto.domain.LogEntry.AttributesEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_domain_log_proto_init() }
func file_api_proto_domain_log_proto_init() {
	if File_api_proto_domain_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_domain_log_proto_rawDesc), len(file_api_proto_domain_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_domain_log_proto_goTypes,
		DependencyIndexes: file_api_proto_domain_log_proto_depIdxs,
		MessageInfos:      file_api_proto_domain_log_proto_msgTypes,
	}.Build()
	File_api_proto_domain_log_proto = out.File
	file_api_proto_domain_log_proto_goTypes = nil
	file_api_proto_domain_log_proto_depIdxs = nil
}
