// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/domain/metrics.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemMetrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CpuUsagePercent     float32                `protobuf:"fixed32,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	CpuCores            uint32                 `protobuf:"varint,17,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryTotalBytes    uint64                 `protobuf:"varint,2,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	MemoryUsedBytes     uint64                 `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryUsagePercent  float32                `protobuf:"fixed32,4,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	StorageTotalBytes   uint64                 `protobuf:"varint,5,opt,name=storage_total_bytes,json=storageTotalBytes,proto3" json:"storage_total_bytes,omitempty"`
	StorageUsedBytes    uint64                 `protobuf:"varint,6,opt,name=storage_used_bytes,json=storageUsedBytes,proto3" json:"storage_used_bytes,omitempty"`
	StorageUsagePercent float32                `protobuf:"fixed32,7,opt,name=storage_usage_percent,json=storageUsagePercent,proto3" json:"storage_usage_percent,omitempty"`
	Load_1              float32                `protobuf:"fixed32,8,opt,name=load_1,json=load1,proto3" json:"load_1,omitempty"`
	Load_5              float32                `protobuf:"fixed32,9,opt,name=load_5,json=load5,proto3" json:"load_5,omitempty"`
	Load_15             float32                `protobuf:"fixed32,10,opt,name=load_15,json=load15,proto3" json:"load_15,omitempty"`
	Goroutines          uint64                 `protobuf:"varint,14,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	OpenFilesLimit      uint64                 `protobuf:"varint,15,opt,name=open_files_limit,json=openFilesLimit,proto3" json:"open_files_limit,omitempty"`
	MaxProcessesLimit   uint64                 `protobuf:"varint,16,opt,name=max_processes_limit,json=maxProcessesLimit,proto3" json:"max_processes_limit,omitempty"`
	// Advanced metrics
	DiskIo        *DiskMetrics     `protobuf:"bytes,11,opt,name=disk_io,json=diskIo,proto3" json:"disk_io,omitempty"`
	NetworkIo     *NetworkMetrics  `protobuf:"bytes,12,opt,name=network_io,json=networkIo,proto3" json:"network_io,omitempty"`
	DbMetrics     *DatabaseMetrics `protobuf:"bytes,13,opt,name=db_metrics,json=dbMetrics,proto3" json:"db_metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_api_proto_domain_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *SystemMetrics) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *SystemMetrics) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemMetrics) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsagePercent() float32 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *SystemMetrics) GetStorageTotalBytes() uint64 {
	if x != nil {
		return x.StorageTotalBytes
	}
	return 0
}

func (x *SystemMetrics) GetStorageUsedBytes() uint64 {
	if x != nil {
		return x.StorageUsedBytes
	}
	return 0
}

func (x *SystemMetrics) GetStorageUsagePercent() float32 {
	if x != nil {
		return x.StorageUsagePercent
	}
	return 0
}

func (x *SystemMetrics) GetLoad_1() float32 {
	if x != nil {
		return x.Load_1
	}
	return 0
}

func (x *SystemMetrics) GetLoad_5() float32 {
	if x != nil {
		return x.Load_5
	}
	return 0
}

func (x *SystemMetrics) GetLoad_15() float32 {
	if x != nil {
		return x.Load_15
	}
	return 0
}

func (x *SystemMetrics) GetGoroutines() uint64 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *SystemMetrics) GetOpenFilesLimit() uint64 {
	if x != nil {
		return x.OpenFilesLimit
	}
	return 0
}

func (x *SystemMetrics) GetMaxProcessesLimit() uint64 {
	if x != nil {
		return x.MaxProcessesLimit
	}
	return 0
}

func (x *SystemMetrics) GetDiskIo() *DiskMetrics {
	if x != nil {
		return x.DiskIo
	}
	return nil
}

func (x *SystemMetrics) GetNetworkIo() *NetworkMetrics {
	if x != nil {
		return x.NetworkIo
	}
	return nil
}

func (x *SystemMetrics) GetDbMetrics() *DatabaseMetrics {
	if x != nil {
		return x.DbMetrics
	}
	return nil
}

type DiskMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReadBytesPerSec  uint64                 `protobuf:"varint,1,opt,name=read_bytes_per_sec,json=readBytesPerSec,proto3" json:"read_bytes_per_sec,omitempty"`
	WriteBytesPerSec uint64                 `protobuf:"varint,2,opt,name=write_bytes_per_sec,json=writeBytesPerSec,proto3" json:"write_bytes_per_sec,omitempty"`
	ReadCountPerSec  uint64                 `protobuf:"varint,3,opt,name=read_count_per_sec,json=readCountPerSec,proto3" json:"read_count_per_sec,omitempty"`
	WriteCountPerSec uint64                 `protobuf:"varint,4,opt,name=write_count_per_sec,json=writeCountPerSec,proto3" json:"write_count_per_sec,omitempty"`
	IotimeMs         float32                `protobuf:"fixed32,5,opt,name=iotime_ms,json=iotimeMs,proto3" json:"iotime_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_api_proto_domain_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *DiskMetrics) GetReadBytesPerSec() uint64 {
	if x != nil {
		return x.ReadBytesPerSec
	}
	return 0
}

func (x *DiskMetrics) GetWriteBytesPerSec() uint64 {
	if x != nil {
		return x.WriteBytesPerSec
	}
	return 0
}

func (x *DiskMetrics) GetReadCountPerSec() uint64 {
	if x != nil {
		return x.ReadCountPerSec
	}
	return 0
}

func (x *DiskMetrics) GetWriteCountPerSec() uint64 {
	if x != nil {
		return x.WriteCountPerSec
	}
	return 0
}

func (x *DiskMetrics) GetIotimeMs() float32 {
	if x != nil {
		return x.IotimeMs
	}
	return 0
}

type NetworkMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BytesSentPerSec   uint64                 `protobuf:"varint,1,opt,name=bytes_sent_per_sec,json=bytesSentPerSec,proto3" json:"bytes_sent_per_sec,omitempty"`
	BytesRecvPerSec   uint64                 `protobuf:"varint,2,opt,name=bytes_recv_per_sec,json=bytesRecvPerSec,proto3" json:"bytes_recv_per_sec,omitempty"`
	PacketsSentPerSec uint64                 `protobuf:"varint,3,opt,name=packets_sent_per_sec,json=packetsSentPerSec,proto3" json:"packets_sent_per_sec,omitempty"`
	PacketsRecvPerSec uint64                 `protobuf:"varint,4,opt,name=packets_recv_per_sec,json=packetsRecvPerSec,proto3" json:"packets_recv_per_sec,omitempty"`
	ErrIn             uint64                 `protobuf:"varint,5,opt,name=err_in,json=errIn,proto3" json:"err_in,omitempty"`
	ErrOut            uint64                 `protobuf:"varint,6,opt,name=err_out,json=errOut,proto3" json:"err_out,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_api_proto_domain_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkMetrics) GetBytesSentPerSec() uint64 {
	if x != nil {
		return x.BytesSentPerSec
	}
	return 0
}

func (x *NetworkMetrics) GetBytesRecvPerSec() uint64 {
	if x != nil {
		return x.BytesRecvPerSec
	}
	return 0
}

func (x *NetworkMetrics) GetPacketsSentPerSec() uint64 {
	if x != nil {
		return x.PacketsSentPerSec
	}
	return 0
}

func (x *NetworkMetrics) GetPacketsRecvPerSec() uint64 {
	if x != nil {
		return x.PacketsRecvPerSec
	}
	return 0
}

func (x *NetworkMetrics) GetErrIn() uint64 {
	if x != nil {
		return x.ErrIn
	}
	return 0
}

func (x *NetworkMetrics) GetErrOut() uint64 {
	if x != nil {
		return x.ErrOut
	}
	return 0
}

type DatabaseMetrics struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ActiveBackends         int64                  `protobuf:"varint,1,opt,name=active_backends,json=activeBackends,proto3" json:"active_backends,omitempty"`
	MaxBackends            int64                  `protobuf:"varint,2,opt,name=max_backends,json=maxBackends,proto3" json:"max_backends,omitempty"`
	TransactionsCommitted  int64                  `protobuf:"varint,3,opt,name=transactions_committed,json=transactionsCommitted,proto3" json:"transactions_committed,omitempty"`
	TransactionsRolledBack int64                  `protobuf:"varint,4,opt,name=transactions_rolled_back,json=transactionsRolledBack,proto3" json:"transactions_rolled_back,omitempty"`
	BlocksRead             int64                  `protobuf:"varint,5,opt,name=blocks_read,json=blocksRead,proto3" json:"blocks_read,omitempty"`
	BlocksHit              int64                  `protobuf:"varint,6,opt,name=blocks_hit,json=blocksHit,proto3" json:"blocks_hit,omitempty"`
	CacheHitRatio          float32                `protobuf:"fixed32,7,opt,name=cache_hit_ratio,json=cacheHitRatio,proto3" json:"cache_hit_ratio,omitempty"`
	Conflicts              int64                  `protobuf:"varint,8,opt,name=conflicts,proto3" json:"conflicts,omitempty"`
	Deadlocks              int64                  `protobuf:"varint,9,opt,name=deadlocks,proto3" json:"deadlocks,omitempty"`
	ReplicationLagBytes    int64                  `protobuf:"varint,10,opt,name=replication_lag_bytes,json=replicationLagBytes,proto3" json:"replication_lag_bytes,omitempty"`
	IsRecovery             bool                   `protobuf:"varint,11,opt,name=is_recovery,json=isRecovery,proto3" json:"is_recovery,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DatabaseMetrics) Reset() {
	*x = DatabaseMetrics{}
	mi := &file_api_proto_domain_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseMetrics) ProtoMessage() {}

func (x *DatabaseMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseMetrics.ProtoReflect.Descriptor instead.
func (*DatabaseMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *DatabaseMetrics) GetActiveBackends() int64 {
	if x != nil {
		return x.ActiveBackends
	}
	return 0
}

func (x *DatabaseMetrics) GetMaxBackends() int64 {
	if x != nil {
		return x.MaxBackends
	}
	return 0
}

func (x *DatabaseMetrics) GetTransactionsCommitted() int64 {
	if x != nil {
		return x.TransactionsCommitted
	}
	return 0
}

func (x *DatabaseMetrics) GetTransactionsRolledBack() int64 {
	if x != nil {
		return x.TransactionsRolledBack
	}
	return 0
}

func (x *DatabaseMetrics) GetBlocksRead() int64 {
	if x != nil {
		return x.BlocksRead
	}
	return 0
}

func (x *DatabaseMetrics) GetBlocksHit() int64 {
	if x != nil {
		return x.BlocksHit
	}
	return 0
}

func (x *DatabaseMetrics) GetCacheHitRatio() float32 {
	if x != nil {
		return x.CacheHitRatio
	}
	return 0
}

func (x *DatabaseMetrics) GetConflicts() int64 {
	if x != nil {
		return x.Conflicts
	}
	return 0
}

func (x *DatabaseMetrics) GetDeadlocks() int64 {
	if x != nil {
		return x.Deadlocks
	}
	return 0
}

func (x *DatabaseMetrics) GetReplicationLagBytes() int64 {
	if x != nil {
		return x.ReplicationLagBytes
	}
	return 0
}

func (x *DatabaseMetrics) GetIsRecovery() bool {
	if x != nil {
		return x.IsRecovery
	}
	return false
}

var File_api_proto_domain_metrics_proto protoreflect.FileDescriptor

const file_api_proto_domain_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/domain/metrics.proto\x12\x10api.proto.domain\"\xf2\x05\n" +
	"\rSystemMetrics\x12*\n" +
	"\x11cpu_usage_percent\x18\x01 \x01(\x02R\x0fcpuUsagePercent\x12\x1b\n" +
	"\tcpu_cores\x18\x11 \x01(\rR\bcpuCores\x12,\n" +
	"\x12memory_total_bytes\x18\x02 \x01(\x04R\x10memoryTotalBytes\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x04R\x0fmemoryUsedBytes\x120\n" +
	"\x14memory_usage_percent\x18\x04 \x01(\x02R\x12memoryUsagePercent\x12.\n" +
	"\x13storage_total_bytes\x18\x05 \x01(\x04R\x11storageTotalBytes\x12,\n" +
	"\x12storage_used_bytes\x18\x06 \x01(\x04R\x10storageUsedBytes\x122\n" +
	"\x15storage_usage_percent\x18\a \x01(\x02R\x13storageUsagePercent\x12\x15\n" +
	"\x06load_1\x18\b \x01(\x02R\x05load1\x12\x15\n" +
	"\x06load_5\x18\t \x01(\x02R\x05load5\x12\x17\n" +
	"\aload_15\x18\n" +
	" \x01(\x02R\x06load15\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x0e \x01(\x04R\n" +
	"goroutines\x12(\n" +
	"\x10open_files_limit\x18\x0f \x01(\x04R\x0eopenFilesLimit\x12.\n" +
	"\x13max_processes_limit\x18\x10 \x01(\x04R\x11maxProcessesLimit\x126\n" +
	"\adisk_io\x18\v \x01(\v2\x1d.api.proto.domain.DiskMetricsR\x06diskIo\x12?\n" +
	"\n" +
	"network_io\x18\f \x01(\v2 .api.proto.domain.NetworkMetricsR\tnetworkIo\x12@\n" +
	"\n" +
	"db_metrics\x18\r \x01(\v2!.api.proto.domain.DatabaseMetricsR\tdbMetrics\"\xe2\x01\n" +
	"\vDiskMetrics\x12+\n" +
	"\x12read_bytes_per_sec\x18\x01 \x01(\x04R\x0freadBytesPerSec\x12-\n" +
	"\x13write_bytes_per_sec\x18\x02 \x01(\x04R\x10writeBytesPerSec\x12+\n" +
	"\x12read_count_per_sec\x18\x03 \x01(\x04R\x0freadCountPerSec\x12-\n" +
	"\x13write_count_per_sec\x18\x04 \x01(\x04R\x10writeCountPerSec\x12\x1b\n" +
	"\tiotime_ms\x18\x05 \x01(\x02R\biotimeMs\"\xfc\x01\n" +
	"\x0eNetworkMetrics\x12+\n" +
	"\x12bytes_sent_per_sec\x18\x01 \x01(\x04R\x0fbytesSentPerSec\x12+\n" +
	"\x12bytes_recv_per_sec\x18\x02 \x01(\x04R\x0fbytesRecvPerSec\x12/\n" +
	"\x14packets_sent_per_sec\x18\x03 \x01(\x04R\x11packetsSentPerSec\x12/\n" +
	"\x14packets_recv_per_sec\x18\x04 \x01(\x04R\x11packetsRecvPerSec\x12\x15\n" +
	"\x06err_in\x18\x05 \x01(\x04R\x05errIn\x12\x17\n" +
	"\aerr_out\x18\x06 \x01(\x04R\x06errOut\"\xc7\x03\n" +
	"\x0fDatabaseMetrics\x12'\n" +
	"\x0factive_backends\x18\x01 \x01(\x03R\x0eactiveBackends\x12!\n" +
	"\fmax_backends\x18\x02 \x01(\x03R\vmaxBackends\x125\n" +
	"\x16transactions_committed\x18\x03 \x01(\x03R\x15transactionsCommitted\x128\n" +
	"\x18transactions_rolled_back\x18\x04 \x01(\x03R\x16transactionsRolledBack\x12\x1f\n" +
	"\vblocks_read\x18\x05 \x01(\x03R\n" +
	"blocksRead\x12\x1d\n" +
	"\n" +
	"blocks_hit\x18\x06 \x01(\x03R\tblocksHit\x12&\n" +
	"\x0fcache_hit_ratio\x18\a \x01(\x02R\rcacheHitRatio\x12\x1c\n" +
	"\tconflicts\x18\b \x01(\x03R\tconflicts\x12\x1c\n" +
	"\tdeadlocks\x18\t \x01(\x03R\tdeadlocks\x122\n" +
	"\x15replication_lag_bytes\x18\n" +
	" \x01(\x03R\x13replicationLagBytes\x12\x1f\n" +
	"\vis_recovery\x18\v \x01(\bR\n" +
	"isRecoveryB-Z+github.com/gsoultan/pontus/api/proto/domainb\x06proto3"

var (
	file_api_proto_domain_metrics_proto_rawDescOnce sync.Once
	file_api_proto_domain_metrics_proto_rawDescData []byte
)

func file_api_proto_domain_metrics_proto_rawDescGZIP() []byte {
	file_api_proto_domain_metrics_proto_rawDescOnce.Do(func() {
		file_api_proto_domain_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_domain_metrics_proto_rawDesc), len(file_api_proto_domain_metrics_proto_rawDesc)))
	})
	return file_api_proto_domain_metrics_proto_rawDescData
}

var file_api_proto_domain_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_domain_metrics_proto_goTypes = []any{
	(*SystemMetrics)(nil),   // 0: api.proto.domain.SystemMetrics
	(*DiskMetrics)(nil),     // 1: api.proto.domain.DiskMetrics
	(*NetworkMetrics)(nil),  // 2: api.proto.domain.NetworkMetrics
	(*DatabaseMetrics)(nil), // 3: api.proto.domain.DatabaseMetrics
}
var file_api_proto_domain_metrics_proto_depIdxs = []int32{
	1, // 0: api.proto.domain.SystemMetrics.disk_io:type_name -> api.proto.domain.DiskMetrics
	2, // 1: api.proto.domain.SystemMetrics.network_io:type_name -> api.proto.domain.NetworkMetrics
	3, // 2: api.proto.domain.SystemMetrics.db_metrics:type_name -> api.proto.domain.DatabaseMetrics
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_domain_metrics_proto_init() }
func file_api_proto_domain_metrics_proto_init() {
	if File_api_proto_domain_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_domain_metrics_proto_rawDesc), len(file_api_proto_domain_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_domain_metrics_proto_goTypes,
		DependencyIndexes: file_api_proto_domain_metrics_proto_depIdxs,
		MessageInfos:      file_api_proto_domain_metrics_proto_msgTypes,
	}.Build()
	File_api_proto_domain_metrics_proto = out.File
	file_api_proto_domain_metrics_proto_goTypes = nil
	file_api_proto_domain_metrics_proto_depIdxs = nil
}
