// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/domain/project.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // "postgres" or "mysql"
	Proxies       []*ProxyConfig         `protobuf:"bytes,4,rep,name=proxies,proto3" json:"proxies,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_api_proto_domain_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Project) GetProxies() []*ProxyConfig {
	if x != nil {
		return x.Proxies
	}
	return nil
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ProxyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Backends      []*BackendConfig       `protobuf:"bytes,4,rep,name=backends,proto3" json:"backends,omitempty"`
	Balancer      string                 `protobuf:"bytes,5,opt,name=balancer,proto3" json:"balancer,omitempty"`
	MaxConns      int32                  `protobuf:"varint,6,opt,name=max_conns,json=maxConns,proto3" json:"max_conns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyConfig) Reset() {
	*x = ProxyConfig{}
	mi := &file_api_proto_domain_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConfig) ProtoMessage() {}

func (x *ProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConfig.ProtoReflect.Descriptor instead.
func (*ProxyConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProxyConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProxyConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProxyConfig) GetBackends() []*BackendConfig {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *ProxyConfig) GetBalancer() string {
	if x != nil {
		return x.Balancer
	}
	return ""
}

func (x *ProxyConfig) GetMaxConns() int32 {
	if x != nil {
		return x.MaxConns
	}
	return 0
}

type BackendConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Address        string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Zone           string                 `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	Role           string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // "primary" or "replica"
	Weight         int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	ManagedByAgent bool                   `protobuf:"varint,5,opt,name=managed_by_agent,json=managedByAgent,proto3" json:"managed_by_agent,omitempty"`
	AgentAddress   string                 `protobuf:"bytes,6,opt,name=agent_address,json=agentAddress,proto3" json:"agent_address,omitempty"`
	AgentToken     string                 `protobuf:"bytes,8,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	AgentConfig    *AgentDatabaseConfig   `protobuf:"bytes,7,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackendConfig) Reset() {
	*x = BackendConfig{}
	mi := &file_api_proto_domain_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendConfig) ProtoMessage() {}

func (x *BackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendConfig.ProtoReflect.Descriptor instead.
func (*BackendConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_project_proto_rawDescGZIP(), []int{2}
}

func (x *BackendConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BackendConfig) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *BackendConfig) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *BackendConfig) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *BackendConfig) GetManagedByAgent() bool {
	if x != nil {
		return x.ManagedByAgent
	}
	return false
}

func (x *BackendConfig) GetAgentAddress() string {
	if x != nil {
		return x.AgentAddress
	}
	return ""
}

func (x *BackendConfig) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

func (x *BackendConfig) GetAgentConfig() *AgentDatabaseConfig {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

type AgentDatabaseConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DataDirectory    string                 `protobuf:"bytes,1,opt,name=data_directory,json=dataDirectory,proto3" json:"data_directory,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	InitialDatabase  string                 `protobuf:"bytes,3,opt,name=initial_database,json=initialDatabase,proto3" json:"initial_database,omitempty"`
	InitialUser      string                 `protobuf:"bytes,4,opt,name=initial_user,json=initialUser,proto3" json:"initial_user,omitempty"`
	InitialPassword  string                 `protobuf:"bytes,5,opt,name=initial_password,json=initialPassword,proto3" json:"initial_password,omitempty"`
	InstallIfMissing bool                   `protobuf:"varint,6,opt,name=install_if_missing,json=installIfMissing,proto3" json:"install_if_missing,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentDatabaseConfig) Reset() {
	*x = AgentDatabaseConfig{}
	mi := &file_api_proto_domain_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDatabaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDatabaseConfig) ProtoMessage() {}

func (x *AgentDatabaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDatabaseConfig.ProtoReflect.Descriptor instead.
func (*AgentDatabaseConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_project_proto_rawDescGZIP(), []int{3}
}

func (x *AgentDatabaseConfig) GetDataDirectory() string {
	if x != nil {
		return x.DataDirectory
	}
	return ""
}

func (x *AgentDatabaseConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentDatabaseConfig) GetInitialDatabase() string {
	if x != nil {
		return x.InitialDatabase
	}
	return ""
}

func (x *AgentDatabaseConfig) GetInitialUser() string {
	if x != nil {
		return x.InitialUser
	}
	return ""
}

func (x *AgentDatabaseConfig) GetInitialPassword() string {
	if x != nil {
		return x.InitialPassword
	}
	return ""
}

func (x *AgentDatabaseConfig) GetInstallIfMissing() bool {
	if x != nil {
		return x.InstallIfMissing
	}
	return false
}

var File_api_proto_domain_project_proto protoreflect.FileDescriptor

const file_api_proto_domain_project_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/domain/project.proto\x12\x10api.proto.domain\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x127\n" +
	"\aproxies\x18\x04 \x03(\v2\x1d.api.proto.domain.ProxyConfigR\aproxies\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc1\x01\n" +
	"\vProxyConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12;\n" +
	"\bbackends\x18\x04 \x03(\v2\x1f.api.proto.domain.BackendConfigR\bbackends\x12\x1a\n" +
	"\bbalancer\x18\x05 \x01(\tR\bbalancer\x12\x1b\n" +
	"\tmax_conns\x18\x06 \x01(\x05R\bmaxConns\"\xa3\x02\n" +
	"\rBackendConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04zone\x18\x04 \x01(\tR\x04zone\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\x12(\n" +
	"\x10managed_by_agent\x18\x05 \x01(\bR\x0emanagedByAgent\x12#\n" +
	"\ragent_address\x18\x06 \x01(\tR\fagentAddress\x12\x1f\n" +
	"\vagent_token\x18\b \x01(\tR\n" +
	"agentToken\x12H\n" +
	"\fagent_config\x18\a \x01(\v2%.api.proto.domain.AgentDatabaseConfigR\vagentConfig\"\xfd\x01\n" +
	"\x13AgentDatabaseConfig\x12%\n" +
	"\x0edata_directory\x18\x01 \x01(\tR\rdataDirectory\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10initial_database\x18\x03 \x01(\tR\x0finitialDatabase\x12!\n" +
	"\finitial_user\x18\x04 \x01(\tR\vinitialUser\x12)\n" +
	"\x10initial_password\x18\x05 \x01(\tR\x0finitialPassword\x12,\n" +
	"\x12install_if_missing\x18\x06 \x01(\bR\x10installIfMissingB-Z+github.com/gsoultan/pontus/api/proto/domainb\x06proto3"

var (
	file_api_proto_domain_project_proto_rawDescOnce sync.Once
	file_api_proto_domain_project_proto_rawDescData []byte
)

func file_api_proto_domain_project_proto_rawDescGZIP() []byte {
	file_api_proto_domain_project_proto_rawDescOnce.Do(func() {
		file_api_proto_domain_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_domain_project_proto_rawDesc), len(file_api_proto_domain_project_proto_rawDesc)))
	})
	return file_api_proto_domain_project_proto_rawDescData
}

var file_api_proto_domain_project_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_domain_project_proto_goTypes = []any{
	(*Project)(nil),               // 0: api.proto.domain.Project
	(*ProxyConfig)(nil),           // 1: api.proto.domain.ProxyConfig
	(*BackendConfig)(nil),         // 2: api.proto.domain.BackendConfig
	(*AgentDatabaseConfig)(nil),   // 3: api.proto.domain.AgentDatabaseConfig
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_api_proto_domain_project_proto_depIdxs = []int32{
	1, // 0: api.proto.domain.Project.proxies:type_name -> api.proto.domain.ProxyConfig
	4, // 1: api.proto.domain.Project.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: api.proto.domain.ProxyConfig.backends:type_name -> api.proto.domain.BackendConfig
	3, // 3: api.proto.domain.BackendConfig.agent_config:type_name -> api.proto.domain.AgentDatabaseConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_domain_project_proto_init() }
func file_api_proto_domain_project_proto_init() {
	if File_api_proto_domain_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_domain_project_proto_rawDesc), len(file_api_proto_domain_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_domain_project_proto_goTypes,
		DependencyIndexes: file_api_proto_domain_project_proto_depIdxs,
		MessageInfos:      file_api_proto_domain_project_proto_msgTypes,
	}.Build()
	File_api_proto_domain_project_proto = out.File
	file_api_proto_domain_project_proto_goTypes = nil
	file_api_proto_domain_project_proto_depIdxs = nil
}
