// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/domain/query.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	TotalTimeMs   int64                  `protobuf:"varint,3,opt,name=total_time_ms,json=totalTimeMs,proto3" json:"total_time_ms,omitempty"`
	MaxTimeMs     int64                  `protobuf:"varint,4,opt,name=max_time_ms,json=maxTimeMs,proto3" json:"max_time_ms,omitempty"`
	AvgTimeMs     int64                  `protobuf:"varint,5,opt,name=avg_time_ms,json=avgTimeMs,proto3" json:"avg_time_ms,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	ErrorCount    int64                  `protobuf:"varint,7,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	IsThrottled   bool                   `protobuf:"varint,8,opt,name=is_throttled,json=isThrottled,proto3" json:"is_throttled,omitempty"`
	Insight       *QueryPlanInsight      `protobuf:"bytes,9,opt,name=insight,proto3" json:"insight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopQuery) Reset() {
	*x = TopQuery{}
	mi := &file_api_proto_domain_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopQuery) ProtoMessage() {}

func (x *TopQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopQuery.ProtoReflect.Descriptor instead.
func (*TopQuery) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_query_proto_rawDescGZIP(), []int{0}
}

func (x *TopQuery) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TopQuery) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TopQuery) GetTotalTimeMs() int64 {
	if x != nil {
		return x.TotalTimeMs
	}
	return 0
}

func (x *TopQuery) GetMaxTimeMs() int64 {
	if x != nil {
		return x.MaxTimeMs
	}
	return 0
}

func (x *TopQuery) GetAvgTimeMs() int64 {
	if x != nil {
		return x.AvgTimeMs
	}
	return 0
}

func (x *TopQuery) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *TopQuery) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *TopQuery) GetIsThrottled() bool {
	if x != nil {
		return x.IsThrottled
	}
	return false
}

func (x *TopQuery) GetInsight() *QueryPlanInsight {
	if x != nil {
		return x.Insight
	}
	return nil
}

type QueryPlanInsight struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*Recommendation      `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	Plan            string                 `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryPlanInsight) Reset() {
	*x = QueryPlanInsight{}
	mi := &file_api_proto_domain_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPlanInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPlanInsight) ProtoMessage() {}

func (x *QueryPlanInsight) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPlanInsight.ProtoReflect.Descriptor instead.
func (*QueryPlanInsight) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryPlanInsight) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *QueryPlanInsight) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

type Recommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Impact        string                 `protobuf:"bytes,3,opt,name=impact,proto3" json:"impact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_api_proto_domain_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_query_proto_rawDescGZIP(), []int{2}
}

func (x *Recommendation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Recommendation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Recommendation) GetImpact() string {
	if x != nil {
		return x.Impact
	}
	return ""
}

type TuningSuggestion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Parameter      string                 `protobuf:"bytes,1,opt,name=parameter,proto3" json:"parameter,omitempty"`
	CurrentValue   string                 `protobuf:"bytes,2,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	SuggestedValue string                 `protobuf:"bytes,3,opt,name=suggested_value,json=suggestedValue,proto3" json:"suggested_value,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TuningSuggestion) Reset() {
	*x = TuningSuggestion{}
	mi := &file_api_proto_domain_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuningSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuningSuggestion) ProtoMessage() {}

func (x *TuningSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuningSuggestion.ProtoReflect.Descriptor instead.
func (*TuningSuggestion) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_query_proto_rawDescGZIP(), []int{3}
}

func (x *TuningSuggestion) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

func (x *TuningSuggestion) GetCurrentValue() string {
	if x != nil {
		return x.CurrentValue
	}
	return ""
}

func (x *TuningSuggestion) GetSuggestedValue() string {
	if x != nil {
		return x.SuggestedValue
	}
	return ""
}

func (x *TuningSuggestion) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type QueryInsight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Calls         int64                  `protobuf:"varint,2,opt,name=calls,proto3" json:"calls,omitempty"`
	TotalTime     float64                `protobuf:"fixed64,3,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	MinTime       float64                `protobuf:"fixed64,4,opt,name=min_time,json=minTime,proto3" json:"min_time,omitempty"`
	MaxTime       float64                `protobuf:"fixed64,5,opt,name=max_time,json=maxTime,proto3" json:"max_time,omitempty"`
	MeanTime      float64                `protobuf:"fixed64,6,opt,name=mean_time,json=meanTime,proto3" json:"mean_time,omitempty"`
	Rows          int64                  `protobuf:"varint,7,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryInsight) Reset() {
	*x = QueryInsight{}
	mi := &file_api_proto_domain_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInsight) ProtoMessage() {}

func (x *QueryInsight) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInsight.ProtoReflect.Descriptor instead.
func (*QueryInsight) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryInsight) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryInsight) GetCalls() int64 {
	if x != nil {
		return x.Calls
	}
	return 0
}

func (x *QueryInsight) GetTotalTime() float64 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

func (x *QueryInsight) GetMinTime() float64 {
	if x != nil {
		return x.MinTime
	}
	return 0
}

func (x *QueryInsight) GetMaxTime() float64 {
	if x != nil {
		return x.MaxTime
	}
	return 0
}

func (x *QueryInsight) GetMeanTime() float64 {
	if x != nil {
		return x.MeanTime
	}
	return 0
}

func (x *QueryInsight) GetRows() int64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type LockInsight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Locktype      string                 `protobuf:"bytes,2,opt,name=locktype,proto3" json:"locktype,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Granted       bool                   `protobuf:"varint,4,opt,name=granted,proto3" json:"granted,omitempty"`
	Query         string                 `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockInsight) Reset() {
	*x = LockInsight{}
	mi := &file_api_proto_domain_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockInsight) ProtoMessage() {}

func (x *LockInsight) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockInsight.ProtoReflect.Descriptor instead.
func (*LockInsight) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_query_proto_rawDescGZIP(), []int{5}
}

func (x *LockInsight) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *LockInsight) GetLocktype() string {
	if x != nil {
		return x.Locktype
	}
	return ""
}

func (x *LockInsight) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *LockInsight) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *LockInsight) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ReplicationInsight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	SentLsn       string                 `protobuf:"bytes,3,opt,name=sent_lsn,json=sentLsn,proto3" json:"sent_lsn,omitempty"`
	WriteLsn      string                 `protobuf:"bytes,4,opt,name=write_lsn,json=writeLsn,proto3" json:"write_lsn,omitempty"`
	FlushLsn      string                 `protobuf:"bytes,5,opt,name=flush_lsn,json=flushLsn,proto3" json:"flush_lsn,omitempty"`
	ReplayLsn     string                 `protobuf:"bytes,6,opt,name=replay_lsn,json=replayLsn,proto3" json:"replay_lsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationInsight) Reset() {
	*x = ReplicationInsight{}
	mi := &file_api_proto_domain_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationInsight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationInsight) ProtoMessage() {}

func (x *ReplicationInsight) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationInsight.ProtoReflect.Descriptor instead.
func (*ReplicationInsight) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_query_proto_rawDescGZIP(), []int{6}
}

func (x *ReplicationInsight) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ReplicationInsight) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ReplicationInsight) GetSentLsn() string {
	if x != nil {
		return x.SentLsn
	}
	return ""
}

func (x *ReplicationInsight) GetWriteLsn() string {
	if x != nil {
		return x.WriteLsn
	}
	return ""
}

func (x *ReplicationInsight) GetFlushLsn() string {
	if x != nil {
		return x.FlushLsn
	}
	return ""
}

func (x *ReplicationInsight) GetReplayLsn() string {
	if x != nil {
		return x.ReplayLsn
	}
	return ""
}

var File_api_proto_domain_query_proto protoreflect.FileDescriptor

const file_api_proto_domain_query_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/domain/query.proto\x12\x10api.proto.domain\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x02\n" +
	"\bTopQuery\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\"\n" +
	"\rtotal_time_ms\x18\x03 \x01(\x03R\vtotalTimeMs\x12\x1e\n" +
	"\vmax_time_ms\x18\x04 \x01(\x03R\tmaxTimeMs\x12\x1e\n" +
	"\vavg_time_ms\x18\x05 \x01(\x03R\tavgTimeMs\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x1f\n" +
	"\verror_count\x18\a \x01(\x03R\n" +
	"errorCount\x12!\n" +
	"\fis_throttled\x18\b \x01(\bR\visThrottled\x12<\n" +
	"\ainsight\x18\t \x01(\v2\".api.proto.domain.QueryPlanInsightR\ainsight\"r\n" +
	"\x10QueryPlanInsight\x12J\n" +
	"\x0frecommendations\x18\x01 \x03(\v2 .api.proto.domain.RecommendationR\x0frecommendations\x12\x12\n" +
	"\x04plan\x18\x02 \x01(\tR\x04plan\"V\n" +
	"\x0eRecommendation\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06impact\x18\x03 \x01(\tR\x06impact\"\x96\x01\n" +
	"\x10TuningSuggestion\x12\x1c\n" +
	"\tparameter\x18\x01 \x01(\tR\tparameter\x12#\n" +
	"\rcurrent_value\x18\x02 \x01(\tR\fcurrentValue\x12'\n" +
	"\x0fsuggested_value\x18\x03 \x01(\tR\x0esuggestedValue\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xc0\x01\n" +
	"\fQueryInsight\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05calls\x18\x02 \x01(\x03R\x05calls\x12\x1d\n" +
	"\n" +
	"total_time\x18\x03 \x01(\x01R\ttotalTime\x12\x19\n" +
	"\bmin_time\x18\x04 \x01(\x01R\aminTime\x12\x19\n" +
	"\bmax_time\x18\x05 \x01(\x01R\amaxTime\x12\x1b\n" +
	"\tmean_time\x18\x06 \x01(\x01R\bmeanTime\x12\x12\n" +
	"\x04rows\x18\a \x01(\x03R\x04rows\"\x7f\n" +
	"\vLockInsight\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x1a\n" +
	"\blocktype\x18\x02 \x01(\tR\blocktype\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x18\n" +
	"\agranted\x18\x04 \x01(\bR\agranted\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\"\xb0\x01\n" +
	"\x12ReplicationInsight\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x19\n" +
	"\bsent_lsn\x18\x03 \x01(\tR\asentLsn\x12\x1b\n" +
	"\twrite_lsn\x18\x04 \x01(\tR\bwriteLsn\x12\x1b\n" +
	"\tflush_lsn\x18\x05 \x01(\tR\bflushLsn\x12\x1d\n" +
	"\n" +
	"replay_lsn\x18\x06 \x01(\tR\treplayLsnB-Z+github.com/gsoultan/pontus/api/proto/domainb\x06proto3"

var (
	file_api_proto_domain_query_proto_rawDescOnce sync.Once
	file_api_proto_domain_query_proto_rawDescData []byte
)

func file_api_proto_domain_query_proto_rawDescGZIP() []byte {
	file_api_proto_domain_query_proto_rawDescOnce.Do(func() {
		file_api_proto_domain_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_domain_query_proto_rawDesc), len(file_api_proto_domain_query_proto_rawDesc)))
	})
	return file_api_proto_domain_query_proto_rawDescData
}

var file_api_proto_domain_query_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_domain_query_proto_goTypes = []any{
	(*TopQuery)(nil),              // 0: api.proto.domain.TopQuery
	(*QueryPlanInsight)(nil),      // 1: api.proto.domain.QueryPlanInsight
	(*Recommendation)(nil),        // 2: api.proto.domain.Recommendation
	(*TuningSuggestion)(nil),      // 3: api.proto.domain.TuningSuggestion
	(*QueryInsight)(nil),          // 4: api.proto.domain.QueryInsight
	(*LockInsight)(nil),           // 5: api.proto.domain.LockInsight
	(*ReplicationInsight)(nil),    // 6: api.proto.domain.ReplicationInsight
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_api_proto_domain_query_proto_depIdxs = []int32{
	7, // 0: api.proto.domain.TopQuery.last_seen:type_name -> google.protobuf.Timestamp
	1, // 1: api.proto.domain.TopQuery.insight:type_name -> api.proto.domain.QueryPlanInsight
	2, // 2: api.proto.domain.QueryPlanInsight.recommendations:type_name -> api.proto.domain.Recommendation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_domain_query_proto_init() }
func file_api_proto_domain_query_proto_init() {
	if File_api_proto_domain_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_domain_query_proto_rawDesc), len(file_api_proto_domain_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_domain_query_proto_goTypes,
		DependencyIndexes: file_api_proto_domain_query_proto_depIdxs,
		MessageInfos:      file_api_proto_domain_query_proto_msgTypes,
	}.Build()
	File_api_proto_domain_query_proto = out.File
	file_api_proto_domain_query_proto_goTypes = nil
	file_api_proto_domain_query_proto_depIdxs = nil
}
