// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/domain/status.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackendStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Address            string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Zone               string                 `protobuf:"bytes,15,opt,name=zone,proto3" json:"zone,omitempty"`
	Healthy            bool                   `protobuf:"varint,2,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ActiveConns        int64                  `protobuf:"varint,3,opt,name=active_conns,json=activeConns,proto3" json:"active_conns,omitempty"`
	LastCheck          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	Role               string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	LatencyMs          int64                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ReplicationLagMs   int64                  `protobuf:"varint,7,opt,name=replication_lag_ms,json=replicationLagMs,proto3" json:"replication_lag_ms,omitempty"`
	IsDraining         bool                   `protobuf:"varint,8,opt,name=is_draining,json=isDraining,proto3" json:"is_draining,omitempty"`
	Weight             int32                  `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	MaxConns           int32                  `protobuf:"varint,10,opt,name=max_conns,json=maxConns,proto3" json:"max_conns,omitempty"`
	CurrentMaxConns    int32                  `protobuf:"varint,16,opt,name=current_max_conns,json=currentMaxConns,proto3" json:"current_max_conns,omitempty"`
	IdleConns          int32                  `protobuf:"varint,11,opt,name=idle_conns,json=idleConns,proto3" json:"idle_conns,omitempty"`
	WaitQueueSize      int64                  `protobuf:"varint,12,opt,name=wait_queue_size,json=waitQueueSize,proto3" json:"wait_queue_size,omitempty"`
	TotalRequests      int64                  `protobuf:"varint,13,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalErrors        int64                  `protobuf:"varint,14,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	RttMs              int64                  `protobuf:"varint,17,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`
	ManagedByAgent     bool                   `protobuf:"varint,18,opt,name=managed_by_agent,json=managedByAgent,proto3" json:"managed_by_agent,omitempty"`
	AgentAddress       string                 `protobuf:"bytes,19,opt,name=agent_address,json=agentAddress,proto3" json:"agent_address,omitempty"`
	AgentConfig        *AgentDatabaseConfig   `protobuf:"bytes,20,opt,name=agent_config,json=agentConfig,proto3" json:"agent_config,omitempty"`
	DbMetrics          *DatabaseMetrics       `protobuf:"bytes,21,opt,name=db_metrics,json=dbMetrics,proto3" json:"db_metrics,omitempty"`
	InstalledVersion   string                 `protobuf:"bytes,22,opt,name=installed_version,json=installedVersion,proto3" json:"installed_version,omitempty"`
	RecommendedVersion string                 `protobuf:"bytes,23,opt,name=recommended_version,json=recommendedVersion,proto3" json:"recommended_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BackendStatus) Reset() {
	*x = BackendStatus{}
	mi := &file_api_proto_domain_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendStatus) ProtoMessage() {}

func (x *BackendStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendStatus.ProtoReflect.Descriptor instead.
func (*BackendStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_status_proto_rawDescGZIP(), []int{0}
}

func (x *BackendStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BackendStatus) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *BackendStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *BackendStatus) GetActiveConns() int64 {
	if x != nil {
		return x.ActiveConns
	}
	return 0
}

func (x *BackendStatus) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

func (x *BackendStatus) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *BackendStatus) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *BackendStatus) GetReplicationLagMs() int64 {
	if x != nil {
		return x.ReplicationLagMs
	}
	return 0
}

func (x *BackendStatus) GetIsDraining() bool {
	if x != nil {
		return x.IsDraining
	}
	return false
}

func (x *BackendStatus) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *BackendStatus) GetMaxConns() int32 {
	if x != nil {
		return x.MaxConns
	}
	return 0
}

func (x *BackendStatus) GetCurrentMaxConns() int32 {
	if x != nil {
		return x.CurrentMaxConns
	}
	return 0
}

func (x *BackendStatus) GetIdleConns() int32 {
	if x != nil {
		return x.IdleConns
	}
	return 0
}

func (x *BackendStatus) GetWaitQueueSize() int64 {
	if x != nil {
		return x.WaitQueueSize
	}
	return 0
}

func (x *BackendStatus) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *BackendStatus) GetTotalErrors() int64 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

func (x *BackendStatus) GetRttMs() int64 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *BackendStatus) GetManagedByAgent() bool {
	if x != nil {
		return x.ManagedByAgent
	}
	return false
}

func (x *BackendStatus) GetAgentAddress() string {
	if x != nil {
		return x.AgentAddress
	}
	return ""
}

func (x *BackendStatus) GetAgentConfig() *AgentDatabaseConfig {
	if x != nil {
		return x.AgentConfig
	}
	return nil
}

func (x *BackendStatus) GetDbMetrics() *DatabaseMetrics {
	if x != nil {
		return x.DbMetrics
	}
	return nil
}

func (x *BackendStatus) GetInstalledVersion() string {
	if x != nil {
		return x.InstalledVersion
	}
	return ""
}

func (x *BackendStatus) GetRecommendedVersion() string {
	if x != nil {
		return x.RecommendedVersion
	}
	return ""
}

type AdaptiveStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsThrottled       bool                   `protobuf:"varint,1,opt,name=is_throttled,json=isThrottled,proto3" json:"is_throttled,omitempty"`
	ThrottleReason    string                 `protobuf:"bytes,2,opt,name=throttle_reason,json=throttleReason,proto3" json:"throttle_reason,omitempty"`
	CurrentMaxWaiters int32                  `protobuf:"varint,3,opt,name=current_max_waiters,json=currentMaxWaiters,proto3" json:"current_max_waiters,omitempty"`
	ActiveGoroutines  int32                  `protobuf:"varint,4,opt,name=active_goroutines,json=activeGoroutines,proto3" json:"active_goroutines,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdaptiveStatus) Reset() {
	*x = AdaptiveStatus{}
	mi := &file_api_proto_domain_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptiveStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptiveStatus) ProtoMessage() {}

func (x *AdaptiveStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptiveStatus.ProtoReflect.Descriptor instead.
func (*AdaptiveStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_status_proto_rawDescGZIP(), []int{1}
}

func (x *AdaptiveStatus) GetIsThrottled() bool {
	if x != nil {
		return x.IsThrottled
	}
	return false
}

func (x *AdaptiveStatus) GetThrottleReason() string {
	if x != nil {
		return x.ThrottleReason
	}
	return ""
}

func (x *AdaptiveStatus) GetCurrentMaxWaiters() int32 {
	if x != nil {
		return x.CurrentMaxWaiters
	}
	return 0
}

func (x *AdaptiveStatus) GetActiveGoroutines() int32 {
	if x != nil {
		return x.ActiveGoroutines
	}
	return 0
}

type PerformanceSuggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"` // "info", "warning", "critical"
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceSuggestion) Reset() {
	*x = PerformanceSuggestion{}
	mi := &file_api_proto_domain_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceSuggestion) ProtoMessage() {}

func (x *PerformanceSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceSuggestion.ProtoReflect.Descriptor instead.
func (*PerformanceSuggestion) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_status_proto_rawDescGZIP(), []int{2}
}

func (x *PerformanceSuggestion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PerformanceSuggestion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PerformanceSuggestion) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *PerformanceSuggestion) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type Topology struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*TopologyNode        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*TopologyEdge        `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topology) Reset() {
	*x = Topology{}
	mi := &file_api_proto_domain_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topology) ProtoMessage() {}

func (x *Topology) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topology.ProtoReflect.Descriptor instead.
func (*Topology) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_status_proto_rawDescGZIP(), []int{3}
}

func (x *Topology) GetNodes() []*TopologyNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Topology) GetEdges() []*TopologyEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type TopologyNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`     // "proxy", "primary", "replica"
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "unhealthy", "draining"
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyNode) Reset() {
	*x = TopologyNode{}
	mi := &file_api_proto_domain_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyNode) ProtoMessage() {}

func (x *TopologyNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyNode.ProtoReflect.Descriptor instead.
func (*TopologyNode) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_status_proto_rawDescGZIP(), []int{4}
}

func (x *TopologyNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TopologyNode) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TopologyNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TopologyNode) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TopologyNode) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TopologyEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyEdge) Reset() {
	*x = TopologyEdge{}
	mi := &file_api_proto_domain_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyEdge) ProtoMessage() {}

func (x *TopologyEdge) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyEdge.ProtoReflect.Descriptor instead.
func (*TopologyEdge) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_status_proto_rawDescGZIP(), []int{5}
}

func (x *TopologyEdge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TopologyEdge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TopologyEdge) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TopologyEdge) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type MetricSnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RequestsPerSecond float32                `protobuf:"fixed32,2,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	ErrorRate         float32                `protobuf:"fixed32,3,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	LatencyMs         float32                `protobuf:"fixed32,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricSnapshot) Reset() {
	*x = MetricSnapshot{}
	mi := &file_api_proto_domain_status_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSnapshot) ProtoMessage() {}

func (x *MetricSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_status_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSnapshot.ProtoReflect.Descriptor instead.
func (*MetricSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_status_proto_rawDescGZIP(), []int{6}
}

func (x *MetricSnapshot) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricSnapshot) GetRequestsPerSecond() float32 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

func (x *MetricSnapshot) GetErrorRate() float32 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *MetricSnapshot) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type FirewallStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BlockedByWord    int64                  `protobuf:"varint,1,opt,name=blocked_by_word,json=blockedByWord,proto3" json:"blocked_by_word,omitempty"`
	BlockedByPattern int64                  `protobuf:"varint,2,opt,name=blocked_by_pattern,json=blockedByPattern,proto3" json:"blocked_by_pattern,omitempty"`
	BlockedBySize    int64                  `protobuf:"varint,3,opt,name=blocked_by_size,json=blockedBySize,proto3" json:"blocked_by_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FirewallStats) Reset() {
	*x = FirewallStats{}
	mi := &file_api_proto_domain_status_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallStats) ProtoMessage() {}

func (x *FirewallStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_status_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallStats.ProtoReflect.Descriptor instead.
func (*FirewallStats) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_status_proto_rawDescGZIP(), []int{7}
}

func (x *FirewallStats) GetBlockedByWord() int64 {
	if x != nil {
		return x.BlockedByWord
	}
	return 0
}

func (x *FirewallStats) GetBlockedByPattern() int64 {
	if x != nil {
		return x.BlockedByPattern
	}
	return 0
}

func (x *FirewallStats) GetBlockedBySize() int64 {
	if x != nil {
		return x.BlockedBySize
	}
	return 0
}

type CacheStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          int64                  `protobuf:"varint,1,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses        int64                  `protobuf:"varint,2,opt,name=misses,proto3" json:"misses,omitempty"`
	ItemsCount    int64                  `protobuf:"varint,3,opt,name=items_count,json=itemsCount,proto3" json:"items_count,omitempty"`
	HitRatio      float32                `protobuf:"fixed32,4,opt,name=hit_ratio,json=hitRatio,proto3" json:"hit_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheStats) Reset() {
	*x = CacheStats{}
	mi := &file_api_proto_domain_status_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStats) ProtoMessage() {}

func (x *CacheStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_domain_status_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStats.ProtoReflect.Descriptor instead.
func (*CacheStats) Descriptor() ([]byte, []int) {
	return file_api_proto_domain_status_proto_rawDescGZIP(), []int{8}
}

func (x *CacheStats) GetHits() int64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *CacheStats) GetMisses() int64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *CacheStats) GetItemsCount() int64 {
	if x != nil {
		return x.ItemsCount
	}
	return 0
}

func (x *CacheStats) GetHitRatio() float32 {
	if x != nil {
		return x.HitRatio
	}
	return 0
}

var File_api_proto_domain_status_proto protoreflect.FileDescriptor

const file_api_proto_domain_status_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/domain/status.proto\x12\x10api.proto.domain\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eapi/proto/domain/project.proto\x1a\x1eapi/proto/domain/metrics.proto\"\xf9\x06\n" +
	"\rBackendStatus\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04zone\x18\x0f \x01(\tR\x04zone\x12\x18\n" +
	"\ahealthy\x18\x02 \x01(\bR\ahealthy\x12!\n" +
	"\factive_conns\x18\x03 \x01(\x03R\vactiveConns\x129\n" +
	"\n" +
	"last_check\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMs\x12,\n" +
	"\x12replication_lag_ms\x18\a \x01(\x03R\x10replicationLagMs\x12\x1f\n" +
	"\vis_draining\x18\b \x01(\bR\n" +
	"isDraining\x12\x16\n" +
	"\x06weight\x18\t \x01(\x05R\x06weight\x12\x1b\n" +
	"\tmax_conns\x18\n" +
	" \x01(\x05R\bmaxConns\x12*\n" +
	"\x11current_max_conns\x18\x10 \x01(\x05R\x0fcurrentMaxConns\x12\x1d\n" +
	"\n" +
	"idle_conns\x18\v \x01(\x05R\tidleConns\x12&\n" +
	"\x0fwait_queue_size\x18\f \x01(\x03R\rwaitQueueSize\x12%\n" +
	"\x0etotal_requests\x18\r \x01(\x03R\rtotalRequests\x12!\n" +
	"\ftotal_errors\x18\x0e \x01(\x03R\vtotalErrors\x12\x15\n" +
	"\x06rtt_ms\x18\x11 \x01(\x03R\x05rttMs\x12(\n" +
	"\x10managed_by_agent\x18\x12 \x01(\bR\x0emanagedByAgent\x12#\n" +
	"\ragent_address\x18\x13 \x01(\tR\fagentAddress\x12H\n" +
	"\fagent_config\x18\x14 \x01(\v2%.api.proto.domain.AgentDatabaseConfigR\vagentConfig\x12@\n" +
	"\n" +
	"db_metrics\x18\x15 \x01(\v2!.api.proto.domain.DatabaseMetricsR\tdbMetrics\x12+\n" +
	"\x11installed_version\x18\x16 \x01(\tR\x10installedVersion\x12/\n" +
	"\x13recommended_version\x18\x17 \x01(\tR\x12recommendedVersion\"\xb9\x01\n" +
	"\x0eAdaptiveStatus\x12!\n" +
	"\fis_throttled\x18\x01 \x01(\bR\visThrottled\x12'\n" +
	"\x0fthrottle_reason\x18\x02 \x01(\tR\x0ethrottleReason\x12.\n" +
	"\x13current_max_waiters\x18\x03 \x01(\x05R\x11currentMaxWaiters\x12+\n" +
	"\x11active_goroutines\x18\x04 \x01(\x05R\x10activeGoroutines\"}\n" +
	"\x15PerformanceSuggestion\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"v\n" +
	"\bTopology\x124\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1e.api.proto.domain.TopologyNodeR\x05nodes\x124\n" +
	"\x05edges\x18\x02 \x03(\v2\x1e.api.proto.domain.TopologyEdgeR\x05edges\"z\n" +
	"\fTopologyNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\"\\\n" +
	"\fTopologyEdge\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\xb8\x01\n" +
	"\x0eMetricSnapshot\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12.\n" +
	"\x13requests_per_second\x18\x02 \x01(\x02R\x11requestsPerSecond\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x03 \x01(\x02R\terrorRate\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x02R\tlatencyMs\"\x8d\x01\n" +
	"\rFirewallStats\x12&\n" +
	"\x0fblocked_by_word\x18\x01 \x01(\x03R\rblockedByWord\x12,\n" +
	"\x12blocked_by_pattern\x18\x02 \x01(\x03R\x10blockedByPattern\x12&\n" +
	"\x0fblocked_by_size\x18\x03 \x01(\x03R\rblockedBySize\"v\n" +
	"\n" +
	"CacheStats\x12\x12\n" +
	"\x04hits\x18\x01 \x01(\x03R\x04hits\x12\x16\n" +
	"\x06misses\x18\x02 \x01(\x03R\x06misses\x12\x1f\n" +
	"\vitems_count\x18\x03 \x01(\x03R\n" +
	"itemsCount\x12\x1b\n" +
	"\thit_ratio\x18\x04 \x01(\x02R\bhitRatioB-Z+github.com/gsoultan/pontus/api/proto/domainb\x06proto3"

var (
	file_api_proto_domain_status_proto_rawDescOnce sync.Once
	file_api_proto_domain_status_proto_rawDescData []byte
)

func file_api_proto_domain_status_proto_rawDescGZIP() []byte {
	file_api_proto_domain_status_proto_rawDescOnce.Do(func() {
		file_api_proto_domain_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_domain_status_proto_rawDesc), len(file_api_proto_domain_status_proto_rawDesc)))
	})
	return file_api_proto_domain_status_proto_rawDescData
}

var file_api_proto_domain_status_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_domain_status_proto_goTypes = []any{
	(*BackendStatus)(nil),         // 0: api.proto.domain.BackendStatus
	(*AdaptiveStatus)(nil),        // 1: api.proto.domain.AdaptiveStatus
	(*PerformanceSuggestion)(nil), // 2: api.proto.domain.PerformanceSuggestion
	(*Topology)(nil),              // 3: api.proto.domain.Topology
	(*TopologyNode)(nil),          // 4: api.proto.domain.TopologyNode
	(*TopologyEdge)(nil),          // 5: api.proto.domain.TopologyEdge
	(*MetricSnapshot)(nil),        // 6: api.proto.domain.MetricSnapshot
	(*FirewallStats)(nil),         // 7: api.proto.domain.FirewallStats
	(*CacheStats)(nil),            // 8: api.proto.domain.CacheStats
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*AgentDatabaseConfig)(nil),   // 10: api.proto.domain.AgentDatabaseConfig
	(*DatabaseMetrics)(nil),       // 11: api.proto.domain.DatabaseMetrics
}
var file_api_proto_domain_status_proto_depIdxs = []int32{
	9,  // 0: api.proto.domain.BackendStatus.last_check:type_name -> google.protobuf.Timestamp
	10, // 1: api.proto.domain.BackendStatus.agent_config:type_name -> api.proto.domain.AgentDatabaseConfig
	11, // 2: api.proto.domain.BackendStatus.db_metrics:type_name -> api.proto.domain.DatabaseMetrics
	4,  // 3: api.proto.domain.Topology.nodes:type_name -> api.proto.domain.TopologyNode
	5,  // 4: api.proto.domain.Topology.edges:type_name -> api.proto.domain.TopologyEdge
	9,  // 5: api.proto.domain.MetricSnapshot.timestamp:type_name -> google.protobuf.Timestamp
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_domain_status_proto_init() }
func file_api_proto_domain_status_proto_init() {
	if File_api_proto_domain_status_proto != nil {
		return
	}
	file_api_proto_domain_project_proto_init()
	file_api_proto_domain_metrics_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_domain_status_proto_rawDesc), len(file_api_proto_domain_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_domain_status_proto_goTypes,
		DependencyIndexes: file_api_proto_domain_status_proto_depIdxs,
		MessageInfos:      file_api_proto_domain_status_proto_msgTypes,
	}.Build()
	File_api_proto_domain_status_proto = out.File
	file_api_proto_domain_status_proto_goTypes = nil
	file_api_proto_domain_status_proto_depIdxs = nil
}
