// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/endpoints/agent.proto

package endpoints

import (
	domain "github.com/gsoultan/pontus/api/proto/domain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{0}
}

type GetSystemInfoResponse struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	Os                 string                     `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Hostname           string                     `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	EnvVars            map[string]string          `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metrics            *domain.SystemMetrics      `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	HealthPrediction   *HealthPrediction          `protobuf:"bytes,5,opt,name=health_prediction,json=healthPrediction,proto3" json:"health_prediction,omitempty"`
	DetectedVersion    string                     `protobuf:"bytes,6,opt,name=detected_version,json=detectedVersion,proto3" json:"detected_version,omitempty"`
	AvailableVersions  []string                   `protobuf:"bytes,7,rep,name=available_versions,json=availableVersions,proto3" json:"available_versions,omitempty"`
	AgentVersion       string                     `protobuf:"bytes,8,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	RecommendedVersion string                     `protobuf:"bytes,9,opt,name=recommended_version,json=recommendedVersion,proto3" json:"recommended_version,omitempty"`
	PostgresRunning    bool                       `protobuf:"varint,10,opt,name=postgres_running,json=postgresRunning,proto3" json:"postgres_running,omitempty"`
	PostgresAddress    string                     `protobuf:"bytes,11,opt,name=postgres_address,json=postgresAddress,proto3" json:"postgres_address,omitempty"`
	PostgresDataDir    string                     `protobuf:"bytes,12,opt,name=postgres_data_dir,json=postgresDataDir,proto3" json:"postgres_data_dir,omitempty"`
	TuningSuggestions  []*domain.TuningSuggestion `protobuf:"bytes,13,rep,name=tuning_suggestions,json=tuningSuggestions,proto3" json:"tuning_suggestions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetSystemInfoResponse) Reset() {
	*x = GetSystemInfoResponse{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResponse) ProtoMessage() {}

func (x *GetSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetSystemInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *GetSystemInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetSystemInfoResponse) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *GetSystemInfoResponse) GetMetrics() *domain.SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GetSystemInfoResponse) GetHealthPrediction() *HealthPrediction {
	if x != nil {
		return x.HealthPrediction
	}
	return nil
}

func (x *GetSystemInfoResponse) GetDetectedVersion() string {
	if x != nil {
		return x.DetectedVersion
	}
	return ""
}

func (x *GetSystemInfoResponse) GetAvailableVersions() []string {
	if x != nil {
		return x.AvailableVersions
	}
	return nil
}

func (x *GetSystemInfoResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *GetSystemInfoResponse) GetRecommendedVersion() string {
	if x != nil {
		return x.RecommendedVersion
	}
	return ""
}

func (x *GetSystemInfoResponse) GetPostgresRunning() bool {
	if x != nil {
		return x.PostgresRunning
	}
	return false
}

func (x *GetSystemInfoResponse) GetPostgresAddress() string {
	if x != nil {
		return x.PostgresAddress
	}
	return ""
}

func (x *GetSystemInfoResponse) GetPostgresDataDir() string {
	if x != nil {
		return x.PostgresDataDir
	}
	return ""
}

func (x *GetSystemInfoResponse) GetTuningSuggestions() []*domain.TuningSuggestion {
	if x != nil {
		return x.TuningSuggestions
	}
	return nil
}

type HealthPrediction struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DegradationDetected  bool                   `protobuf:"varint,1,opt,name=degradation_detected,json=degradationDetected,proto3" json:"degradation_detected,omitempty"`
	Reason               string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Confidence           float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	EstimatedFailureTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=estimated_failure_time,json=estimatedFailureTime,proto3" json:"estimated_failure_time,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HealthPrediction) Reset() {
	*x = HealthPrediction{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthPrediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthPrediction) ProtoMessage() {}

func (x *HealthPrediction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthPrediction.ProtoReflect.Descriptor instead.
func (*HealthPrediction) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HealthPrediction) GetDegradationDetected() bool {
	if x != nil {
		return x.DegradationDetected
	}
	return false
}

func (x *HealthPrediction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HealthPrediction) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *HealthPrediction) GetEstimatedFailureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedFailureTime
	}
	return nil
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateConfigRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UpdateConfigRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateConfigResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ExecuteCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteCommandRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ExecuteCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteCommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteCommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteCommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type RestartServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartServiceRequest) Reset() {
	*x = RestartServiceRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartServiceRequest) ProtoMessage() {}

func (x *RestartServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartServiceRequest.ProtoReflect.Descriptor instead.
func (*RestartServiceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{7}
}

func (x *RestartServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type RestartServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartServiceResponse) Reset() {
	*x = RestartServiceResponse{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartServiceResponse) ProtoMessage() {}

func (x *RestartServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartServiceResponse.ProtoReflect.Descriptor instead.
func (*RestartServiceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RestartServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestartServiceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type LogStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogPath       string                 `protobuf:"bytes,1,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamRequest) Reset() {
	*x = LogStreamRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamRequest) ProtoMessage() {}

func (x *LogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamRequest.ProtoReflect.Descriptor instead.
func (*LogStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{9}
}

func (x *LogStreamRequest) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *LogStreamRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type LogStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamResponse) Reset() {
	*x = LogStreamResponse{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamResponse) ProtoMessage() {}

func (x *LogStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamResponse.ProtoReflect.Descriptor instead.
func (*LogStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{10}
}

func (x *LogStreamResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type ScheduleMaintenanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskType       string                 `protobuf:"bytes,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Database       string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	CronExpression string                 `protobuf:"bytes,3,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduleMaintenanceRequest) Reset() {
	*x = ScheduleMaintenanceRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleMaintenanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleMaintenanceRequest) ProtoMessage() {}

func (x *ScheduleMaintenanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleMaintenanceRequest.ProtoReflect.Descriptor instead.
func (*ScheduleMaintenanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ScheduleMaintenanceRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *ScheduleMaintenanceRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ScheduleMaintenanceRequest) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

type ScheduleMaintenanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleMaintenanceResponse) Reset() {
	*x = ScheduleMaintenanceResponse{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleMaintenanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleMaintenanceResponse) ProtoMessage() {}

func (x *ScheduleMaintenanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleMaintenanceResponse.ProtoReflect.Descriptor instead.
func (*ScheduleMaintenanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ScheduleMaintenanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScheduleMaintenanceResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ScheduleMaintenanceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SetupReplicationRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PrimaryHost         string                 `protobuf:"bytes,1,opt,name=primary_host,json=primaryHost,proto3" json:"primary_host,omitempty"`
	PrimaryPort         int32                  `protobuf:"varint,2,opt,name=primary_port,json=primaryPort,proto3" json:"primary_port,omitempty"`
	ReplicationUser     string                 `protobuf:"bytes,3,opt,name=replication_user,json=replicationUser,proto3" json:"replication_user,omitempty"`
	ReplicationPassword string                 `protobuf:"bytes,4,opt,name=replication_password,json=replicationPassword,proto3" json:"replication_password,omitempty"`
	SlotName            string                 `protobuf:"bytes,5,opt,name=slot_name,json=slotName,proto3" json:"slot_name,omitempty"`
	UseRewind           bool                   `protobuf:"varint,6,opt,name=use_rewind,json=useRewind,proto3" json:"use_rewind,omitempty"`
	DataDirectory       string                 `protobuf:"bytes,7,opt,name=data_directory,json=dataDirectory,proto3" json:"data_directory,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetupReplicationRequest) Reset() {
	*x = SetupReplicationRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupReplicationRequest) ProtoMessage() {}

func (x *SetupReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupReplicationRequest.ProtoReflect.Descriptor instead.
func (*SetupReplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{13}
}

func (x *SetupReplicationRequest) GetPrimaryHost() string {
	if x != nil {
		return x.PrimaryHost
	}
	return ""
}

func (x *SetupReplicationRequest) GetPrimaryPort() int32 {
	if x != nil {
		return x.PrimaryPort
	}
	return 0
}

func (x *SetupReplicationRequest) GetReplicationUser() string {
	if x != nil {
		return x.ReplicationUser
	}
	return ""
}

func (x *SetupReplicationRequest) GetReplicationPassword() string {
	if x != nil {
		return x.ReplicationPassword
	}
	return ""
}

func (x *SetupReplicationRequest) GetSlotName() string {
	if x != nil {
		return x.SlotName
	}
	return ""
}

func (x *SetupReplicationRequest) GetUseRewind() bool {
	if x != nil {
		return x.UseRewind
	}
	return false
}

func (x *SetupReplicationRequest) GetDataDirectory() string {
	if x != nil {
		return x.DataDirectory
	}
	return ""
}

type ReplicationProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Percentage    int32                  `protobuf:"varint,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationProgress) Reset() {
	*x = ReplicationProgress{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationProgress) ProtoMessage() {}

func (x *ReplicationProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationProgress.ProtoReflect.Descriptor instead.
func (*ReplicationProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ReplicationProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ReplicationProgress) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *ReplicationProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PromoteNodeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WaitForCompletion string                 `protobuf:"bytes,1,opt,name=wait_for_completion,json=waitForCompletion,proto3" json:"wait_for_completion,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PromoteNodeRequest) Reset() {
	*x = PromoteNodeRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteNodeRequest) ProtoMessage() {}

func (x *PromoteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteNodeRequest.ProtoReflect.Descriptor instead.
func (*PromoteNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{15}
}

func (x *PromoteNodeRequest) GetWaitForCompletion() string {
	if x != nil {
		return x.WaitForCompletion
	}
	return ""
}

type PromoteNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteNodeResponse) Reset() {
	*x = PromoteNodeResponse{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteNodeResponse) ProtoMessage() {}

func (x *PromoteNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteNodeResponse.ProtoReflect.Descriptor instead.
func (*PromoteNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{16}
}

func (x *PromoteNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PromoteNodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type InitializeDatabaseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DataDirectory   string                 `protobuf:"bytes,1,opt,name=data_directory,json=dataDirectory,proto3" json:"data_directory,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	InitialDatabase string                 `protobuf:"bytes,3,opt,name=initial_database,json=initialDatabase,proto3" json:"initial_database,omitempty"`
	InitialUser     string                 `protobuf:"bytes,4,opt,name=initial_user,json=initialUser,proto3" json:"initial_user,omitempty"`
	InitialPassword string                 `protobuf:"bytes,5,opt,name=initial_password,json=initialPassword,proto3" json:"initial_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitializeDatabaseRequest) Reset() {
	*x = InitializeDatabaseRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeDatabaseRequest) ProtoMessage() {}

func (x *InitializeDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeDatabaseRequest.ProtoReflect.Descriptor instead.
func (*InitializeDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{17}
}

func (x *InitializeDatabaseRequest) GetDataDirectory() string {
	if x != nil {
		return x.DataDirectory
	}
	return ""
}

func (x *InitializeDatabaseRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InitializeDatabaseRequest) GetInitialDatabase() string {
	if x != nil {
		return x.InitialDatabase
	}
	return ""
}

func (x *InitializeDatabaseRequest) GetInitialUser() string {
	if x != nil {
		return x.InitialUser
	}
	return ""
}

func (x *InitializeDatabaseRequest) GetInitialPassword() string {
	if x != nil {
		return x.InitialPassword
	}
	return ""
}

type InitializeProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Percentage    int32                  `protobuf:"varint,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeProgress) Reset() {
	*x = InitializeProgress{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeProgress) ProtoMessage() {}

func (x *InitializeProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeProgress.ProtoReflect.Descriptor instead.
func (*InitializeProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{18}
}

func (x *InitializeProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *InitializeProgress) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *InitializeProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InstallDatabaseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	TargetDirectory string                 `protobuf:"bytes,2,opt,name=target_directory,json=targetDirectory,proto3" json:"target_directory,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InstallDatabaseRequest) Reset() {
	*x = InstallDatabaseRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallDatabaseRequest) ProtoMessage() {}

func (x *InstallDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallDatabaseRequest.ProtoReflect.Descriptor instead.
func (*InstallDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{19}
}

func (x *InstallDatabaseRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstallDatabaseRequest) GetTargetDirectory() string {
	if x != nil {
		return x.TargetDirectory
	}
	return ""
}

type InstallProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Percentage    int32                  `protobuf:"varint,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallProgress) Reset() {
	*x = InstallProgress{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallProgress) ProtoMessage() {}

func (x *InstallProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallProgress.ProtoReflect.Descriptor instead.
func (*InstallProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{20}
}

func (x *InstallProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *InstallProgress) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *InstallProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstallProgress) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type BackupDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupPath    string                 `protobuf:"bytes,1,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupDatabaseRequest) Reset() {
	*x = BackupDatabaseRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupDatabaseRequest) ProtoMessage() {}

func (x *BackupDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupDatabaseRequest.ProtoReflect.Descriptor instead.
func (*BackupDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{21}
}

func (x *BackupDatabaseRequest) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *BackupDatabaseRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type BackupProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Percentage    int32                  `protobuf:"varint,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupProgress) Reset() {
	*x = BackupProgress{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupProgress) ProtoMessage() {}

func (x *BackupProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupProgress.ProtoReflect.Descriptor instead.
func (*BackupProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{22}
}

func (x *BackupProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *BackupProgress) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *BackupProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestoreDatabaseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BackupPath     string                 `protobuf:"bytes,1,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	TargetDatabase string                 `protobuf:"bytes,2,opt,name=target_database,json=targetDatabase,proto3" json:"target_database,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RestoreDatabaseRequest) Reset() {
	*x = RestoreDatabaseRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreDatabaseRequest) ProtoMessage() {}

func (x *RestoreDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreDatabaseRequest.ProtoReflect.Descriptor instead.
func (*RestoreDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{23}
}

func (x *RestoreDatabaseRequest) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *RestoreDatabaseRequest) GetTargetDatabase() string {
	if x != nil {
		return x.TargetDatabase
	}
	return ""
}

type RestoreProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Percentage    int32                  `protobuf:"varint,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreProgress) Reset() {
	*x = RestoreProgress{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreProgress) ProtoMessage() {}

func (x *RestoreProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreProgress.ProtoReflect.Descriptor instead.
func (*RestoreProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{24}
}

func (x *RestoreProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *RestoreProgress) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *RestoreProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPostgresInsightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostgresInsightsRequest) Reset() {
	*x = GetPostgresInsightsRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostgresInsightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostgresInsightsRequest) ProtoMessage() {}

func (x *GetPostgresInsightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostgresInsightsRequest.ProtoReflect.Descriptor instead.
func (*GetPostgresInsightsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{25}
}

func (x *GetPostgresInsightsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type GetPostgresInsightsResponse struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	TopQueries        []*domain.QueryInsight       `protobuf:"bytes,1,rep,name=top_queries,json=topQueries,proto3" json:"top_queries,omitempty"`
	ActiveLocks       []*domain.LockInsight        `protobuf:"bytes,2,rep,name=active_locks,json=activeLocks,proto3" json:"active_locks,omitempty"`
	ReplicationStatus []*domain.ReplicationInsight `protobuf:"bytes,3,rep,name=replication_status,json=replicationStatus,proto3" json:"replication_status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetPostgresInsightsResponse) Reset() {
	*x = GetPostgresInsightsResponse{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostgresInsightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostgresInsightsResponse) ProtoMessage() {}

func (x *GetPostgresInsightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostgresInsightsResponse.ProtoReflect.Descriptor instead.
func (*GetPostgresInsightsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{26}
}

func (x *GetPostgresInsightsResponse) GetTopQueries() []*domain.QueryInsight {
	if x != nil {
		return x.TopQueries
	}
	return nil
}

func (x *GetPostgresInsightsResponse) GetActiveLocks() []*domain.LockInsight {
	if x != nil {
		return x.ActiveLocks
	}
	return nil
}

func (x *GetPostgresInsightsResponse) GetReplicationStatus() []*domain.ReplicationInsight {
	if x != nil {
		return x.ReplicationStatus
	}
	return nil
}

type ShutdownDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataDirectory string                 `protobuf:"bytes,1,opt,name=data_directory,json=dataDirectory,proto3" json:"data_directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownDatabaseRequest) Reset() {
	*x = ShutdownDatabaseRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownDatabaseRequest) ProtoMessage() {}

func (x *ShutdownDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownDatabaseRequest.ProtoReflect.Descriptor instead.
func (*ShutdownDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{27}
}

func (x *ShutdownDatabaseRequest) GetDataDirectory() string {
	if x != nil {
		return x.DataDirectory
	}
	return ""
}

type ShutdownDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownDatabaseResponse) Reset() {
	*x = ShutdownDatabaseResponse{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownDatabaseResponse) ProtoMessage() {}

func (x *ShutdownDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownDatabaseResponse.ProtoReflect.Descriptor instead.
func (*ShutdownDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{28}
}

func (x *ShutdownDatabaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShutdownDatabaseResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RemoveDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataDirectory string                 `protobuf:"bytes,1,opt,name=data_directory,json=dataDirectory,proto3" json:"data_directory,omitempty"`
	DeleteData    bool                   `protobuf:"varint,2,opt,name=delete_data,json=deleteData,proto3" json:"delete_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDatabaseRequest) Reset() {
	*x = RemoveDatabaseRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDatabaseRequest) ProtoMessage() {}

func (x *RemoveDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDatabaseRequest.ProtoReflect.Descriptor instead.
func (*RemoveDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{29}
}

func (x *RemoveDatabaseRequest) GetDataDirectory() string {
	if x != nil {
		return x.DataDirectory
	}
	return ""
}

func (x *RemoveDatabaseRequest) GetDeleteData() bool {
	if x != nil {
		return x.DeleteData
	}
	return false
}

type RemoveDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDatabaseResponse) Reset() {
	*x = RemoveDatabaseResponse{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDatabaseResponse) ProtoMessage() {}

func (x *RemoveDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDatabaseResponse.ProtoReflect.Descriptor instead.
func (*RemoveDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{30}
}

func (x *RemoveDatabaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveDatabaseResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type VacuumDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Full          bool                   `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"`
	Analyze       bool                   `protobuf:"varint,3,opt,name=analyze,proto3" json:"analyze,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VacuumDatabaseRequest) Reset() {
	*x = VacuumDatabaseRequest{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VacuumDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacuumDatabaseRequest) ProtoMessage() {}

func (x *VacuumDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacuumDatabaseRequest.ProtoReflect.Descriptor instead.
func (*VacuumDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{31}
}

func (x *VacuumDatabaseRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *VacuumDatabaseRequest) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *VacuumDatabaseRequest) GetAnalyze() bool {
	if x != nil {
		return x.Analyze
	}
	return false
}

type VacuumProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Percentage    int32                  `protobuf:"varint,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VacuumProgress) Reset() {
	*x = VacuumProgress{}
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VacuumProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacuumProgress) ProtoMessage() {}

func (x *VacuumProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_endpoints_agent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacuumProgress.ProtoReflect.Descriptor instead.
func (*VacuumProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_endpoints_agent_proto_rawDescGZIP(), []int{32}
}

func (x *VacuumProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *VacuumProgress) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *VacuumProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_endpoints_agent_proto protoreflect.FileDescriptor

const file_api_proto_endpoints_agent_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/endpoints/agent.proto\x12\x13api.proto.endpoints\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eapi/proto/domain/metrics.proto\x1a\x1capi/proto/domain/query.proto\"\x16\n" +
	"\x14GetSystemInfoRequest\"\xe7\x05\n" +
	"\x15GetSystemInfoResponse\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12R\n" +
	"\benv_vars\x18\x03 \x03(\v27.api.proto.endpoints.GetSystemInfoResponse.EnvVarsEntryR\aenvVars\x129\n" +
	"\ametrics\x18\x04 \x01(\v2\x1f.api.proto.domain.SystemMetricsR\ametrics\x12R\n" +
	"\x11health_prediction\x18\x05 \x01(\v2%.api.proto.endpoints.HealthPredictionR\x10healthPrediction\x12)\n" +
	"\x10detected_version\x18\x06 \x01(\tR\x0fdetectedVersion\x12-\n" +
	"\x12available_versions\x18\a \x03(\tR\x11availableVersions\x12#\n" +
	"\ragent_version\x18\b \x01(\tR\fagentVersion\x12/\n" +
	"\x13recommended_version\x18\t \x01(\tR\x12recommendedVersion\x12)\n" +
	"\x10postgres_running\x18\n" +
	" \x01(\bR\x0fpostgresRunning\x12)\n" +
	"\x10postgres_address\x18\v \x01(\tR\x0fpostgresAddress\x12*\n" +
	"\x11postgres_data_dir\x18\f \x01(\tR\x0fpostgresDataDir\x12Q\n" +
	"\x12tuning_suggestions\x18\r \x03(\v2\".api.proto.domain.TuningSuggestionR\x11tuningSuggestions\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x01\n" +
	"\x10HealthPrediction\x121\n" +
	"\x14degradation_detected\x18\x01 \x01(\bR\x13degradationDetected\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12P\n" +
	"\x16estimated_failure_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x14estimatedFailureTime\"L\n" +
	"\x13UpdateConfigRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"U\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xc4\x01\n" +
	"\x15ExecuteCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12E\n" +
	"\x03env\x18\x03 \x03(\v23.api.proto.endpoints.ExecuteCommandRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x16ExecuteCommandResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\":\n" +
	"\x15RestartServiceRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"W\n" +
	"\x16RestartServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"E\n" +
	"\x10LogStreamRequest\x12\x19\n" +
	"\blog_path\x18\x01 \x01(\tR\alogPath\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"'\n" +
	"\x11LogStreamResponse\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\"~\n" +
	"\x1aScheduleMaintenanceRequest\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\tR\btaskType\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12'\n" +
	"\x0fcron_expression\x18\x03 \x01(\tR\x0ecronExpression\"u\n" +
	"\x1bScheduleMaintenanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xa0\x02\n" +
	"\x17SetupReplicationRequest\x12!\n" +
	"\fprimary_host\x18\x01 \x01(\tR\vprimaryHost\x12!\n" +
	"\fprimary_port\x18\x02 \x01(\x05R\vprimaryPort\x12)\n" +
	"\x10replication_user\x18\x03 \x01(\tR\x0freplicationUser\x121\n" +
	"\x14replication_password\x18\x04 \x01(\tR\x13replicationPassword\x12\x1b\n" +
	"\tslot_name\x18\x05 \x01(\tR\bslotName\x12\x1d\n" +
	"\n" +
	"use_rewind\x18\x06 \x01(\bR\tuseRewind\x12%\n" +
	"\x0edata_directory\x18\a \x01(\tR\rdataDirectory\"e\n" +
	"\x13ReplicationProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x05R\n" +
	"percentage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"D\n" +
	"\x12PromoteNodeRequest\x12.\n" +
	"\x13wait_for_completion\x18\x01 \x01(\tR\x11waitForCompletion\"T\n" +
	"\x13PromoteNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xd5\x01\n" +
	"\x19InitializeDatabaseRequest\x12%\n" +
	"\x0edata_directory\x18\x01 \x01(\tR\rdataDirectory\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10initial_database\x18\x03 \x01(\tR\x0finitialDatabase\x12!\n" +
	"\finitial_user\x18\x04 \x01(\tR\vinitialUser\x12)\n" +
	"\x10initial_password\x18\x05 \x01(\tR\x0finitialPassword\"d\n" +
	"\x12InitializeProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x05R\n" +
	"percentage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"]\n" +
	"\x16InstallDatabaseRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12)\n" +
	"\x10target_directory\x18\x02 \x01(\tR\x0ftargetDirectory\"\x86\x01\n" +
	"\x0fInstallProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x05R\n" +
	"percentage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"T\n" +
	"\x15BackupDatabaseRequest\x12\x1f\n" +
	"\vbackup_path\x18\x01 \x01(\tR\n" +
	"backupPath\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\"`\n" +
	"\x0eBackupProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x05R\n" +
	"percentage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"b\n" +
	"\x16RestoreDatabaseRequest\x12\x1f\n" +
	"\vbackup_path\x18\x01 \x01(\tR\n" +
	"backupPath\x12'\n" +
	"\x0ftarget_database\x18\x02 \x01(\tR\x0etargetDatabase\"a\n" +
	"\x0fRestoreProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x05R\n" +
	"percentage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"8\n" +
	"\x1aGetPostgresInsightsRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\"\xf5\x01\n" +
	"\x1bGetPostgresInsightsResponse\x12?\n" +
	"\vtop_queries\x18\x01 \x03(\v2\x1e.api.proto.domain.QueryInsightR\n" +
	"topQueries\x12@\n" +
	"\factive_locks\x18\x02 \x03(\v2\x1d.api.proto.domain.LockInsightR\vactiveLocks\x12S\n" +
	"\x12replication_status\x18\x03 \x03(\v2$.api.proto.domain.ReplicationInsightR\x11replicationStatus\"@\n" +
	"\x17ShutdownDatabaseRequest\x12%\n" +
	"\x0edata_directory\x18\x01 \x01(\tR\rdataDirectory\"Y\n" +
	"\x18ShutdownDatabaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"_\n" +
	"\x15RemoveDatabaseRequest\x12%\n" +
	"\x0edata_directory\x18\x01 \x01(\tR\rdataDirectory\x12\x1f\n" +
	"\vdelete_data\x18\x02 \x01(\bR\n" +
	"deleteData\"W\n" +
	"\x16RemoveDatabaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"a\n" +
	"\x15VacuumDatabaseRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x12\n" +
	"\x04full\x18\x02 \x01(\bR\x04full\x12\x18\n" +
	"\aanalyze\x18\x03 \x01(\bR\aanalyze\"`\n" +
	"\x0eVacuumProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x05R\n" +
	"percentage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB0Z.github.com/gsoultan/pontus/api/proto/endpointsb\x06proto3"

var (
	file_api_proto_endpoints_agent_proto_rawDescOnce sync.Once
	file_api_proto_endpoints_agent_proto_rawDescData []byte
)

func file_api_proto_endpoints_agent_proto_rawDescGZIP() []byte {
	file_api_proto_endpoints_agent_proto_rawDescOnce.Do(func() {
		file_api_proto_endpoints_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_endpoints_agent_proto_rawDesc), len(file_api_proto_endpoints_agent_proto_rawDesc)))
	})
	return file_api_proto_endpoints_agent_proto_rawDescData
}

var file_api_proto_endpoints_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_api_proto_endpoints_agent_proto_goTypes = []any{
	(*GetSystemInfoRequest)(nil),        // 0: api.proto.endpoints.GetSystemInfoRequest
	(*GetSystemInfoResponse)(nil),       // 1: api.proto.endpoints.GetSystemInfoResponse
	(*HealthPrediction)(nil),            // 2: api.proto.endpoints.HealthPrediction
	(*UpdateConfigRequest)(nil),         // 3: api.proto.endpoints.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),        // 4: api.proto.endpoints.UpdateConfigResponse
	(*ExecuteCommandRequest)(nil),       // 5: api.proto.endpoints.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil),      // 6: api.proto.endpoints.ExecuteCommandResponse
	(*RestartServiceRequest)(nil),       // 7: api.proto.endpoints.RestartServiceRequest
	(*RestartServiceResponse)(nil),      // 8: api.proto.endpoints.RestartServiceResponse
	(*LogStreamRequest)(nil),            // 9: api.proto.endpoints.LogStreamRequest
	(*LogStreamResponse)(nil),           // 10: api.proto.endpoints.LogStreamResponse
	(*ScheduleMaintenanceRequest)(nil),  // 11: api.proto.endpoints.ScheduleMaintenanceRequest
	(*ScheduleMaintenanceResponse)(nil), // 12: api.proto.endpoints.ScheduleMaintenanceResponse
	(*SetupReplicationRequest)(nil),     // 13: api.proto.endpoints.SetupReplicationRequest
	(*ReplicationProgress)(nil),         // 14: api.proto.endpoints.ReplicationProgress
	(*PromoteNodeRequest)(nil),          // 15: api.proto.endpoints.PromoteNodeRequest
	(*PromoteNodeResponse)(nil),         // 16: api.proto.endpoints.PromoteNodeResponse
	(*InitializeDatabaseRequest)(nil),   // 17: api.proto.endpoints.InitializeDatabaseRequest
	(*InitializeProgress)(nil),          // 18: api.proto.endpoints.InitializeProgress
	(*InstallDatabaseRequest)(nil),      // 19: api.proto.endpoints.InstallDatabaseRequest
	(*InstallProgress)(nil),             // 20: api.proto.endpoints.InstallProgress
	(*BackupDatabaseRequest)(nil),       // 21: api.proto.endpoints.BackupDatabaseRequest
	(*BackupProgress)(nil),              // 22: api.proto.endpoints.BackupProgress
	(*RestoreDatabaseRequest)(nil),      // 23: api.proto.endpoints.RestoreDatabaseRequest
	(*RestoreProgress)(nil),             // 24: api.proto.endpoints.RestoreProgress
	(*GetPostgresInsightsRequest)(nil),  // 25: api.proto.endpoints.GetPostgresInsightsRequest
	(*GetPostgresInsightsResponse)(nil), // 26: api.proto.endpoints.GetPostgresInsightsResponse
	(*ShutdownDatabaseRequest)(nil),     // 27: api.proto.endpoints.ShutdownDatabaseRequest
	(*ShutdownDatabaseResponse)(nil),    // 28: api.proto.endpoints.ShutdownDatabaseResponse
	(*RemoveDatabaseRequest)(nil),       // 29: api.proto.endpoints.RemoveDatabaseRequest
	(*RemoveDatabaseResponse)(nil),      // 30: api.proto.endpoints.RemoveDatabaseResponse
	(*VacuumDatabaseRequest)(nil),       // 31: api.proto.endpoints.VacuumDatabaseRequest
	(*VacuumProgress)(nil),              // 32: api.proto.endpoints.VacuumProgress
	nil,                                 // 33: api.proto.endpoints.GetSystemInfoResponse.EnvVarsEntry
	nil,                                 // 34: api.proto.endpoints.ExecuteCommandRequest.EnvEntry
	(*domain.SystemMetrics)(nil),        // 35: api.proto.domain.SystemMetrics
	(*domain.TuningSuggestion)(nil),     // 36: api.proto.domain.TuningSuggestion
	(*timestamppb.Timestamp)(nil),       // 37: google.protobuf.Timestamp
	(*domain.QueryInsight)(nil),         // 38: api.proto.domain.QueryInsight
	(*domain.LockInsight)(nil),          // 39: api.proto.domain.LockInsight
	(*domain.ReplicationInsight)(nil),   // 40: api.proto.domain.ReplicationInsight
}
var file_api_proto_endpoints_agent_proto_depIdxs = []int32{
	33, // 0: api.proto.endpoints.GetSystemInfoResponse.env_vars:type_name -> api.proto.endpoints.GetSystemInfoResponse.EnvVarsEntry
	35, // 1: api.proto.endpoints.GetSystemInfoResponse.metrics:type_name -> api.proto.domain.SystemMetrics
	2,  // 2: api.proto.endpoints.GetSystemInfoResponse.health_prediction:type_name -> api.proto.endpoints.HealthPrediction
	36, // 3: api.proto.endpoints.GetSystemInfoResponse.tuning_suggestions:type_name -> api.proto.domain.TuningSuggestion
	37, // 4: api.proto.endpoints.HealthPrediction.estimated_failure_time:type_name -> google.protobuf.Timestamp
	34, // 5: api.proto.endpoints.ExecuteCommandRequest.env:type_name -> api.proto.endpoints.ExecuteCommandRequest.EnvEntry
	38, // 6: api.proto.endpoints.GetPostgresInsightsResponse.top_queries:type_name -> api.proto.domain.QueryInsight
	39, // 7: api.proto.endpoints.GetPostgresInsightsResponse.active_locks:type_name -> api.proto.domain.LockInsight
	40, // 8: api.proto.endpoints.GetPostgresInsightsResponse.replication_status:type_name -> api.proto.domain.ReplicationInsight
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_endpoints_agent_proto_init() }
func file_api_proto_endpoints_agent_proto_init() {
	if File_api_proto_endpoints_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_endpoints_agent_proto_rawDesc), len(file_api_proto_endpoints_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_endpoints_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_endpoints_agent_proto_depIdxs,
		MessageInfos:      file_api_proto_endpoints_agent_proto_msgTypes,
	}.Build()
	File_api_proto_endpoints_agent_proto = out.File
	file_api_proto_endpoints_agent_proto_goTypes = nil
	file_api_proto_endpoints_agent_proto_depIdxs = nil
}
