/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackendsRouteImport } from './routes/backends'
import { Route as ClusterRouteImport } from './routes/cluster'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QueriesRouteImport } from './routes/queries'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StreamsRouteImport } from './routes/streams'
import { Route as TuningRouteImport } from './routes/tuning'
import { Route as ProjectsProjectIdProxiesNewRouteImport } from './routes/projects.$projectId.proxies.new'
import { Route as ProjectsProjectIdProxiesProxyIdEditRouteImport } from './routes/projects.$projectId.proxies.$proxyId.edit'

const ProjectsIndexLazyRouteImport = createFileRoute('/projects/')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const BackendsRoute = BackendsRouteImport.update({
  id: '/backends',
  path: '/backends',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/backends.lazy').then((d) => d.Route))
const ClusterRoute = ClusterRouteImport.update({
  id: '/cluster',
  path: '/cluster',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cluster.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/logs.lazy').then((d) => d.Route))
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/metrics.lazy').then((d) => d.Route))
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesRoute = QueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/queries.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const StreamsRoute = StreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/streams.lazy').then((d) => d.Route))
const TuningRoute = TuningRouteImport.update({
  id: '/tuning',
  path: '/tuning',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tuning.lazy').then((d) => d.Route))
const ProjectsIndexLazyRoute = ProjectsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any).lazy(() =>
  import('./routes/projects.index.lazy').then((d) => d.Route),
)
const ProjectsProjectIdProxiesNewRoute =
  ProjectsProjectIdProxiesNewRouteImport.update({
    id: '/$projectId/proxies/new',
    path: '/$projectId/proxies/new',
    getParentRoute: () => ProjectsRoute,
  } as any).lazy(() =>
    import('./routes/projects.$projectId.proxies.new.lazy').then(
      (d) => d.Route,
    ),
  )
const ProjectsProjectIdProxiesProxyIdEditRoute =
  ProjectsProjectIdProxiesProxyIdEditRouteImport.update({
    id: '/$projectId/proxies/$proxyId/edit',
    path: '/$projectId/proxies/$proxyId/edit',
    getParentRoute: () => ProjectsRoute,
  } as any).lazy(() =>
    import('./routes/projects.$projectId.proxies.$proxyId.edit.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backends': typeof BackendsRoute
  '/cluster': typeof ClusterRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/queries': typeof QueriesRoute
  '/settings': typeof SettingsRoute
  '/streams': typeof StreamsRoute
  '/tuning': typeof TuningRoute
  '/projects/': typeof ProjectsIndexLazyRoute
  '/projects/$projectId/proxies/new': typeof ProjectsProjectIdProxiesNewRoute
  '/projects/$projectId/proxies/$proxyId/edit': typeof ProjectsProjectIdProxiesProxyIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backends': typeof BackendsRoute
  '/cluster': typeof ClusterRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/queries': typeof QueriesRoute
  '/settings': typeof SettingsRoute
  '/streams': typeof StreamsRoute
  '/tuning': typeof TuningRoute
  '/projects': typeof ProjectsIndexLazyRoute
  '/projects/$projectId/proxies/new': typeof ProjectsProjectIdProxiesNewRoute
  '/projects/$projectId/proxies/$proxyId/edit': typeof ProjectsProjectIdProxiesProxyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backends': typeof BackendsRoute
  '/cluster': typeof ClusterRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/queries': typeof QueriesRoute
  '/settings': typeof SettingsRoute
  '/streams': typeof StreamsRoute
  '/tuning': typeof TuningRoute
  '/projects/': typeof ProjectsIndexLazyRoute
  '/projects/$projectId/proxies/new': typeof ProjectsProjectIdProxiesNewRoute
  '/projects/$projectId/proxies/$proxyId/edit': typeof ProjectsProjectIdProxiesProxyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backends'
    | '/cluster'
    | '/login'
    | '/logs'
    | '/metrics'
    | '/projects'
    | '/queries'
    | '/settings'
    | '/streams'
    | '/tuning'
    | '/projects/'
    | '/projects/$projectId/proxies/new'
    | '/projects/$projectId/proxies/$proxyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backends'
    | '/cluster'
    | '/login'
    | '/logs'
    | '/metrics'
    | '/queries'
    | '/settings'
    | '/streams'
    | '/tuning'
    | '/projects'
    | '/projects/$projectId/proxies/new'
    | '/projects/$projectId/proxies/$proxyId/edit'
  id:
    | '__root__'
    | '/'
    | '/backends'
    | '/cluster'
    | '/login'
    | '/logs'
    | '/metrics'
    | '/projects'
    | '/queries'
    | '/settings'
    | '/streams'
    | '/tuning'
    | '/projects/'
    | '/projects/$projectId/proxies/new'
    | '/projects/$projectId/proxies/$proxyId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackendsRoute: typeof BackendsRoute
  ClusterRoute: typeof ClusterRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  QueriesRoute: typeof QueriesRoute
  SettingsRoute: typeof SettingsRoute
  StreamsRoute: typeof StreamsRoute
  TuningRoute: typeof TuningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backends': {
      id: '/backends'
      path: '/backends'
      fullPath: '/backends'
      preLoaderRoute: typeof BackendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster': {
      id: '/cluster'
      path: '/cluster'
      fullPath: '/cluster'
      preLoaderRoute: typeof ClusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries': {
      id: '/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof QueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams': {
      id: '/streams'
      path: '/streams'
      fullPath: '/streams'
      preLoaderRoute: typeof StreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuning': {
      id: '/tuning'
      path: '/tuning'
      fullPath: '/tuning'
      preLoaderRoute: typeof TuningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexLazyRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/proxies/new': {
      id: '/projects/$projectId/proxies/new'
      path: '/$projectId/proxies/new'
      fullPath: '/projects/$projectId/proxies/new'
      preLoaderRoute: typeof ProjectsProjectIdProxiesNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/proxies/$proxyId/edit': {
      id: '/projects/$projectId/proxies/$proxyId/edit'
      path: '/$projectId/proxies/$proxyId/edit'
      fullPath: '/projects/$projectId/proxies/$proxyId/edit'
      preLoaderRoute: typeof ProjectsProjectIdProxiesProxyIdEditRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIndexLazyRoute: typeof ProjectsIndexLazyRoute
  ProjectsProjectIdProxiesNewRoute: typeof ProjectsProjectIdProxiesNewRoute
  ProjectsProjectIdProxiesProxyIdEditRoute: typeof ProjectsProjectIdProxiesProxyIdEditRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIndexLazyRoute: ProjectsIndexLazyRoute,
  ProjectsProjectIdProxiesNewRoute: ProjectsProjectIdProxiesNewRoute,
  ProjectsProjectIdProxiesProxyIdEditRoute:
    ProjectsProjectIdProxiesProxyIdEditRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackendsRoute: BackendsRoute,
  ClusterRoute: ClusterRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  QueriesRoute: QueriesRoute,
  SettingsRoute: SettingsRoute,
  StreamsRoute: StreamsRoute,
  TuningRoute: TuningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
